### ISSUE TITLE
React - Logout Redirect

### ISSUE THREAD

**Issue by kennyinthirathclq** [okta/okta-oidc-js#100]
Hey there,

I noticed that the React logout always redirects back to `/` even though the App Settings in the Dev Console allows you to set a Logout redirect URI.

Is this behavior intended?

https://github.com/okta/okta-oidc-js/blob/08629addbd6bea3c7d4248ed17b7a3de04d90f0f/packages/okta-react/src/Auth.js#L81-L85

**Comment by jmelberg-okta** [comment]
Hey @kennyinthirathclq. Redirecting back to `/` seems to satisfy most use cases, but for flexibility it probably makes sense to make this configurable.

This function should be something along the lines of:

```typescript
async logout(uri) {
   this._oktaAuth.tokenManager.clear(); 
   await this._oktaAuth.signOut(); 
   this._history.push(uri || '/'); 
 } 
```

I'll try and get this change in sometime over the next week or two.

**Comment by mschaeffner** [comment]
@jmelberg-okta Are you working on this? Or would you like that I implement this and then create a pull request, which you can review?

**Comment by mschaeffner** [comment]
This issue was resolve with #169 and can be close. Logout redirect paths is configurable in package okta-react >= 1.0.0

**Comment by jmelberg-okta** [comment]
Closing due to #169
