### ISSUE TITLE
AuthSdkError: Unable to parse a token from the url

### ISSUE THREAD

**Issue by mabc224** [okta/okta-oidc-js#121]
I am trying to authenticate a user. Upon Authentication, It calls `ImplicitCallback` and gives this error. 

I have defined my routes like this
```
<Route path="/" exact={true} component={HomePage} />
<SecureRoute path="/profile" component={ProfilePage} />
<Route path="/login" render={() => <LoginPage baseUrl={config.url} />} />
<Route path="/register" component={RegistrationForm} />
<Route path="/implicit/callback" component={ImplicitCallback} />
```
and remainging configuration

```
const auth = new Auth({
    history,
    issuer: config.issuer,
    client_id: config.client_id,
    redirect_uri: config.redirect_uri,
    onAuthRequired: ({history}) => history.push('/login')
});

ReactDOM.render(
    <Provider store={store}>
        <Router history={history}>
            <Security auth={auth}>
                <App />
            </Security>
        </Router>
    </Provider>,
    document.getElementById('root')
);
```

Please let me know what is wrong with it?

**Comment by robertjd** [comment]
Hi @mabc224 , can you show us what the error is?

You can also compare your application to our sample applications: https://github.com/okta/samples-js-react

Thanks!

**Comment by mabc224** [comment]
@robertjd Thanks, I just noticed that my app url was using `-admin` and my `issuer` value was also wrong. It is working fine now.

**Comment by mabc224** [comment]
@robertjd Please let me know how can I change a password of a user in react application? 
I read about that in simple js/server application, we can use this method, 
`https://developer.okta.com/docs/api/resources/users.html#change-password`
Is there any specific method to use in react application, as there is simple method to use for sign in.

**Comment by nbarbettini** [comment]
@mabc224 There is no method to change the user's password directly from your React code. You can change the user's password via the Users API (what you linked to), but that API call must be done from your backend code.

Feel free to open another issue if you need help with something else!

**Comment by mraible** [comment]
I was _almost_ able to solve this by changing my `onSuccess()` from this:

```js
onSuccess(res) {
  return this.props.auth.redirect({
    sessionToken: res.session.token
  });
}
```

To this:

```js
onSuccess(res) {
  this.props.auth._oktaAuth.token.getWithoutPrompt({
    sessionToken: res.session.token,
    responseType: ['token', 'id_token'],
    scopes: ['openid', 'profile'],
  }).then(async tokens => {
    for (let token of tokens) {
      if (token.idToken) {
        this.props.auth._oktaAuth.tokenManager.add('idToken', token);
      } else if (token.accessToken) {
        this.props.auth._oktaAuth.tokenManager.add('accessToken', token);
      }
    }
    this.setState({authenticated: true});
  })
}
```

However, now I get the following error when running in Electron:

<img width="1043" alt="screen shot 2018-06-02 at 6 05 41 pm" src="https://user-images.githubusercontent.com/17892/40881892-92cf7fb6-668f-11e8-802c-084d220f37b5.png">

**Comment by ey52fpv** [comment]
Getting the error in React SPA application in localhost on the /implicit/callback route. Can anyone help me here?

**Comment by swiftone** [comment]
@ey52fpv - The error message can come from a variety of causes, so you are better off opening a new issue.  

Does https://github.com/okta/okta-oidc-js/issues/736 look like it applies?  One user there (using the sign-in-widget as well) was able to get working, while another is still working with us to find the source of the problem.

**Comment by ey52fpv** [comment]
@swiftone Yes #736 matched to what I was looking for. Made the recommended changes to set the responseMode to query in widget and it worked. 

Thank you so much. You saved my day.

**Comment by wtsoli** [comment]
We are using 1.3.9, which is not the latest version of okta-react, I found out a way for work around this
instead of using provided ImplicitCallback Component, you can provide your own and add this to render() function:
if (!this.state.authenticated &&
this.state.errorCode === “INTERNAL” &&
this.state.error === “AuthSdkError: The redirectUri passed to /authorize must also be passed to /token”) {
return <Redirect to={"/path"} />;
}

the key thing here is letting this customized implicitcallback allow browser redirect to desired path, here “/path” is just an example, it should be your own one, usually the one you want to land user to after okta login procedure

Hope this helps
