### ISSUE TITLE
UMD build?

### ISSUE THREAD

**Issue by cmckni3** [okta/okta-oidc-js#131]
Wondering if a UMD build is going to be available. I see the ES module is being created but it's not being bound to `global`.

**Comment by cmckni3** [comment]
With a rollup build for a library, I get the following:

```
No name was provided for external module '@okta/okta-angular' in options.globals – guessing 'oktaAngular'
```

I also receive an error that `OktaAuthService` could not be resolved. I believe the error is related the the rollup warning and the definition of the ES module.

**Comment by cmckni3** [comment]
Any advice @jmelberg-okta?

**Comment by cmckni3** [comment]
The issue in particular is using the Angular version of the library in another library. I have a shared library that is built to a UMD module. I receive an error that the imports could not be resolved when importing services, for example `OktaAuthService`.

**Comment by jmelberg-okta** [comment]
@cmckni3 This is interesting. There seems to be a lot of confusion around this - notably captured [here](https://github.com/rollup/rollup/issues/1299#issuecomment-296347377).

I'll try to carve out some time this week (or next) to reproduce this. In the meantime - if you happen to come across a resolution, please let us know.

**Comment by cmckni3** [comment]
I found that lerna is binding the module to the top level. I think that is the issue. I might have some time to learn about lerna and configuration tomorrow.
