### ISSUE TITLE
Can I use the same for react-native app?

### ISSUE THREAD

**Issue by SureshCS-50** [okta/okta-oidc-js#132]

**Comment by mraible** [comment]
I published an article last week on scotch.io that shows how to authenticate with Okta. Maybe this will work for you? https://scotch.io/tutorials/build-a-react-native-app-and-authenticate-with-oauth-20

**Comment by SureshCS-50** [comment]
Thanks @mraible.. This worked for me :)

**Comment by jmelberg-okta** [comment]
@SureshCS-50 - Just so you're aware, we're scheduled to release a React Native SDK.

I'd **highly** recommend watching this repo for when that library drops!

**Comment by SureshCS-50** [comment]
Sure @jmelberg-okta 👍
