### ISSUE TITLE
How to test components WithAuth?

### ISSUE THREAD

**Issue by rafikiass** [okta/okta-oidc-js#133]
I know this is not an issue, but how do we test a component that's exported WithAuth? I tried to define the the auth props but this never worked. 
const minProps = {
  auth: {
    isAuthenticated: () =>true
  } 

Any tip will be appreciated.

**Comment by mraible** [comment]
If you set an id token and access token, isAuthenticated will return true. For example:

```ts
const tokens = ['foo','bar'];
for (let token of tokens) {
  if (token.idToken) {
    this.props.auth._oktaAuth.tokenManager.add('idToken', token);
  } else if (token.accessToken) {
    this.props.auth._oktaAuth.tokenManager.add('accessToken', token);
  }
}
```

**Comment by denchen** [comment]
I ran into the same problem. There are two ways of dealing with this. First, this is an example component that includes `isAuthenticated()` from `withAuth()`

```jsx
export class MyComponent exports React.Component {
  state = { authenticated: false, error: null };

  async componentDidMount() {
    try {
      const authenticated = await this.props.isAuthenticated();
      this.setState({ authenticated });
    } catch(error) {
      this.setState({ error });
    }
  }

  render() { /* render stuff */ }
}

export default withAuth(MyComponent);
```

Note that I'm exporting two things: the default component that includes `withAuth()`, and the base component without the higher-order component decoration. In your test, you can import both via:

```jsx
import WithAuthMyComponent, { MyComponent } = '../MyComponent';
```

To test the undecorated component (ie, _without_ `withAuth()`), you can easily mock the `auth` object. Here's an example:

```jsx
test('renders base component', done => {
  const auth = {
    isAuthenticated: jest.fn().mockImplementation(() => Promise.resolve(true))
  };
  const wrapper = shallow(<MyComponent auth={auth} />);

  // setImmediate() will wait for the promises to resolve.
  setImmediate(() => {
    wrapper.update();
    try {
      /* Make your assertions here */
      done();
    } catch (error) {
      done.fail(error);
    }
  });
}); 
```

Now, if you need to test the full decorated version, you can mock out the `okta-react` library itself:

```jsx
import * as React from 'react';
import { mount } from 'enzyme';
import WithAuthMyComponent from '../MyComponent';

jest.mock('@okta/okta-react', () => ({
  withAuth: Component => {
    const auth = {
      isAuthenticated: () => Promise.resolve(true),
      getAccessToken: () => Promise.resolve('randomauthtoken')
    };
    return props => <Component auth={auth} {...props} />;
  }
}));

describe('MyComponent', () => {
  test('works with withAuth()', done => {
    const wrapper = mount(<WithAuthMyComponent />);
    setImmediate(() => {
      wrapper.update();
      try {
        /* Make your assertions here */
        done();
      } catch (error) {
        done.fail(error);
      }
    });
  });
});
```

The first way is simpler, and in general, probably the way you want to do your testing, without using an HOC. But of course, if you care and want full code coverage, you need to have at least one test that uses the decorators.

**Comment by mukarramali-tw** [comment]
What if we are using cypress for an end to end testing? 
How do we stub auth using cypress?

**Comment by mraible** [comment]
@mukarramali-tw If you're doing end-to-end testing, I don't think you want to mock anything. You want your app to go through its normal flow, including authentication.

**Comment by gkoychev** [comment]
@MukarramAli1729 have you found any solution for mocking in cypress?

**Comment by MukarramAli1729** [comment]
I found some workarounds, felt like an anti-pattern, so didn't go with them

**Comment by swiftone** [comment]
Closing this ticket as advice regarding React testing with Cypress is out-of-scope for this project.  We recommend users look at our existing unit tests to see what advice we can offer.
