### ISSUE TITLE
Timezone Support

### ISSUE THREAD

**Issue by adamjcsmith** [okta/okta-oidc-js#163]
First noticed this issue when one of our engineers was working abroad, one hour ahead of GMT (CET time). As soon as he'd log in to our app, using okta-react, he'd be logged out. Further examination revealed that the expiration time of the `id_token` was set to the same local time as he logged in.

Since ID tokens always expire after an hour, it seems as if the tokens were being requested based on GMT time. Is there a way to check this? There's possibly a way to set timezone and/or locale on the profile settings, but I can't find a way to override the master profile.

Since British Summer Time (GMT + 1) came into force yesterday morning, we are all experiencing the same issue.

**Comment by aarongranick-okta** [comment]
@adamjcsmith we believe this issue has been fixed. Are you still experiencing any issues with okta-react?

**Comment by denysoblohin-okta** [comment]
Closing after no reponse
