### ISSUE TITLE
ImplicitCallback doesn't retain query params or hash in the URL

### ISSUE THREAD

**Issue by pallavi** [okta/okta-oidc-js#174]
On login, `Auth` sets `secureRouterReferrerPath` to the pathname, but doesn't store any search params or hash that are part of the URL. So `ImplicitCallback` redirects back to the referrer pathname, but it doesn't retain query params or hash.

https://github.com/okta/okta-oidc-js/blob/76e761b15710653970bdd8591e906fce11f38059/packages/okta-react/src/Auth.js#L84
https://github.com/okta/okta-oidc-js/blob/76e761b15710653970bdd8591e906fce11f38059/packages/okta-react/src/ImplicitCallback.js#L43

**Comment by robertjd** [comment]
This change is now available in version 1.0.2 on npm. Thanks again @pallavi !
