### ISSUE TITLE
okta-react: Make Auth.js service available outside of React components

### ISSUE THREAD

**Issue by alaister** [okta/okta-oidc-js#19]
Hi,
It would be useful if you made the methods in the Auth class available without having to use the withAuth HOC.

This is useful when you need to use the access token outside of React. For example when using [Apollo Client](http://dev.apollodata.com/react/auth.html#Header).

Thanks

**Comment by leandroleo02** [comment]
Hi!

I have a similar issue, any workaround?

Thanks!

**Comment by gaastonsr** [comment]
Same here but with Vue.

**Comment by robertjd** [comment]
This should now be available in 0.0.11, as resolved by #97.  Please give it a try and let us know if it works.
