### ISSUE TITLE
Revoke user sessions does not logout user

### ISSUE THREAD

**Issue by jdrake** [okta/okta-oidc-js#190]
After clearing the user session:
![image](https://user-images.githubusercontent.com/639956/38711349-f449d248-3e79-11e8-92b0-fd46b1186ff8.png)

the currently logged in user on my local server can still refresh the page. Does this middleware not verify the token after initial login?

My server.js looks like:
```js
const express = require('express');
const session = require('express-session');
const { ExpressOIDC } = require('@okta/oidc-middleware');
const okta = require('@okta/okta-sdk-nodejs');

const app = express();

const client = new okta.Client({
  orgUrl: 'https://dev-***.oktapreview.com/',
  // Obtained from Developer Dashboard
  token: '***'
});

// session support is required to use ExpressOIDC
app.use(session({
  secret: 'this should be secure',
  resave: true,
  saveUninitialized: false
}));

const oidc = new ExpressOIDC({
  issuer: 'https://dev-***.oktapreview.com/oauth2/default',
  client_id: '***',
  client_secret: '***',
  redirect_uri: 'http://localhost:3000/authorization-code/callback',
  scope: 'openid profile'
});

// ExpressOIDC will attach handlers for the /login and /authorization-code/callback routes
app.use(oidc.router);

app.get('/', (req, res) => {
  if (req.session && req.userinfo) {
    return res.redirect('/docs')
  }
  res.redirect('/login')
});

app.get('/logout', (req, res) => {
  req.session.destroy();
  req.logout();
  res.redirect('/');
});

app.get('/docs', oidc.ensureAuthenticated(), async (req, res) => {
  res.send(JSON.stringify(req.userinfo));
});

oidc.on('ready', () => {
  app.listen(3000, () => console.log('Started!'));
});

oidc.on('error', (err) => {
  console.log('Unable to configure ExpressOIDC', err);
});
```

**Comment by robertjd** [comment]
Hi @jdrake , thanks for the question.  That's correct, what this library does is create a cookie-based session for you in the express app, this session isn't tied to Okta.  It simply stores the user info (what you see at `req.userinfo`) that was obtained during the initial authentication request.

The session you're clearing in that screenshot is the Okta session, which is meant for singe-sign-on purposes.  That is a cookie that lives on your Okta org domain.  This is why you don't see an effect on your application.

If you want to remotely revoke access to your application, you would need to model it with access tokens, where the access tokens are meant to be a bearer token that grants access to your application.  As you say you'd need to send those tokens to our Oauth introspection endpoint to see if they have been revoked or not.

Let me know if this helps!

**Comment by jdrake** [comment]
Ahh ok, thanks for the helpful explanation.

Following API docs for introspect (https://developer.okta.com/docs/api/resources/oidc.html#introspect), I'm sending query string params:
- token: `<access token from the okta sign in flow>`
- token_type_hint: access_token
- client_id
- client_secret

and headers:
- Content-Type: application/json
- Accept: application/json

But I'm receiving:
```
{
  "errorCode": "E0000021",
  "errorSummary": "Bad request.  Accept and/or Content-Type headers likely do not match supported values.",
  "errorLink": "E0000021",
  "errorId": "oaeAhTdoAXvQ2SCXJSYyHFyew",
  "errorCauses": []
}
```

Every combination of 1 or both or none of the headers worked. 

Is there something missing here?

**Comment by jdrake** [comment]
Or potentially I may be forced into using the Custom Login Page and not the Okta-hosted Page...

**Comment by jmelberg-okta** [comment]
Hi @jdrake,

Looks like the issue you're running into is passing the `Content-Type: application/json` header. The [`/introspection`](https://developer.okta.com/docs/api/resources/oidc.html#introspect) documentation specifies:

> The following parameters can be posted as a part of the URL-encoded form values to the API.

Can you try changing the header value to `Content-Type: application/x-www-form-urlencoded`?

I'd also suggest checking out the [Postman Collection](https://developer.okta.com/docs/api/getting_started/api_test_client#collections-quick-reference) on API Access Management.

Hope this helps!

**Comment by jdrake** [comment]
That did it, thanks!

I ended up adding some code to the home page after the login succeeds that sends the current Okta session ID to the backend:
```js
signIn.session.get((res) => {
  if (res.id) {
    fetch(
      `/sessions/${res.id}`,
      {
        method: 'PUT',
        credentials: 'same-origin'
      }
    )
      .then((response) => {
        console.log(response)
      })
      .catch((err) => {
        console.error(err)
      })
  }
})
```
(^ Is there a better way to access the Okta session ID in the express server? I couldn't seem to access the access or id token in the backend that are necessary for `/introspect`.)

Then on the backend, store the session ID in the express session:
```js
app.put(
    '/sessions/:sessionId',
    oidc.ensureAuthenticated(),
    (req, res, next) => {
      if (res.statusCode === 401) {
        return next();
      }
      req.session.oktaSessionId = req.params.sessionId
      res.sendStatus(204)
    }
  )
```

Then created a piece of middleware to check the validity of the Okta session:
```js
const validateSession = () => {
    return async function _validateSession(req, res, next) {
      const { oktaSessionId } = req.session
      try {
        if (oktaSessionId) {
          const session = await oktaClient.getSession(oktaSessionId)
          if (session.status === 'ACTIVE') {
            return next()
          }
        }
        res.redirect('/logout')
      } catch (err) {
        if (err.errorCode === 'E0000007') {
          // Session not found
          return res.redirect('/logout')
        }
        // Unhandled error
        next(err)
      }
    }
  }
```

**Comment by jmelberg-okta** [comment]
We've updated our this library to return tokens with our [`1.0.0` release](https://github.com/okta/okta-oidc-js/pull/300).

While we do not have the ability to terminate the Okta session via this library yet, you can use the `end_session_endpoint` (documented [here](https://developer.okta.com/docs/api/resources/oidc#logout)) to remove the user's current session in Okta.

Hope this helps! We are going to close this issue as what was asked originally has been resolved.
