### ISSUE TITLE
is it possiable run okra login only on some users?

### ISSUE THREAD

**Issue by eran10** [okta/okta-oidc-js#196]
can i use this middlewareonly on some of my users ?
i have one login page,
once i find the user (in the backend express nope app), according to some logic i want to enforce him login again with OKTA but for the rest of the users to pass on without okta, can i do this with this package (oidc-middleware) ?

**Comment by nbarbettini** [comment]
Hey @eran10 - this is a good question but a little bigger than the scope of this library. Can you post over on the [Okta Developer Forums](https://devforum.okta.com) instead?
