### ISSUE TITLE
Cannot configure/pass IDP param for authorize request

### ISSUE THREAD

**Issue by robertjd** [okta/okta-oidc-js#198]
I'm seeing this in react but I assume this is across all our front-end libs:

https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/src/Auth.js#L100-L104

We have a hard coded set of params that we pass on to `getWithRedirect()`, so if I want to add other parms, such as idp, it's not possible at the moment.

**Comment by jmelberg-okta** [comment]
We currently account for `additionalParams` in both [Angular](https://github.com/okta/okta-oidc-js/blob/master/packages/okta-angular/src/okta/services/okta.service.ts#L140-L145) and [Vue](https://github.com/okta/okta-oidc-js/blob/master/packages/okta-vue/src/Auth.js#L20-L23) - so we should probably repeat the logic here.

**Comment by jmelberg-okta** [comment]
This issue has been resolved via #275 and released under `@okta/okta-react@1.1.0`
