### ISSUE TITLE
Auto Refresh @okta/okta-angular

### ISSUE THREAD

**Issue by KrishnaJanardhanan** [okta/okta-oidc-js#205]
How to auto refresh the Id token without refreshing/redirecting screen

**Comment by Krishna-Iff** [comment]
Any update?

**Comment by Krishna-Iff** [comment]
Is there predefined method available to refresh the token like below.

Package : angular-oauth2-oidc
Method :   this
      .oauthService
      .silentRefresh()
      .then(info => this.logger.log('refresh ok', info))
      .catch(err => this.logger.log('refresh error', err));

**Comment by jmelberg-okta** [comment]
Sorry for the delay @KrishnaJanardhanan - you can use the [`token.refresh`](https://github.com/okta/okta-auth-js#tokenrefreshtokentorefresh) method to do this.

```javascript
const idToken  = authClient.tokenManager.get('idToken');

authClient.token.refresh(tokenToRefresh)
.then(function(freshToken) {
  // manage freshToken
})
.catch(function(err) {
  // handle err
});
```
