### ISSUE TITLE
oidc-middleware: Errors with request timeout when behind proxy

### ISSUE THREAD

**Issue by alamuv** [okta/okta-oidc-js#208]
### Issue Description
oidc-middleware always emits error 'Request timeout' when running my app behind proxy. I believe `oidcUtil.createClient` errors with request timeout when it tries to do `Issuer.discover(issuer)`

#### Why does oidc-middleware timeout behind proxy?
`openid-client` module that oidc-middleware uses, uses `got` module which does not use environment-defined http(s) proxies. Inorder to use them, openid-client recommends using the `request` module.
https://github.com/panva/node-openid-client#proxy-settings

#### Possible Solution
Doing `npm install request --save`  and
Adding `Issuer.useRequest();` to oidcUtil.js enables the oidc-middleware use https proxies.

**Comment by robertjd** [comment]
Thanks @alamuv ! Did `Issuer.useRequest();` solve this problem for you?  If so I will add this solution to the README.

**Comment by alamuv** [comment]
@robertjd To solve this, I had to include the package `request` as a dependency on a clone of `oidc-middleware` and then add `Issuer.useRequest()` above this [line](https://github.com/okta/okta-oidc-js/blob/master/packages/oidc-middleware/src/oidcUtil.js#L38).

This meant that I now need to maintain a clone of the repo with my change. Do you see a better way of handling this? If so, I can update the way I'm addressing this.

It would be great if I could pass in an optional config to oidc-middleware to enable proxy.

**Comment by robertjd** [comment]
Hi @alamuv , thanks for the info!  It should be possible to configure the request library outside of the oidc-middleware library, such that you won't need to maintain a fork of it.  Can you take a look at #232 ? I'd like to know if these new instructions work for you.

**Comment by alamuv** [comment]
@robertjd Tried it out in my setup. This works well !!

**Comment by abhineet11** [comment]
const Issuer = require('openid-client').Issuer;

Issuer.useRequest();

Tried adding the above line but getting Error: tunneling socket could not be established, statusCode=407

Please help me

**Comment by AnudeepG1507** [comment]
useRequest and useGot methods were removed, with the maintenance mode and inevitable deprecation of the request module i've decided to only support got as an http request library  in openid-client version [3.0.0](https://github.com/panva/node-openid-client/compare/v2.5.0...v3.0.0) (2019-05-11). But  @okta/oidc-middleware": "^4.5.1" uses  "openid-client": "3.12.2",
