### ISSUE TITLE
okta-react - HashRouter has issues with implicit callback

### ISSUE THREAD

**Issue by rodoabad** [okta/okta-oidc-js#210]
Assume the following where restricted is wrapped with `SecureRoute` and anonymous routes are only routed with the default `Route`.

```jsx
import {ImplicitCallback, Security} from '@okta/okta-react';
import {Route, HashRouter as Router} from 'react-router-dom';

const RouteConfig = () => (
    <Router>
        <Security
            client_id={clientId}
            issuer={oktaDomain}
            redirect_uri={`${window.location.origin}/implicit/callback`}
        >
            <HelloRoute/>
            <AnonymousRoute/>
            <RestrictedRouteA/>
            <RestrictedRouteB/>
            <Route
                component={ImplicitCallback}
                path='/implicit/callback'
            />
        </Security>
    </Router>
);
```

Since redirecting back, you are redirected back to `http://localhost:5555/implicit/callback#/` because the path for your `ImplicitCallback` component relies on `http://localhost:5555/#/implicit/callback` and not `http://localhost:5555/implicit/callback`.

At Okta, you cannot use a hash. You will get the following error.

```
The redirect URIs must not contain a fragment identifier.
```

**Comment by jmelberg-okta** [comment]
Hey @rodoabad,

The OAuth 2.0 spec [requires that only one hash fragment exist](https://tools.ietf.org/html/rfc6749#section-3.1.2) on a redirection endpoint.

Please see the conversation in [#29](https://github.com/okta/okta-oidc-js/issues/29#issuecomment-342339960) for more information.

**Comment by rodoabad** [comment]
@jmelberg-okta is that the reason why hash history is not supported in React Router?

**Comment by rodoabad** [comment]
Sweet, thanks @jmelberg-okta I'll read that issue and close this if my question has been answered.
