### ISSUE TITLE
Cannot use 'in' operator to search for 'window' in undefined

### ISSUE THREAD

**Issue by chuckshaw** [okta/okta-oidc-js#213]
I'm integrating with my react app for the first time and running into this issue:

```
Uncaught TypeError: Cannot use 'in' operator to search for 'window' in undefined
    at reqwest.js:15
    at reqwest.js:8
    at Object.<anonymous> (reqwest.js:7)
    at __webpack_require__ (bootstrap cec33e3f03e680d4b2cf:19)
    at Object._typeof (reqwestRequest.js:13)
    at __webpack_require__ (bootstrap cec33e3f03e680d4b2cf:19)
    at Object.<anonymous> (index.js:1)
    at __webpack_require__ (bootstrap cec33e3f03e680d4b2cf:19)
    at Object.<anonymous> (index.js:2)
    at __webpack_require__ (bootstrap cec33e3f03e680d4b2cf:19)
```

**Comment by mraible** [comment]
Are you trying to run your React app with server rendering?

**Comment by mraible** [comment]
This is a known issue. Our Auth SDK (which React is based on) does not support server rendering yet. If there's another OIDC library for React that works on the server, you should be able to use it with Okta.

**Comment by chuckshaw** [comment]
@mraible ah thanks for letting me know.  Is there an ETA on a fix for that?  In the mean time i'll go investigate other react clients.

**Comment by mraible** [comment]
AFAIK, there are no plans to add server rendering support.

**Comment by jmelberg-okta** [comment]
Hi all,

We have no immediate plans to support this, as it requires a bit of refactoring in our [`okta-auth-js`](https://github.com/okta/okta-auth-js) repo. Please give a 👍 to [this issue](https://github.com/okta/okta-auth-js/issues/122) reported in `okta-auth-js`, as we will be tracking our progress there.
