### ISSUE TITLE
After npm run build, Failed minified @okta/jwt-verifier/lib.js

### ISSUE THREAD

**Issue by romainlouvet** [okta/okta-oidc-js#215]
I have checked and didn't found this issue

Here is the callstack
`Failed to minify the code from this file:     ./node_modules/@okta/jwt-verifier/lib.js:16
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@5.8.0
3 info using node@v6.13.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle Cetautomatix@0.1.0~prebuild: Cetautomatix@0.1.0
6 info lifecycle Cetautomatix@0.1.0~build: Cetautomatix@0.1.0
7 verbose lifecycle Cetautomatix@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle Cetautomatix@0.1.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/elouen/react/toto/ihm-cetautomatix/node_modules/.bin:/home/elouen/.sdkman/candidates/maven/current/bin:/home/elouen/.sdkman/candidates/java/current/bin:/home/elouen/opt/atom:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/usr/local/go/bin
9 verbose lifecycle Cetautomatix@0.1.0~build: CWD: /home/elouen/react/toto/ihm-cetautomatix
10 silly lifecycle Cetautomatix@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
11 silly lifecycle Cetautomatix@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle Cetautomatix@0.1.0~build: Failed to exec build script
13 verbose stack Error: Cetautomatix@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid Cetautomatix@0.1.0
15 verbose cwd /home/elouen/react/toto/ihm-cetautomatix
16 verbose Linux 4.4.0-127-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v6.13.1
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error Cetautomatix@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the Cetautomatix@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
@okta/jwt-verifier/lib.js
`

here my package.json
https://gist.github.com/romainlouvet/593af70797e899fa6d78683d48c165cb
Can you help me ?

**Comment by robertjd** [comment]
Hi @romainlouvet , thanks for the question.  The `@okta/jwt-verifier` library is meant for use on the server-side in a Node/Express application, it won't compile into a front end application.  I see that this isn't mentioned in the readme, I'm going to fix that.

Are your trying to use it in your front-end application?  Depending on what you need to do, you can use the `@okta/okta-react` or `@okta/okta-auth-js` libraries.  If you tell me more about what you're trying to achieve I could point you in the right direction.

**Comment by robertjd** [comment]
Hi @romainlouvet , I'm going to close this issue for now, but please reach out if you're still working with this.
