### ISSUE TITLE
Authentication Loop

### ISSUE THREAD

**Issue by cmcconne** [okta/okta-oidc-js#217]
I am using `@okta/okta-angular` and I am stuck in a refresh token loop.  If I look at my network tab in Chrome Dev Tools, the `authorize?...` call is happening repeatedly.  Also, if I use the `@okta/okta-auth-js` to gain access to the Token Manager, I can listen to the `'refresh'` event.  If I put a breakpoint in my callback for this event, it is getting hit repeatedly.

I'm not sure why I'm stuck in this loop as colleagues with the same code base are not running into this.  We have updated our npm packages to the latest.  But the issue remains.  Can I get some help diagnosing what's causing the issue?

**Comment by cmcconne** [comment]
Also, we've tried logging in as other users.  The problem seems to be on this machine alone...

**Comment by mraible** [comment]
Thanks for reporting back and letting us know what the issue was!
