### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by DThanhNg** [okta/okta-oidc-js#221]
I got this error when running a react webapp, trying to login to okta.
I found out that failed in okta-react/dist/Auth.js at 

localStorage.setItem('secureRouterReferrerPath', (0, _stringify2.default)(fromUri ? { pathname: fromUri } : this._history.location));

Console.log() printed that 'fromUri' is a Proxy object.

**Comment by dhavalsoni2001** [comment]
I also get the same error. Any update @DThanhNg ?

**Comment by DThanhNg** [comment]
At the moment, I change in okta-react/dist/Auth.js line 314:
localStorage.setItem('secureRouterReferrerPath', fromUri || this._history.location.pathname);
to:
localStorage.setItem('secureRouterReferrerPath', (0, _stringify2.default)(this._history.location));

I don't know how long it will take Okta team to fix this problem

**Comment by mraible** [comment]
@DThanhNg Send us a PR to fix and we'll try to get it into the next release. ;)

**Comment by thanaratjaruenying** [comment]
Is it fixed? I still get this error when login.

**Comment by ersinciftci** [comment]
Any update on this? I would open a PR that removes `fromUri ? { pathname: fromUri }` part (it works when I test on my local), but I feel like it's there for a reason and needs to be fixed in a better way?

**Comment by robertjd** [comment]
Hi @ersinciftci and @thanaratjaruenying , thanks for confirming this.  Can you show me how you're calling `auth.login(:fromUri)`?  Are you passing it anything as the `fromUri` parameter?  For reference I'm using our [Okta React + Okta Hosted Login Example](https://github.com/okta/samples-js-react/tree/master/okta-hosted-login) and I'm looking at the Navbar component:

https://github.com/okta/samples-js-react/blob/master/okta-hosted-login/src/Navbar.jsx#L36

By default we pass the `/` string for `fromUri`, but I've also tried removing that and passing nothing.  In either case I don't see the error that you are seeing?

Thanks!

**Comment by ersinciftci** [comment]
Hi @robertjd , I think I know what's going on now. In this example https://www.npmjs.com/package/@okta/okta-react#show-login-and-logout-buttons it does `<button onClick={this.props.auth.login}>Login</button>` but it should actually be `<button onClick={() => this.props.auth.login()}>Login</button>`. I changed it in my code and it's fixed.

**Comment by robertjd** [comment]
Ah!  Well that's our bad, I'm updating the docs via #238. JFYI that we actually think it's best to write `login()` and `logout()` member methods on the component, which delegate to the `auth` API (you can see this in the PR)

@DThanhNg @dhavalsoni2001 @thanaratjaruenying can you look at the response above and let me know if this fixes the issue for you?  Thanks!

**Comment by robertjd** [comment]
Closing this issue as it seems like it was a documentation problem, @DThanhNg @dhavalsoni2001 @thanaratjaruenying please see above and re-open if you're still seeing issues.  Thanks!
