### ISSUE TITLE
okta Vuejs implicitCallback components handling error authentication

### ISSUE THREAD

**Issue by anasameur** [okta/okta-oidc-js#225]
Problem:

When using the okta-vue package, if a user are authenticated but are not assigned to the client application there is no way to handle this error.

Solution: 
```
export default {
  name: 'ImplicitCallback',
  data: () => ({
    error_message: '',
    error: false,
  }),
  async beforeMount() {
    try {
      await this.$auth.handleAuthentication();
      this.$router.replace({
        path: this.$auth.getFromUri(),
      });
    } catch (e) {
      // handle error
      this.error_message = e.message;
      this.error = true;
    }
  },
  render(createElement) {
    if (this.error) {
      return createElement('div', this.error_message);
    }
    return createElement;
  },
};
```

**Comment by robertjd** [comment]
Hi @anasameur , thank you for this!  There's a similar conversation going on in #234, where @n-zeplo would instead want to redirect the user to the root of the app.  Both are valid use cases, so I'm #236 I'm proposing to show the error by default, but provide a handler that lets that behavior be overridden.  Can you take a look at let me know what you think?

**Comment by anasameur** [comment]
Hi @robertjd Thanks. This was a quick fix to catch the error and display it to the end user as @n-zeplo  said.
I also approve #236 does a better job of handling the error specially when show the error to the end user if this happens, and adding the global error handler onOAuthRedirectError to let developer inject any error callback.
