### ISSUE TITLE
[oidc-middleware] How to get the access token?

### ISSUE THREAD

**Issue by viniciusgama** [okta/okta-oidc-js#226]
Hey,

I'm trying to implement [this flow](https://developer.okta.com/blog/2018/04/10/oauth-authorization-code-grant-type) in my application and I'm not being able to request an access_token with the code that is returned from OKTA. I imagine that the code was already used(probably by the passport oidc plugin) and because of that, it was expired.

In case this is being returned by the middleware I could not find in the documentation and in the code where it's being stored.

Any help would be appreciated.

**Comment by robertjd** [comment]
Hi @viniciusgama , thanks for the question!  It looks like we don't expose this right now, but we should.  I'm going to triage this for work, watch this issue for a sprint assignment so that you can know when we're working on this.

**Comment by viniciusgama** [comment]
thanks for the reply @robertjd. I'll keep an eye on the issue.

**Comment by coreyperkins** [comment]
I need this as well! Thanks!

**Comment by tusharbudhe0302** [comment]
It's should n't be a bug. Why you don't close this issue. Any ways developer must know how to do session magnet on server.

This integration depends on sessions to store user information. Ensure the express-session middleware is added before you add ExpressOIDC. By default, the session middleware uses a MemoryStore, which is not designed for production use. Use another session store for production.

https://github.com/expressjs/session#compatible-session-stores

You can close this issue.

**Comment by robertjd** [comment]
Hi @tusharbudhe0302 , thanks for the input.  While we do create an express session for you, I do imagine it's useful to have the access token.  The scenario I imagine is one where the access token gives the end-user access to some remote resource, and that the back-end will use the access token to retrieve the resource on behalf of the user.  

@coreyperkins and @viniciusgama , could you share the use cases that you have here?  Thanks!

**Comment by coreyperkins** [comment]
@robertjd I agree with your analysis. In my case I need to retrieve the access token in my client application so that I can pass it to my Rest API (resource server) to retrieve user data. If it is available in the session I could go to my session store (a doc db) and retrieve it, but it does seem reasonable to go ahead and give us the ability to snag via the typical flow as well. Thank you!

**Comment by mathieux51** [comment]
@viniciusgama, I had the problem and I ended up using [this](https://github.com/fischerdan/passport-okta-oauth).

**Comment by robertjd** [comment]
Hey @mathieux51 , thanks for that info.  I see that [passport-okta-oauth](https://github.com/fischerdan/passport-okta-oauth) lets you get the access token.  Are there other features of that library that you think we should consider?

**Comment by robertjd** [comment]
@coreyperkins in your case, when you say "client application", are you referring to a browser application, or your express application?

**Comment by coreyperkins** [comment]
@robertjd Express Application

**Comment by mathieux51** [comment]
@robertjd, the access token was the only thing that I was missing.

**Comment by coreyperkins** [comment]
@robertjd I dug into the code today and I found where the id and access tokens are available inside of your oidcUtil.js file (see attachment). It appears to me that if they were attached to the userinfo object they could be readily available for an express app to snag, feed to a client/UI layer, and use to make api calls. Does this analysis seem correct, if not, could you provide a bit more insight? (curiousity and the cat, and all).

<img width="1034" alt="screen shot 2018-07-26 at 12 26 46 pm" src="https://user-images.githubusercontent.com/429696/43278202-f88f834a-90cf-11e8-9d9d-b8da26a9000e.png">

**Comment by jmelberg-okta** [comment]
Thanks for the feedback all!

We've released a new version of [`@okta/oidc-middleware`](https://www.npmjs.com/package/@okta/oidc-middleware) that now exposes the requested tokens.

To see how it is used, check out [`req.userContext`](https://github.com/okta/okta-oidc-js/tree/master/packages/oidc-middleware#requsercontext) in our README.
