### ISSUE TITLE
okta-react: Why doesn't ImplicitCallback push to history on redirect?

### ISSUE THREAD

**Issue by Gulci** [okta/okta-oidc-js#23]
Let's say I have my router set up just like your example:
```
<Router>
  <Security issuer={config.issuer}
    client_id={config.clientId}
    redirect_uri={config.redirect_uri} >
    <Route path='/' exact={true} component={Home}/>
    <Route path='/implicit/callback' component={ImplicitCallback} />
  </Security>
</Router>
```
Once I've successfully authenticated, all is well and I'm redirected back to my application as expected... unless I try to refresh. 

Because the ImplicitCallback component is using `<Redirect to={pathname} />` and not `<Redirect push to={pathname} />`, my history isn't overwritten and I get an error when I try to refresh the page after being redirected: `AuthSdkError: Unable to parse a token from the url` because my window location is still `http://localhost:3000/implicit/callback`.

I think the fix may be to just specifiy `push` to make sure that when you're redirected back from Okta, the desired location is pushed onto the history stack so that when the user refreshes they aren't revisiting `/implicit/callback`.

If I'm wrong on this, I'd appreciate a pointer :)

**Comment by mraible** [comment]
I'm experiencing this issue as well. Any ideas on how to fix @robertjd?

**Comment by mraible** [comment]
After some more research, this only appears to happen in Firefox 57. I'm on macOS Sierra 10.12.6. 

It works as expected on Safari (v11.0.1) and Chrome (v62.0.3202.94).

**Comment by mmaaww** [comment]
encountered the same issue, any suggestion on solution. I have the similar configuration for two servers, one works fine while the other fails.

**Comment by hjain1130** [comment]
any suggestion on fix of above issue? facing the same problem

**Comment by ptxd** [comment]
same here, I have been trying some workarounds but none work so far

**Comment by tbellerose** [comment]
Had the same issue. To experiment and test Gulci's theory, I copied the ImplicitCallback class from the okta-react source and added push={true} to the Redirect. Working as expected in all browsers now.

**Comment by robertjd** [comment]
@tbellerose yeah, that's the tradeoff here. We chose to not push because we don't want that callback page to be on the history stack.  Is this an issue that can be solved by react router?

**Comment by Tony-Hu** [comment]
I met the same problem in Firefox. And I just solved it without modify the source code.
First, create a new js file named `helper.js`. Copy the code below.
``` js
import {createBrowserHistory} from "history";
export default createBrowserHistory();
```

Secondly, In your React Router,  import the function:
```
import history from './history';
```
modify the Router tag from `<Router>` to `<Router history={history}>`.

And the last step, also import the `history` function, and add the code in a proper location:
```js
if (authenticated !== this.state.authenticated) {
    //Other logic
    if (history.location.pathname !== `/`) {
      history.push(`/`);
    }
    //Other logic
}
```
Notice that `/` can be replaced by your actual relevant path.
Then it works with my Firefox 66.0.3 on MacOS 10.14.4

**Comment by swiftone** [comment]
@Tony-Hu Thanks for the suggestion! 

As there haven't been additional complaints in the last 6 months, I'm closing the ticket and recommending that anyone encountering difficulties with the default implementation look at @Tony-Hu 's suggestion.  

If anyone has a problem that isn't solved by that feel free to reopen the issue or create a new one and reference this issue there.

**Comment by ImantsSkultans** [comment]
> if (history.location.pathname !== `/`) {
>     history.push(`/`);
> }

This hack only works if You accessing root, it fails (it clears any sub path) - when You opening some link which navigates to some sub page, fore example: mysite.com/about.

Still having issue with Firefox (v68.6.1) - ways to reproduce - when app loaded for first time (after OKTA authentication) - press browsers refresh button. Page refreshes and shows: "AuthSdkError: Unable to retrieve OAuth redirect params cookie"
Address bar shows: yoursite.com/implicit/callback#access_token=...
You can easly reproduce it by doing it in FF in Private Mode.

In Chrome everything is ok.

**Comment by swiftone** [comment]
@ImantsSkultans - We've updated how we handle the redirection, so this issue covers a slightly different scenarion.  I'm moving your comment into a new issue so we can properly track it.
