### ISSUE TITLE
oidc-middleware routes.callback.path not respected

### ISSUE THREAD

**Issue by rdegges** [okta/okta-oidc-js#231]
In the docs it says that I should be able to customize the route for the callback handler by overwriting the value:

```javascript
ExpressODIC({
  routes: {
    callback: {
      path: "/something/else"
    }
  }
});
```

Unfortunately, it appears that setting isn't being respected. Instead, the redirect flow always attempts to hit the default `/authorization-code/callback` URI =/

**Comment by zypA13510** [comment]
Just in case you missed this, you also need to configure your `redirect_uri`, and add your `redirect_uri` in Okta admin panel.

**Comment by robertjd** [comment]
@rdegges is this still an issue, or was it resolved by @zypA13510 's suggestion?

**Comment by rdegges** [comment]
@robertjd no -- the issue persists regardless of what redirect URIs you've got in the web panel. The setting is just not used/applied in any meaningful way.

**Comment by zypA13510** [comment]
I didn't mean the web panel. I mean `redirect_uri` on ExpressOIDC:
```
ExpressODIC({
  redirect_uri: "http://example.com/something/else",
  routes: {
    callback: {
      path: "/something/else"
    }
  }
});
```

**Comment by robertjd** [comment]
@rdegges ^

**Comment by rdegges** [comment]
:o This fixed it for me. I must have missed this when I was performing my updates.
