### ISSUE TITLE
[okta-react-native] Upgrade to 0.56

### ISSUE THREAD

**Issue by robertjd** [okta/okta-oidc-js#240]
Changelog here: https://github.com/facebook/react-native/releases/tag/v0.56.0
 
Per #239 this upgrade had some downstream affects on jest, which would need to be sorted out

**Comment by oleggnidets-okta** [comment]
Hi there,
We've placed the SDK in [separated repo](https://github.com/okta/okta-react-native). Now we support React Native >=0.63.0.
