### ISSUE TITLE
OktaAuthGuard not routing to login page when session expires

### ISSUE THREAD

**Issue by MarcusChamberlain** [okta/okta-oidc-js#245]
I'm using OktaAuthGuard on my application routes. I have my set my session lifetime to expire after 10 minutes (for testing) in my Okta account. When I let the page sit for 15 minutes and then refresh the page, I run the following code:

````  
  this.signIn.session.get(function (res) { 
	if (res.status === 'INACTIVE') { 
        console.log('session is inactive);
      }
    });`
````

The session has expired so this line is hit, however the auth guard doesn't seem to be sending me to my login screen. I had a look in the auth guard code and I don't see any checks for the users session. 

If I had to make a guess, I would say that while my session has expired my access token is still valid and that once the token expires then auth guard will kick in. If that is the case, I'm not sure where the access token lifetime would be set. I added an access policy to my authorization server and set the access token to expire after 5 minutes, but it doesn't seem to make any difference.

Any advice on what I might be missing?

**Comment by manueltanzi-okta** [comment]
Hi @MarcusChamberlain,

Thank you for posting your question!

In that situation, do you get a console error saying `error.errorCode: login_required, error.description: The client specified not to prompt, but the user is not logged in`?

If that's the case, this is probably similar to https://github.com/okta/okta-oidc-js/issues/282

**Comment by jmelberg-okta** [comment]
Hey @MarcusChamberlain!

We pushed a fix for the likely cause of this. Please checkout [`@okta/okta-angular@1.0.4`](https://github.com/okta/okta-oidc-js/releases/tag/%40okta%2Foidc-angular%401.0.4) to see if this resolves the redirect issue.

If not, please feel free to reopen this issue.
