### ISSUE TITLE
Upgrade to support Angular 6.1

### ISSUE THREAD

**Issue by tcoz** [okta/okta-oidc-js#249]
I get the following when running ng update --all

Any news on when this might be compatible?

Package "@okta/okta-angular" has an incompatible peer dependency to "@angular/router" (requires ">=5.0.0-rc.0 <6.0.0||>=4.0.0 <5.0.0", would install "6.1.0").
                  Package "@okta/okta-angular" has an incompatible peer dependency to "@angular/common" (requires ">=5.0.0-rc.0 <6.0.0||>=4.0.0 <5.0.0", would install "6.1.0").
                  Package "@okta/okta-angular" has an incompatible peer dependency to "@angular/core" (requires ">=5.0.0-rc.0 <6.0.0||>=4.0.0 <5.0.0", would install "6.1.0").
                  Package "@okta/okta-angular" has an incompatible peer dependency to "@angular/platform-browser" (requires ">=5.0.0-rc.0 <6.0.0||>=4.0.0 <5.0.0", would install "6.1.0").

**Comment by robertjd** [comment]
Hi @tcoz , we're working on this right now and should have this merged shortly, please follow #243 , thanks!

**Comment by tcoz** [comment]
Figured I'd mention this as well: it looks like @schematics/angular, the latest version (0.7.1) install schematics differently. When I ran an update on a repo, and it updated schematics, the nrwl schematics no longer worked, because it was looking for schematics that no longer existed, for instance, the router schematics were no longer in @schematics/angular/utility (which is where your schematics are looking for them).

**Comment by tcoz** [comment]
(That other comment was in wrong place).

Thanks, look forward to the merge.

**Comment by robertjd** [comment]
Hi @tcoz, we just released version 1.0.2 of this library which allows Angular 6 in the peer dependencies.  Can you give it a try for us?  Thanks!
