### ISSUE TITLE
Poor handling of authenticated users that are not authorized to access the app

### ISSUE THREAD

**Issue by xscottx** [okta/okta-oidc-js#265]
When an Okta access denied error comes in for /implicit/callback, the Implicit.js class does not support taking in a prop to render a different UI component for errors.  Suggest enhancing this capability for more flexibility on what Okta errors look like on the react application.

**Comment by rodoabad** [comment]
@xscottx are you also getting the same error as I do? https://github.com/okta/okta-oidc-js/issues/266

**Comment by xscottx** [comment]
We've seen that before when using a different oauth client id as well, but the behavior we want is the same: to be able to customize the error UI component based on the error type/description.

**Comment by jmelberg-okta** [comment]
Hi @xscottx and @rodoabad! Thanks for the report.

This is something we're actively working on improving, as errors are difficult to react to. Right now, we're investigating what this looks like from our shared library [`okta-auth-js`](https://github.com/okta/okta-auth-js/), and afterwards will be exposing a clean event interface via our integration libraries.

Essentially, we're thinking of something similar to:

```javascript
auth.on('error', (data, context) => {
  if (data.error) {
    console.log(data.error);
    // invalid_scope

    console.log(data.error_description);
    // The requested scope is invalid, unknown, or malformed
  }
});
```

Once we have a clear definition of what this looks like, I'll link to those issues from this one.

Thanks for your patience!

**Comment by rodoabad** [comment]
@jmelberg-okta where are we at on this?

**Comment by jmelberg-okta** [comment]
Hey @rodoabad - We're still deep in the planning process with exposing an event interface, but for the above issue you should be able to work around this by using your own [`ImplicitCallback`](https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/src/ImplicitCallback.js) handler.

Errors are [returned](https://developer.okta.com/docs/api/resources/oidc#response-example-error) and can be parsed via the hash fragment, so you should be able to add some conditional logic before calling [`this.props.auth.handleAuthentication()`](https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/src/ImplicitCallback.js#L28).

**Comment by rodoabad** [comment]
@jmelberg-okta I created a separate thread to not derail this current issue, would you mind looking at that issue instead? https://github.com/okta/okta-oidc-js/issues/321

**Comment by stef-iula** [comment]
Hi! any progress on this?

**Comment by SushanRajShakya** [comment]
I am facing the same issue. 

**Library : ** @okta-angular

**Issue :** Infinite loop during access denied user trying to access the application by ImplicitCallBack Component in angular

**Expected Result :** Redirect the user to the login page or take the user to OKTA access denied page

**Steps to recreate :** 
1. Login to okta directly.
2. Open an application listed by okta with the user who is not given access to the OKTA authenticated application
3. Getting stuck in an infinite loop of Implicit Callback Component with access denied being passed as response but not being handled properly.

Best Regards

**Comment by swiftone** [comment]
Internal Ref: OKTA-269846

**Comment by swiftone** [comment]
@SushanRajShakya et al - While we investigate the issue, as a workaround you should be able to add any custom logic if you copy the ImplicitCallbackComponent to your own component and add your own extended handling.

**Comment by DavidLozzi** [comment]
I just made a workaround for this issue, check it out and let me know!

https://davidlozzi.com/2020/02/28/implementing-a-custom-okta-authentication-error-page-in-reactjs/

**Comment by swiftone** [comment]
Thanks for the write-up @DavidLozzi!  That's the intention of `ImplicitCallback` (now `LoginCallback` with okta-react 2.x) - Enabling you to write the components you need without having to build your own handling of the Okta state.  

We still need better handling/identification of users that are authenticated but lack authorization for the specific app, so I'm keeping this ticket open, but narrowing the focus.  If anyone feels this new focus doesn't match the problem, please open a new issue with details and reference this one.

**Comment by aarongranick-okta** [comment]
I have tested this in current versions of both `okta-angular` and `okta-react`. In this case, the following error will be displayed on the callback page:

```
OAuthError: User is not assigned to the client application.
```

To customize this behavior we recommend copying the `LoginCallback` component to your own source tree where it can be modified.

**Comment by TaylorNoelJordan** [comment]
@aarongranick-okta can you elaborate on what you mean by this?
`To customize this behavior we recommend copying the LoginCallback component to your own source tree where it can be modified.`

**Comment by aarongranick-okta** [comment]
@TaylorNoelJordan The source for the callback component is here: https://github.com/okta/okta-oidc-js/blob/master/packages/okta-angular/src/okta/components/callback.component.ts  You can copy this file and place it in our own source tree. Then following these instructions: https://github.com/okta/okta-oidc-js/tree/master/packages/okta-angular#oktacallbackcomponent  import and use the component from your source tree instead of the one exported by okta-angular. You may modify the component to show more information or add user interactions. Keep in mind that the call to `handleAuthentication` cannot be repeated - it will read the code from the URL and then remove the code from the URL. If a user refreshes the page on the callback route, and this function is called again, this will likely produce an error since the code cannot be read.

**Comment by Tomtomgo** [comment]
Is this supposed to work for v4+?
