### ISSUE TITLE
Token is renewed every time when calling getAccessToken()/getIdToken()

### ISSUE THREAD

**Issue by stormit-vn** [okta/okta-oidc-js#268]
I just upgraded to latest okta-angular version (1.0.3) and noticed that every time we call getAccessToken() or getIdToken(), Okta will attempt to renew the token by calling this API oauth2/default/v1/authorize. 

As the note, it should return token in the local storage without refresh new token. It worked in the previous version we've used 1.0.1. 

Dependencies:
* https://github.com/okta/okta-signin-widget 2.11.0
* Latest angular version 6.1.4

**Comment by robertjd** [comment]
Hi @stormit-vn , this is a problem we had with `@okta/okta-auth-js@2.0.0`, which we've fixed in `@okta/okta-auth-js@2.0.1`.  Can you look at your package tree and see which version of `@okta/okta-auth-js` is installed?  Thanks!

**Comment by jmelberg-okta** [comment]
Resolved with [#152](https://github.com/okta/okta-auth-js/pull/152)

**Comment by stormit-vn** [comment]
@robertjd Yes, install latest okta-auth-js fixed our problem. But we had to increase our token lifetime greater than 5 mins. There is no such as a option to change DEFAULT_MAX_CLOCK_SKEW variable, it always has default value to 300 which is 5 mins
