### ISSUE TITLE
Can't extend Angular OktaAuthService

### ISSUE THREAD

**Issue by seangwright** [okta/okta-oidc-js#270]
Hello,

I am requesting the ability to subclass `OktaAuthService` without having to jump through hoops.

I'm working with `"@okta/okta-angular": "1.0.2",` and I was trying to wrap the `OktaAuthService` so that I can expose less of directly to my map and also change some of the implementation process by intercepting requests.

One scenario I have is when I call `authService.handleAuthentication()` the tokens are pulled out of the url and then routing happens immediately.

I would prefer to get the tokens stored in the auth service and then make a request to my api with the tokens to get additional information about the user before redirecting them into the application.

If I was able to extend `OktaAuthService` I could perform the token parsing and delay the navigation until my Http request to my api returned.

Example:
```typescript
async parseTokens(): Promise<void> {
  const tokens = await this.oktaAuth.token.parseFromUrl();
  tokens.forEach(token => {
    if (token.idToken) {
      this.oktaAuth.tokenManager.add('idToken', token);
    }
    if (token.accessToken) {
      this.oktaAuth.tokenManager.add('accessToken', token);
    }
  });
  if (await this.isAuthenticated()) {
    this.emitAuthenticationState(true);
  }
}
```

All of the properties of `OktaAuthService` are private and the injection token for `OktaConfig` is not exposed directly by the module so constructing my own implementation is difficult.

I'd be happy to make a PR to make the properties `protected` and expose the `OktaConfig` DI token.

I'd then provide my implementation instead of the Okta one in my `AppModule`.

Thoughts?

Thanks!

**Comment by cmckni3** [comment]
The `InjectionToken` for the config is exposed as `OKTA_CONFIG`.

**Comment by seangwright** [comment]
Yes, but the _type_ of `OKTA_CONFIG` is not exposed by the module.

I don't consider using this import
`import { OktaConfig } from '@okta/okta-angular/dist/okta/models/okta.config';`
to be a good solution, which is what I'm doing now.

**Comment by cmckni3** [comment]
I agree but `OktaConfig` is not the actual DI token.
