### ISSUE TITLE
Okta login errors after redirect

### ISSUE THREAD

**Issue by felixhammerl** [okta/okta-oidc-js#271]
Hi folks,

I am using the Okta hosted login via Authorization Code Grant Flow in a small express service, which leads to the following request flow:

* Visit http://localhost:8080
* Get 301'd to https://localhost:8443 by a middleware
* Okta OIDC middleware redirects to hosted login page
* Login is performed, redirected to `https://localhost:8443/authorization-code/callback?code=[some code]&state=[some state]`

**Expected result**: Okta Middleware picks up the request, creates the respective cookies and forwards to the page I previously intended to go to, i.e. `/`

**Actual result**: Error is created and caught by a later error middleware. The funky thing is that if I go back to `/` manually, everything works as expected and all the cookies are set accordingly. Error Stack:
```
Error: did not find expected authorization request details in session, req.session[\"oidc:https://dev-204768.oktapreview.com/oauth2/default\"] is undefined
    at OpenIDConnectStrategy.authenticate (PATH/node_modules/openid-client/lib/passport_strategy.js:117:18)
    at attempt (PATH/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate (PATH/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at Layer.handle [as handle_request] (PATH/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (PATH/node_modules/express/lib/router/index.js:317:13)
    at PATH/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (PATH/node_modules/express/lib/router/index.js:335:12)
    at next (PATH/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (PATH/node_modules/passport/lib/middleware/authenticate.js:325:9)
    at SessionStrategy.authenticate (PATH/node_modules/passport/lib/strategies/session.js:71:10)
    at attempt (PATH/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate (PATH/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at Layer.handle [as handle_request] (PATH/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (PATH/node_modules/express/lib/router/index.js:317:13)
    at PATH/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (PATH/node_modules/express/lib/router/index.js:335:12)
```

**Versions**

* node: 10.9.0
* @okta/oidc-middleware: 0.1.3.tgz
* express-session: 1.15.6
* express: 4.16.3

**Comment by manueltanzi-okta** [comment]
Hi @felixhammerl , thank you for you question!

Few questions:
- Just to clarify, after authentication, do you want to redirect to the original http://localhost:8080/, or do you want to redirect to https://localhost:8443/?
- What is the value of `redirect_uri` in your code passed to `ExpressOIDC` object?
- What are the values of `Login redirect URIs` and `Initiate login URI` that you assigned when you setup the web application in the Okta Developer Console?

Thank you!

**Comment by felixhammerl** [comment]
* I want to redirect to `https://localhost:8443` and path should be whatever i had before, typically `/`.
* `redirect_uri` is `https://localhost:8443/authorization-code/callback`
* Here's the okta config:

![screen shot 2018-09-06 at 15 42 17](https://user-images.githubusercontent.com/1818340/45161172-85802980-b1eb-11e8-8a48-d4152bcee06e.png)

Here's my config:
```
{
  issuer: `https://${oktaHost}/oauth2/default`,
  client_id: oktaClientId,
  client_secret: oktaClientSecret,
  redirect_uri: `${protocol}://${domain}:${port}/authorization-code/callback`,
  scope: 'openid profile'
}
```

**Comment by manueltanzi-okta** [comment]
Hi @felixhammerl,

Thank you for providing me your configuration!

I tried to recreate your scenario using these, however, I was not able to reproduce your error.

So I created a branch based on our Express & Okta-Hosted Login sample that uses your configuration (except for the 301, i.e. starting directly from https://localhost:8443): https://github.com/okta/samples-nodejs-express-4/tree/mt-sample-issue-271/okta-hosted-login

Can you try to pull this branch, place values in .samples.config.json, and test if it works for you? If it does, can you compare with the small express service that you are trying to build and see what is different?

Thank you!

**Comment by felixhammerl** [comment]
Wrongfully assumed it was the library's error, but recently found out that it was actually the completely unrelated `samesite` property of `express-session` that caused the mistake. Thanks for the help anyway!

**Comment by varatep** [comment]
> Wrongfully assumed it was the library's error, but recently found out that it was actually the completely unrelated `samesite` property of `express-session` that caused the mistake. Thanks for the help anyway!

What did you set the `cookies.sameSite` property to for the fix?

**Comment by MrXploder** [comment]
> Wrongfully assumed it was the library's error, but recently found out that it was actually the completely unrelated `samesite` property of `express-session` that caused the mistake. Thanks for the help anyway!

I have the same issue, but I failed to reproduce every time. Can you point out the configuration you have?

**Comment by felixhammerl** [comment]
@MrXploder try removing the samesite attribute and build from there. i've got other csrf measures in place, so `samesite` was not high on my list of priorities.

**Comment by afalahi** [comment]
@felixhammerl I'm actually running into the same issue, this time I'm just trying to pick up an existing Okta session and if true redirect the user to the authorize uri. I don't have samesite in my session config, but hitting the same error you posted when I hit the callback url

**Comment by AliHaghani** [comment]
@afalahi Were you able to figure out the cause of this issue?

**Comment by shengc5** [comment]
Anyone has a theory/solution for this?

**Comment by AliHaghani** [comment]
The root cause of this issue for me was the use of multiple server instances with no session sharing between them and no sticky sessions support (which would always route the requests for a particular user session to the same server instance).

Example: test.com (instance A) would redirect the user to Okta for authentication, then Okta would redirect the user back to test.com/redirect (instance B) which has no session context from instance A.

If you have the same root cause, leveraging either session sharing or sticky sessions will resolve this issue.

**Comment by afalahi** [comment]
@shengc5 are you doing any sort of manual session detection? The OIDC middle expects a post request with the session token and the csrf token it generates. My issue what I wasn’t posting, and simply attempting to hit authorize endpoint and then redirect, which was causing my error to happen. When I try to authenticate directly it works fine. @AliHaghani not sure if this helps you as well

**Comment by johncrisostomo** [comment]
I am experiencing this issue both with this library and with `flask-oidc`, not really sure what is going on but is probably what @alihaghani explained. It works well on the dev Okta, but doesn't work on our corporate Okta instance.

**Comment by dnikomon** [comment]
I had some issue but in my case the mistake was that I was running `passport.session() `in middleware.ts and `passport.use(STRATEGY)` in different module.

The issue was resolved when I returned passport from the module where I set strategy to my middleware module and initialized that passport.
```

const passport = await setStrategy()
router.use(passport.initialize())
router.use(passport.session())
```

So the my passport.use(STRATEGY) didn't know anything about my session because it was initialized before strategy was set.

**Comment by mariohmol** [comment]
I´m having this issue and it is intermittent. Most of the time it works, but once in a while my users receives that.

1. its a single server, so there is no many servers that could be having some kind of session issue
2. It happens with and without express-session
3. I read all the tips here and nothing could solve..


any ideas?
