### ISSUE TITLE
jwt-verifier: library configuration checks

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-oidc-js#276]
To help avoid misconfiguration, this library should implement these checks against common errors: https://oktawiki.atlassian.net/wiki/spaces/PM/pages/552049922/Library+configuration+checks

For this library, these checks apply:

- [ ] Issuer
- [ ] Client ID

Additionally, make sure these placeholders are always used in documentation or samples:

- [ ] `https://{yourOktaDomain}` (not `{yourOktaDomain}.com`)
- [ ] `{clientId}`
- [ ] `{clientSecret}`

**Comment by jmelberg-okta** [comment]
This change is now public with `@okta/jwt-verifier@0.0.13`
