### ISSUE TITLE
oidc-middleware: library configuration checks

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-oidc-js#277]
To help avoid misconfiguration, this library should implement these checks against common errors: https://oktawiki.atlassian.net/wiki/spaces/PM/pages/552049922/Library+configuration+checks

For this library, these checks apply:

- [x] Issuer
- [x] Client ID
- [x] Client secret

Additionally, make sure these placeholders are always used in documentation or samples:

- [x] `https://{yourOktaDomain}` (not `{yourOktaDomain}.com`)
- [x] `{clientId}`
- [x] `{clientSecret}`

**Comment by jmelberg-okta** [comment]
Resolved with #286
