### ISSUE TITLE
Allow to specify the type of storage for tokens

### ISSUE THREAD

**Issue by manueltanzi-okta** [okta/okta-oidc-js#285]
Currently okta-auth-js offers the [option to specify the type of storage for tokens](https://github.com/okta/okta-auth-js#the-tokenmanager), however this option is not exposed to the SDKs, so it is always defaulted to localStorage.

We should probably allow the developers to use that option also when using okta-oidc-js SDKs.

CC: @robertdamphousse-okta @nbarbettini

**Comment by nbarbettini** [comment]
These PRs are related:

https://github.com/okta/okta-oidc-js/pull/173
https://github.com/okta/okta-oidc-js/pull/252

**Comment by manueltanzi-okta** [comment]
Also: 

https://github.com/okta/okta-oidc-js/pull/95

**Comment by RacingTadpole** [comment]
Another great advantage to this would be to allow the app to set `autoRenew: false`.

**Comment by manueltanzi-okta** [comment]
@Racing @mablack @seangwright @RacingTadpole 

We just released:
- @okta/okta-angular v1.1.0
- @okta/okta-react v1.2.0
- @okta/okta-vue v1.1.0

Which add the possibility to configure TokenManager parameters, check it out!
