### ISSUE TITLE
CORS error during callback

### ISSUE THREAD

**Issue by langfordG** [okta/okta-oidc-js#299]
Hello, I'm trying to authenticate users with the React web SDK, and seeing this error during the callback:

"Failed to load https://<my_issuer>/oauth2/<my_qa_auth_server_id>/.well-known/openid-configuration: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://<my_domain>.<my_company>.com' is therefore not allowed access."

Interestingly, everything works fine from localhost, but when I try from a different domain I get this error. Do apps need to be whitelisted for the sdk to work?

Thanks!

**Comment by rodoabad** [comment]
@langfordG based from my experience, yes. You need to whitelist it.

**Comment by langfordG** [comment]
@rodoabad Thanks for the response. Do you recall how to do so or if there's documentation? I don't have direct access to my org's okta account but with some instructions can submit a request. Much appreciated!

**Comment by langfordG** [comment]
@rodoabad Awesome that helps. Thanks again!
