### ISSUE TITLE
Unable to compile okta-react dependencies when using Webpack/Babel with Create-React-App

### ISSUE THREAD

**Issue by tbutman** [okta/okta-oidc-js#30]
I'm looking for a way to use okta with my React app which was generated using Create-React-App, however, I'm running into trouble when adding these modules as they use async functions which are an ES2017 feature. By default, Webpack only transpiles my app code into ES5 using the babel loaders and plugins, however, it does not transpile external dependencies due to performance considerations. As a result, I am running into errors when it imports these modules. I believe this will be an issue for anyone using Create-React-App to bootstrap a new project, unless they eject and configure webpack to compile all dependencies as well (which is inadvisable as it drastically slows down webpack compilation times). I was able to correct the issue by transpiling the dependencies manually, but it seems like it would be much easier for consumers if these libraries were hosted in the more widely supported ES5 syntax. This seems like the standard for most other libraries. Do you know if this is a possibility or do you know of any workarounds for Create-React-App users?

**Comment by robertdamphousse-okta** [comment]
Hi @tbutman , thanks for the feedback!  If that's the default for webpack then I agree that we should be transpiring our distribution for convenience.  I'll bring this to the team.

In the meantime, it seems like you could also use conditional module loaders, and single out this library?  I'm looking at this webpack documentation (I haven't tired this yet myself): https://webpack.github.io/docs/configuration.html#module-loaders

**Comment by jeroenransijn** [comment]
The error I keep getting is from the `async` syntax. For example in the `Auth.js` component  in the `dist` folder I see this:

```
value: async function handleAuthentication() {
```

I think the problem is in the [build step](https://github.com/okta/okta-oidc-js/blob/d7f4d9b769dee83058a6e7489673b5bf17e78354/packages/okta-react/package.json#L7) of the package (`@okta/okta-react`).

I am not sure, but shouldn't there either be a `.babelrc` in the root, or a preset in the command?

```
"build": "rimraf dist/ && NODE_ENV=development babel src -d dist --presets=es2015,react"
```

**Comment by jeroenransijn** [comment]
Seems like the babel preset is the problem. It should probably use `babel-present-env`:

```
npm i -S babel-preset-env
```

```
{
  "presets": ["env", "react"],
  "plugins": ["transform-object-rest-spread", "transform-class-properties"],
  "env": {
    "development": {
      "plugins": ["babel-plugin-dynamic-import-node"]
    }
  }
}
```
Not sure if the plugins are still necessary.

If I run `npm run build` I am seeing the following:

```
_createClass(Auth, [{
    key: 'handleAuthentication',
    value: function () {
      var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee() {
        var tokens, _iteratorNormalCompletion, _didIteratorError, _iteratorError, _iterator, _step, token;
```

Which I think is what we want here in the distribution.

**Comment by terensu-desu** [comment]
@tbutman What did you do to transpile the dependencies manually without ejecting the CRA? Right now I'm seeing Auth.js:54 causing the compile error (I assume there's more?). Maybe a fix is on the horizon but I'd like to push on if I can and do whatever you did to get this going.

**Comment by stephe** [comment]
I see PR #51 seems to have resolved this issue. Any plans to update the NPM module? I would like to just update my config rather than pulling master or monkey patching.

**Comment by robertjd** [comment]
HI @stephe since the last comment we've released new versions, can you please try?  Thanks!

**Comment by stephe** [comment]
@robertjd Yes picked up the new version and works well for us. We went live in Beta with our app this week. Thanks for resolving the issue.

**Comment by robertjd** [comment]
No prob, that's great to hear - I hope the beta is going well!
