### ISSUE TITLE
okta-angular: How to pass in env variables for OktaAuthModule.initAuth() ?

### ISSUE THREAD

**Issue by timc986** [okta/okta-oidc-js#308]
I have read this post but still cant make it work.
https://github.com/okta/okta-oidc-js/issues/39

Long story short, in the app.module, how can we pass in the config for OktaAuthModule.initAuth(config) from a json file?

![image](https://user-images.githubusercontent.com/32720097/45809520-41e3f000-bcc0-11e8-8253-cd719005f64f.png)

**Comment by timc986** [comment]
Ok so I end up using the following approach instead of the initAuth. A little bit more code work to do but at least it works.

https://developer.okta.com/code/angular/okta_angular_auth_js

**Comment by seangwright** [comment]
@timc986 

I provide [APP_INITIALIZER](https://hackernoon.com/hook-into-angular-initialization-process-add41a6b7e) to get my `.json` config from the server.

I then store that in my `AppSettingsService` (via `PreInitService`) before Angular starts up.

```
{
   provide: APP_INITIALIZER,
   useFactory: preInitServiceFactory,
   deps: [PreInitService, Injector],
   multi: true,
}
```

I then use another factory provider to inject the data stored in `AppSettingsService` via the `OKTA_CONFIG` injection token. See below

```
import { FactoryProvider } from '@angular/core';
import { Router } from '@angular/router';

import { OKTA_CONFIG, OktaAuthService } from '@okta/okta-angular';

import { AppSettingsService } from '@app/shared/infrastructure/app-settings.service';

export function onAuthRequired(_oktaAuth: OktaAuthService, router: Router) {
  router.navigate(['/login']);
}

export function oktaConfigFactory(appSettingsService: AppSettingsService) {
  const config = appSettingsService.getSettings();

  const oktaConfig = {
    ...config.oktaConfiguration,
    onAuthRequired,
  };

  return oktaConfig;
}

export const OktaConfigProvider: FactoryProvider = {
  provide: OKTA_CONFIG,
  useFactory: oktaConfigFactory,
  deps: [AppSettingsService],
};
```

My `CoreModule` then registers both the `APP_INITIALIZER` and `OKTA_CONFIG` injection tokens.

**Comment by jakehockey10** [comment]
@seangwright Did you have to do anything to account for the `OKTA_CONFIG` resolving before the `APP_INITIALIZER` was done initializing your `AppSettingsService`?  I can't seem to find a way to make sure that the `APP_INITIALIZER` resolves its Promise before the `OKTA_CONFIG` token is provided for.

**Comment by seangwright** [comment]
@jakehockey10 `APP_INITIALIZER` returns a promise, which you can delay resolving until you have successfully stored your Okta configuration in a service like `AppSettingsService`.

Which version of Angular are you using?

I don't have any providers in my `AppModule` class. I use `providedIn: 'root'` for all of my providers.

I don't use the `OktaAuthModule` and instead register all of the module's providers and declarations explicitly.

My `CoreModule`'s providers looks like this

```
providers: [
    PreInitService,
    {
      provide: APP_INITIALIZER,
      useFactory: preInitServiceFactory,
      deps: [PreInitService, Injector],
      multi: true,
    },
    {
      provide: OKTA_CONFIG,
      useFactory: oktaConfigFactory,
      deps: [AppSettingsService],
    },
    OktaAuthService,
  ],
```

I can push a demo repo showing all the pieces and parts sometime this week.

**Comment by OlgaDan25** [comment]
@seangwright Could you please push a demo repo showing how you managed to get okta config from json file? I tried to follow the steps above but got confused by  PreInitService vs AppSettingsService. Thank you.

**Comment by seangwright** [comment]
@OlgaDan25 Here ya go https://stackblitz.com/edit/angular-okta-configuration-via-http-request

A few caveats with this approach:

- All Okta components, services, ect... need to be declared and provided manually since you aren't using the module
- Pre-init services (using `APP_INITIALIZER`) prevent Angular from bootstrapping until they resolve so you probably want to keep the requests fast and small
- `const http = new HttpClient(this.httpBackend);` means the pre-init request runs outside of all interceptors, so you won't be able to decorate requests / responses like you normally do when your app loads - but this can also be a good thing and can prevent issues with circular/not ready dependencies (using interceptors to add jwt headers).

**Comment by OlgaDan25** [comment]
@seangwright Thank you so much!!!!! Your demo really helped a lot and I finally managed to use okta config from json file at runtime! Yay! :-) Thank you!

**Comment by aarongranick-okta** [comment]
For anyone finding this issue, `initAuth` is deprecated and will be removed soon. To dynamically build config you can to do something like:

```
  providers: [{
    provide: OKTA_CONFIG,
    useFactory: () => {
       //  load JSON, build and return config
    }
  }
/// ... other providers
],
```

**Comment by allthingsclowd** [comment]
> For anyone finding this issue, `initAuth` is deprecated and will be removed soon. To dynamically build config you can to do something like:
> 
> ```
>   providers: [{
>     provide: OKTA_CONFIG,
>     useFactory: () => {
>        //  load JSON, build and return config
>     }
>   },
>   // ... other providers
>   ],
> ```

Hey @aarongranick-okta,

Thank you for the pointer.

I'm hitting the issue that you mentioned

```ERROR in src/app/app.module.ts:29:20 - error TS2339: Property 'initAuth' does not exist on type 'typeof OktaAuthModule'.```

Is there any chance of providing a complete example similar to what's on the okta website https://developer.okta.com/blog/2019/02/12/secure-angular-login but with the new approach?

Many thanks

**Comment by aarongranick-okta** [comment]
@allthingsclowd We have complete samples [available here](https://github.com/okta/samples-js-angular). The config is provided in the [app module](https://github.com/okta/samples-js-angular/blob/master/okta-hosted-login/src/app/app.module.ts)

**Comment by allthingsclowd** [comment]
Thank you so much, sorry I missed this.

**Comment by swiftone** [comment]
Closing this issue as initAuth() is now replaced.  See the samples and README for details on the modern usage.
