### ISSUE TITLE
Infinite Loop on OAuthError: User is not assigned to the client application.

### ISSUE THREAD

**Issue by rodoabad** [okta/okta-oidc-js#321]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Infinite loop
## Minimal reproduction of the problem with instructions
1. Okta React + Implicit. - Root `/` must be secure. Every route must be secure.
2. Add a user to the "system" but do not add the user to the "application"
3. Login using the unauthorized user
4. Infinite loop

Infinite loop when you login.
![screencap](https://user-images.githubusercontent.com/1240667/46426470-52568a80-c704-11e8-8d49-0c2a08476861.gif)

**Comment by rodoabad** [comment]
@jmelberg-okta either I'm missing something here, but even if you have a custom handler for the callback, you cannot direct back to ANY URL since they are all "Secure" as far as...

```jsx
<SecureRoute path='/' />
```

is concerned. You will still get an infinite loop.

```jsx
<Security>
  <SecureHome/> // -> /
  <SecureOther/> // -> /other
  <ImplicitCallbackRoute/> -> /callback
</Security>

**Comment by HashirHussain** [comment]
I'm also facing the same issue,

@jmelberg-okta , @rodoabad any updates on this thread ?

**Comment by yj29** [comment]
@HashirHussain @jmelberg-okta @rodoabad any update on this thread?? I am also facing the same issue. 😞

**Comment by jameschapmanumusic** [comment]
I got around this issue by creating a new ImplicitCallback component which adds a couple of new lines to the Okta one. See this [Gist](https://gist.github.com/jameschapmanumusic/78877a9d3bba44402851436ad9d1352f). I've added comments against the changes you need to make

**Comment by swiftone** [comment]
@jameschapmanumusic - Thanks for sharing!  That is the current recommended way of customizing/expanding error handling in okta-react.  ( https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#implicitcallback )

Closing this issue with that recommendation.  If anyone continues to have an issue that isn't handled by that practice, please feel free to open a new issue with details and reference this one.

**Comment by Tomtomgo** [comment]
Same issue here on v4.5.1. Is this going to be fixed in `okta-react`?

**Comment by shuowu** [comment]
@Tomtomgo Do you mean auth-js v4.5.1? 
Also, okta-react has been moved to https://github.com/okta/okta-react, can you create a new issue with repo details there?
