### ISSUE TITLE
@okta/okta-vue 1.0.5 missing dist folder

### ISSUE THREAD

**Issue by bvangennep** [okta/okta-oidc-js#330]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [x] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
Version 1.0.5 of the @okta/okta-vue is missing a dist folder. This causes an error when trying to import the package with `import Auth from '@okta/okta-vue'`. Main in the package.json does refer to a dist/okta-vue.js file.

## Expected behavior
Dist folder to be there and imports to succeed.

## Minimal reproduction of the problem with instructions

1. Checkout https://github.com/okta?q=samples-js
2. Go to custom-login folder
3. Run `npm update && npm install`
4. Run `npm start`
5. See the error: 
```
 ERROR  Failed to compile with 1 errors                                                                                                                                                             

This dependency was not found:
* @okta/okta-vue in ./src/router/index.js

To install it, you can run: npm install --save @okta/okta-vue
```

## Environment

- Package Version: 1.0.5
- Browser: none
- OS: osx high sierra
- Node version (`node -v`): 8.11.3
- Other:

**Comment by jmelberg-okta** [comment]
Thanks for the report @bvangennep - I'm investigating this now. I'll follow up shortly.

**Comment by jmelberg-okta** [comment]
Thanks again for your patience @bvangennep. I've identified that the issue is related to our internal CI failing to trigger npm prepublish when npm publish was called.

`@okta/okta-vue@1.0.6` is now public and contains the bugfix.
