### ISSUE TITLE
[Okta React] Version `1.1.3` has syntax error in IE11

### ISSUE THREAD

**Issue by rodoabad** [okta/okta-oidc-js#333]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [X] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Syntax error in IE11.

## Expected behavior

No syntax error.

## Minimal reproduction of the problem with instructions

Use version `1.1.3`

## Environment

- Package Version: 1.1.3
- Browser: IE11
- OS: Windows
- Node version (`node -v`): 10.x

**Comment by rodoabad** [comment]
Any updates on this guys?

**Comment by jmelberg-okta** [comment]
@rodoabad - Thanks for the report!

I've identified the problem and working on publishing a new version now.

**Comment by rodoabad** [comment]
@jmelberg-okta you the man, Jordan. 💯

**Comment by jmelberg-okta** [comment]
@rodoabad - `@okta/okta-react@1.1.4` has been published and contains a fix to support IE11. Thank you again for the report!

**Comment by rodoabad** [comment]
Cool beans! @jmelberg-okta 👍 :shipit:
