### ISSUE TITLE
Update okta-react changelog

### ISSUE THREAD

**Issue by RacingTadpole** [okta/okta-oidc-js#341]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [ ] Feature request
- [x] Other (Describe below)

## Current behavior
https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/CHANGELOG.md only shows changes to 1.1.2

## Expected behavior
https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/CHANGELOG.md shows changes to 1.1.4.

## Minimal reproduction of the problem with instructions
Visit https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/CHANGELOG.md .

## Extra information about the use case/user story you are trying to implement
The current latest version on [npm](https://www.npmjs.com/package/@okta/okta-react) is 1.1.4.
It would be a great help when deciding whether to update a deployment, to know what the changes between 1.1.2 and 1.1.4 are. 

## Environment

N/A

**Comment by jmelberg-okta** [comment]
Thanks for the report @RacingTadpole!

This has been resolved via #342.
