### ISSUE TITLE
Cannot pass `tokenManager` option to okta-auth-js

### ISSUE THREAD

**Issue by RacingTadpole** [okta/okta-oidc-js#344]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [x] Feature request
- [ ] Other (Describe below)

## Current behavior

Okta-react always uses `localStorage` to store the returned jwt token, if possible. However concerns have been raised about this practice, eg. [here](https://auth0.com/docs/security/store-tokens).
It seems that [okta-auth-js](https://github.com/okta/okta-auth-js#the-tokenmanager) lets you configure this behavior, but okta-react does not expose this functionality.

## Expected behavior

Allow the jwt token to be stored in `sessionStorage` or a cookie.
One way to achieve this could be to allow a `token_manager` (or `tokenManager`) prop on the `Security` component:
```
          <Security
            issuer={oidc.issuer}
            client_id={oidc.clientId}
            redirect_uri={oidc.redirectUri}
            scope={oidc.scope}
            token_manager={{storage: 'sessionStorage'}}
          >
```

## Extra information about the use case/user story you are trying to implement

I think this can be easily implemented by a one-line change to the constructor in `Auth.js`:
```
    this._oktaAuth = new OktaAuth({
      url: config.issuer.split('/oauth2/')[0],
      clientId: config.client_id,
      issuer: config.issuer,
      redirectUri: config.redirect_uri
      tokenManager: config.token_manager
    });
```
However, I have not tested this.

## Environment

NA

**Comment by jmelberg-okta** [comment]
Hi @RacingTadpole -

This is already reported in #285. Please leave a 👍 on that issue to indicate this is something you're wanting as well.

Closing this issue as a duplicate.
