### ISSUE TITLE
Okta-react token verification

### ISSUE THREAD

**Issue by amandaluniz** [okta/okta-oidc-js#349]
## I'm submitting this issue for the package(s):

- [X] jwt-verifier
- [X] okta-react

## I'm submitting a:

- [X] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
A user is logged in to the application and the access token is saved in the localstorage. When the user logs out directly on the Okta tenant URL (not through the application) and the token is invalidated in the server, the **isAuthenticated** function provided by the **okta-react** library returns true.

## Expected behavior
A user is logged in to the application and the access token is saved in the localstorage. When the user logs out directly on the Okta tenant URL (not through the application) and the token is invalidated in the server, the **isAuthenticated** function provided by the **okta-react** library should return false as the user was logged out.

## Minimal reproduction of the problem with instructions
Create a react application using Okta's react library. Log in to the application which will call the /implicit/callback and will populate the localstorage with the token and user information.

Navigate to the tenants Okta page, and log out.

Come back to the application page and reload. The access token is still valid.

## Environment

- Package Version: 1.1.3
- Browser: Chrome 70.0.3538.77
- OS: MacOS Mojave 10.14
- Node version (`node -v`): 8.12.0
- Other:

**Comment by arrghh1** [comment]
I had similar issues last week. I believe however, that this is intended operation. The jwt-verifier according to the docs checks that:

- Signature is valid (the token was signed by a private key which has a corresponding public key in the JWKS response from the authorization server).
- Access token is not expired (requires local system time to be in sync with Okta, checks the exp claim of the access token).

It does not check against the Auth server to see if the session has been closed, or the user has been suspended (or similar). As a workaround to achieve this I wrote a custom authentication routing around the '/introspect' endpoint as per this document: https://developer.okta.com/authentication-guide/tokens/validating-access-tokens

**Comment by jmelberg-okta** [comment]
@amandaluniz & @arrghh1,

Thanks for the report + comment! As noted above, this is expected behavior of [offline JWT validation](https://developer.okta.com/authentication-guide/tokens/validating-access-tokens).

As an alternative, you can use the [`/introspection`](https://developer.okta.com/docs/api/resources/oidc#introspect) endpoint to determine if the token is invalid, expired, or revoked.
