### ISSUE TITLE
Add an HttpInterceptor to auto-add an Authorization header

### ISSUE THREAD

**Issue by mraible** [okta/okta-oidc-js#35]
This can be useful when using `HttpClient` in Angular 4.3+:

```ts
import { Injectable } from '@angular/core';
import {
  HttpRequest,
  HttpHandler,
  HttpEvent,
  HttpInterceptor
} from '@angular/common/http';
import { Observable } from 'rxjs/Observable';
import { OktaAuthService } from '@okta/okta-angular';

@Injectable()
export class AuthInterceptor implements HttpInterceptor {

  constructor(private oktaAuth: OktaAuthService) {
  }

  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {

    if (request.url.indexOf('localhost') > -1) {
      request = request.clone({
        setHeaders: {
          Authorization: `Bearer ${this.oktaAuth.getAccessToken().accessToken}`
        }
      });
    }

    return next.handle(request);
  }
}

```

Of course, this should be improved to allow whitelisting of URLs and check if the user is authenticated first. The whitelisting is necessary because I've found some APIs will fail (e.g., Giphy) if there's an `Authorization` header.

It'll also need to registered as a module in a provider.

```ts
  providers: [{
    provide: HTTP_INTERCEPTORS,
    useClass: AuthInterceptor,
    multi: true
  }],
```

**Comment by cmckni3** [comment]
I have similar code in my applications but I haven't found a good way to skip them. Sometimes I need to make a request which does not have authorization or has a different authorization token.

**Comment by yarx1988** [comment]
anybody solve this problem?? please give me a decision

**Comment by cmckni3** [comment]
Discussion at https://github.com/okta/okta-oidc-js/pull/229 @yarx1988

**Comment by swiftone** [comment]
Closing as out-of-scope, as our front end SDKs are built around the AuthJS library.  If there is a general use-case that would benefit from this feature in this SDK, feel free to open a new issue with details and reference this one.

**Comment by mraible** [comment]
If you use [OktaDev Schematics](https://github.com/oktadeveloper/schematics), it installs an `HttpInterceptor` that has this functionality. See [`auth.interceptor.ts`](https://github.com/oktadeveloper/schematics/blob/master/src/add-auth/angular/src/app/shared/okta/auth.interceptor.ts).
