### ISSUE TITLE
Okta Vue SDK should include TypeScript types

### ISSUE THREAD

**Issue by mraible** [okta/okta-oidc-js#352]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [x] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

I'm unable to use this library in a Vue + TypeScript project. Using [@types/okta__okta-vue](https://npm.taobao.org/package/@types/okta__okta-vue), I can redirect to Okta and login, but I can’t the callback to work. 

You can see my project [on GitHub](https://github.com/oktadeveloper/spring-boot-vue-example/blob/okta). [`main.ts`](https://github.com/oktadeveloper/spring-boot-vue-example/blob/okta/client/src/main.ts) is where everything is initialized. 

Not sure what I’m doing wrong since there’s no errors. Here's my [`router.ts`](https://github.com/oktadeveloper/spring-boot-vue-example/blob/okta/client/src/router.ts).

I created an [issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30933) to get `@types/okta__okta-vue` updated for the latest release. It'd probably be better if the types were included in this project.

## Expected behavior

I expect it to be easy to use the Okta Vue SDK in a TypeScript project. I'm able to use the Angular and React SDKs with TypeScript quite easily.

## Minimal reproduction of the problem with instructions

```
git clone -b okta git@github.com:oktadeveloper/spring-boot-vue-example.git
```

Follow the project's README to set it up for your Okta instance, or ping me and I'll give you credentials for mine.

## Extra information about the use case/user story you are trying to implement

Developers 💙 TypeScript, and I do too.

## Environment

- Package Version: 1.0.7
- Browser: Chrome
- OS: macOS Mojave
- Node version (`node -v`): v11.1.0
- Other:

**Comment by mraible** [comment]
I was able to work around this issue by creating my own `ImplicitCallback.vue` class:

```html
<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class ImplicitCallback extends Vue {

  private async created() {
    await this.$auth.handleAuthentication();
    this.$router.replace({
      path: this.$auth.getFromUri(),
    });
  }

  private render() {
    // empty
  }
}
</script>
```

Now I'm trying to figure out how to propogate the `authenticated` status between components. But that's not related to this issue. ;)

**Comment by mraible** [comment]
After a bit more investigating, it turns out I didn't need to create my own `ImplicitCallback`. I was able to use the following in my `router.ts` and make it work.

```ts
import OktaVuePlugin from '@okta/okta-vue';
...

{ path: '/implicit/callback', component: OktaVuePlugin.handleCallback() }
```

See my [`router.ts`](https://github.com/oktadeveloper/spring-boot-vue-example/blob/okta/client/src/router.ts) for its final form. 

In light of this development, I'm going to change this issue's title to say we should include TypeScript types rather than having them provided by a third-party.

**Comment by cybercussion** [comment]
I found https://npm.taobao.org/package/@types/okta__okta-vue, giving that a shot now.

**Comment by mraible** [comment]
@cybercussion That should work. I used it in my [Bootiful Development with Spring Boot and Vue](https://developer.okta.com/blog/2018/12/03/bootiful-spring-boot-java-vue-typescript) blog post.

**Comment by cybercussion** [comment]
It worked!  Thanks.

**Comment by robertjd** [comment]
Hi everyone, thank you for your thoughts.  We've discussed this and have decided that Typescript should get some first-party support from us, so we will start working it into our roadmap.  Continue to watch this issue for updates.  Thanks!

**Comment by ilgiznurgaliev** [comment]
Hi Everyone.
Any updates on this? **[okta__okta-vue](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/okta__okta-vue)** seems outdated and type definitions there no longer match functions and components in latest version of **[okta-vue](https://github.com/okta/okta-vue)**. **handleCallback** is no replaced by **LoginCallback** and it is missing in types.
Getting the following error:
`Uncaught TypeError: _okta_okta_vue__WEBPACK_IMPORTED_MODULE_2__.default.handleCallback is not a function`

**Comment by swiftone** [comment]
Okta-provided TypeScript for okta-vue is a WIP, see https://github.com/okta/okta-vue/pull/39

**Comment by ilgiznurgaliev** [comment]
thank you @swiftone, looking forward it to be merged

**Comment by mraible** [comment]
TypeScript support was added to Okta Vue in Okta Vue v3.0. https://github.com/oktadeveloper/schematics/releases/tag/v3.2.0
