### ISSUE TITLE
okta-react session expiration does not log user out

### ISSUE THREAD

**Issue by evbots** [okta/okta-oidc-js#357]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
If a user's Okta session expires, the user is not logged out of an app using `okta-react`. Instead, users will be able to navigate to `SecureRoute` components, which is not ideal since their session has expired. Additionally, the method `props.auth.isAuthenticated()` returns `true` and `props.auth.getAccessToken()` returns `undefined`. This is a problem because I would prefer for application routing to rely on `SecureRoute` instead of the return value of `getAccessToken`.

## Expected behavior

When a user's Okta session expires, I would expect that SecureRoute would block access to a protected component, and redirect based on the logic defined in `onAuthRequired`. Additionally, I would expect `isAuthenticated` to return `undefined`, not `true` as it currently does.

## Minimal reproduction of the problem with instructions
Set your token expiration to 5 minutes, and your session expiration to 6 minutes. Log into a react app using the sign-in widget and okta-react, wait past the 6 minute mark, and navigate to a protected component. At this point, the method `props.auth.isAuthenticated()` returns `true` and `props.auth.getAccessToken()` returns `undefined`.

## Extra information about the use case/user story you are trying to implement
I want a user to be technically "logged out" of an app using okta-react if a okta session expires.

## Environment

- Package Version: 1.1.4
- Browser: Chrome
- OS: MacOS 10.14.1
- Node version (`node -v`): 8.11.1
- Other:

**Comment by jmelberg-okta** [comment]
Hi @evbots -

This is intended behavior, as the `SecureRoute` checks for the existence of an `accessToken` or `idToken` to determine whether or not the user is in an "authenticated" state. These libraries are built on OAuth 2.0 and OpenID Connect APIs, which use token-based authentication instead of session-based.

> Additionally, the method props.auth.isAuthenticated() returns true and props.auth.getAccessToken() returns undefined. This is a problem because I would prefer for application routing to rely on SecureRoute instead of the return value of getAccessToken.

Most likely, the library is returning `true` here  because the `idToken` is still valid. As long as the `idToken` minted for the user hasn't expired, the user should be treated as "authenticated".

If you're wanting to use only an `accessToken` for your application, you can [pass in an updated `response_type`](https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/README.md#security). This will satisfy your expected behavior above.

Hope this helps clarify some things!

**Comment by evbots** [comment]
@jmelberg-okta Ok, thanks. My intent with tweaking the session timeout from the default (which i believe was 7 days) to 6 minutes was to set a limit on the amount of time that a user could get remain authenticated with new access_tokens (via silent refresh). If the way I am doing it is not possible, what would you recommend? preventing silent refresh w/ a longer access_token timeout value?

**Comment by evbots** [comment]
@jmelberg-okta I want to be able to silently refresh access tokens up to a limit that I set, something like 6 hours. Then I want the app to boot the user off of SecureRoutes and make them log in again. Does that make sense? Not sure if this flow is possible with this library.

**Comment by anjalichawlaa** [comment]
> @jmelberg-okta I want to be able to silently refresh access tokens up to a limit that I set, something like 6 hours. Then I want the app to boot the user off of SecureRoutes and make them log in again. Does that make sense? Not sure if this flow is possible with this library.

@evbots  were u able to achieve the same, i'm facing the same issue.
