### ISSUE TITLE
OKTA-angular redirect on errors

### ISSUE THREAD

**Issue by jbarber2016** [okta/okta-oidc-js#358]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [x] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [x] Feature request
- [ ] Other (Describe below)

## Current behavior

Forgive me if something like this has been submitted, but it's important
I would like to redirect when OAuthErrors shows up.  For example, if the user isn't assigned, I would like to have users redirected to a route I specify.  Currently, the flow stops at the implicit/callback, and that's not desired.  Here's an example of the error:

OAuthError: User is not assigned to the client application

## Environment

- Package Version: 1.0.7
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by levimdmiller** [comment]
I ran into this as well, and ended up just making my own callback component.

`  
ngOnInit() {
    this.okta.handleAuthentication()
      .catch(e => {
        console.log(e);
        this.okta.logout('/error');
      });
  }
`

**Comment by swiftone** [comment]
@levimdmiller - That is the correct response, thanks for sharing!

**Comment by albertchen-okta** [comment]
added to DevEx backlog here: https://oktainc.atlassian.net/browse/OKTA-244580
