### ISSUE TITLE
will it work for angular7? anyone tried?

### ISSUE THREAD

**Issue by vinay0458** [okta/okta-oidc-js#361]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [x] Feature request
- [ ] Other (Describe below)

## Environment

- Package Version:
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by peavers** [comment]
Seems fine for me on 7.1.4.

**Comment by manueltanzi-okta** [comment]
Hi @vinay0458 , do you have any problem running it on Angular 7?

**Comment by petemcwilliams** [comment]
Seems to be working fine with angular 7.2.0 and "@ionic/angular": "4.0.0-rc.1"

Perhaps we could update the peer dependencies:
```
npm WARN @okta/okta-angular@1.0.7 requires a peer of @angular/common@>=4 <7 but none is installed. You must install peer dependencies yourself.
npm WARN @okta/okta-angular@1.0.7 requires a peer of @angular/core@>=4 <7 but none is installed. You must install peer dependencies yourself.
npm WARN @okta/okta-angular@1.0.7 requires a peer of @angular/platform-browser@>=4 <7 but none is installed. You must install peer dependencies yourself.
npm WARN @okta/okta-angular@1.0.7 requires a peer of @angular/router@>=4 <7 but none is installed. You must install peer dependencies yourself.
```

**Comment by seangwright** [comment]
Yes it works fine with Angular 7. The Okta peer dependencies list is not correct which produces the warning on package installation.

**Comment by seangwright** [comment]
Maybe the package will be updated to use Angular 7 by the time Angular 8 is released...

**Comment by manueltanzi-okta** [comment]
Hi @seangwright, sorry for the delay, we are looking into updating our peer dependencies.

Will keep you guys updated!

**Comment by manueltanzi-okta** [comment]
@vinay0458 @peavers @petemcwilliams @seangwright Good News!

We have a PR open for this: https://github.com/okta/okta-oidc-js/pull/419

**Comment by manueltanzi-okta** [comment]
Good News! https://github.com/okta/okta-oidc-js/pull/419 has been merged!

Closing this issue.

**Comment by jakehockey10** [comment]
so is 8 happening, then?

**Comment by mraible** [comment]
@jakehockey10 It works just fine with Angular 8. See [Angular 8 + Spring Boot 2.2: Build a CRUD App Today!](https://developer.okta.com/blog/2019/05/13/angular-8-spring-boot-2).

**Comment by jakehockey10** [comment]
Yay! Just looked into it and saw the lack of an upper constraint! Yay!
