### ISSUE TITLE
JwtVerifier -- Why assert clientId?

### ISSUE THREAD

**Issue by chadjaros** [okta/okta-oidc-js#367]
## I'm submitting this issue for the package(s):

- [x] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [ ] Feature request
- [x] Question

## Current behavior

In version 0.13 clientId was added as a required field. 

## Expected behavior

Requiring clientID seems unnecessary. Why was this added as a requirement, rather than being handled similarly to audience where this claim is validated only if the argument is supplied?

Please note: Audience is technically required to be validated by the JWT spec if present in the token.

## Minimal reproduction of the problem with instructions

Create instance of JwtVerifier without supplying clientId property

## Extra information about the use case/user story you are trying to implement

Our servers have historically validated tokens from any client id. This provides us with a lot of flexibility as far as managing token behavior between multiple services.
```
[ UX 1 (Okta Application) ]   [ UX 2 (Okta Application)]
                         \         /
                           [Server]
```
## Environment

- Package Version: 0.14
- Node version (`node -v`): 8

**Comment by swiftone** [comment]
Excellent point!  While clientId is required to validate an id token, it should not be required to validate an access token.  We are looking at the necessary changes involved, and will update this issue as progress is made.  In the meantime, it may be possible to use multiple instances of the verifier to resolve any conflicts you are encountering.

**Comment by chadjaros** [comment]
In the mean time, we have migrated away from this library.
