### ISSUE TITLE
okta-react dist files contain async function

### ISSUE THREAD

**Issue by jjrdev** [okta/okta-oidc-js#37]
Why do the compiled files contain async functions? renders them unusable on IE11

**Comment by jjrdev** [comment]
heres my workaround in webpack config
        rules: [{
            test: /\.js$/,
            loaders: ['babel-loader'],
            exclude: function(modulePath) {
                return /node_modules/.test(modulePath) &&
                    !/node_modules\/@okta/.test(modulePath);
            }
        }],

**Comment by jeroenransijn** [comment]
Possibly fixed by my PR #31. I don't know if Okta is looking at this repo at all. Pretty sad to be blocked by such a small issue.

**Comment by Sathish-kumar-Subramani** [comment]
Hi jeroenransijn,

I'm unable to build my react because of the async function in auth.js.
How did you get it work?

**Comment by Prophet32j** [comment]
This is also the reason why `npm build` fails for me.
```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/@okta/okta-react/dist/Auth.js:54 

Read more here: http://bit.ly/2tRViJ9
```
