### ISSUE TITLE
Breaking change in patch version from 1.0.2 to 1.0.3

### ISSUE THREAD

**Issue by mbergeronupgrade** [okta/okta-oidc-js#380]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

When updating okta-react from 1.0.2 to 1.0.3 (or latest 1.1.4) the okta-auth-js sub dependency is bumped by a major version which makes our authentication stop working. I used the react sample project to make sure it wasn't anything that was done in our application that was causing the problem.

I.e. version 1.0.3 -> 1.1.4 
![image](https://user-images.githubusercontent.com/29203843/51939245-ff07f680-23dc-11e9-9b05-012d79ed4046.png)

## Expected behavior

Updating a patch version should not introduce a breaking change.

version 1.0.2 result:
![image](https://user-images.githubusercontent.com/29203843/51939395-5b6b1600-23dd-11e9-9034-1209ed7a79f1.png)

## Minimal reproduction of the problem with instructions

Here is our application settings:

![image](https://user-images.githubusercontent.com/29203843/51939440-7473c700-23dd-11e9-8d0b-7c0658a69ec1.png)

Here is what is used in the okta-hosted-login sample app

![image](https://user-images.githubusercontent.com/29203843/51939609-eb10c480-23dd-11e9-8a89-1a9f60fb804c.png)

## Extra information about the use case/user story you are trying to implement

Trying to update to latest version to satisfy our security team's requests that dependencies are not stale.

## Environment

- Package Version: 1.0.3
- Browser: Tested in Chrome and Firefox
- OS: OSX Mojave
- Node version (`node -v`): 10
- Other:

**Comment by mbergeronupgrade** [comment]
@robertjd , issuer is `https://dev-214885.oktapreview.com` which has worked for the past year or so in dev mode. In prod its `https://credify.okta.com` but I cannot confirm wether that would show the same problem.

**Comment by DavidLozzi** [comment]
We're seeing something similar, upgrading from 1.0.2 to 1.1.4. It appears the request URL changed from `/oauth2/xxx/v1/userinfo` to `/oauth2/xxx/v1/keys`. The Authorize URL didn't change, but the second call this component makes changed endpoints. This is now causing authentication issues in browsers where a full cache reset is needed.

**Comment by DavidLozzi** [comment]
Our issue appears to be more closely related to https://github.com/okta/okta-signin-widget/issues/541, and doesn't appear to be a version issue

**Comment by swiftone** [comment]
Thanks for the update.  I'll close this issue and allow discussion to continue there.

**Comment by DavidLozzi** [comment]
I'm not sure if the issue I referenced is the same issue originally posted here.

**Comment by swiftone** [comment]
@mbergeronupgrade Can you confirm if your issue is distinct from https://github.com/okta/okta-signin-widget/issues/541 ?
