### ISSUE TITLE
[feat] Add type definitions to @okta/jwt-verifier

### ISSUE THREAD

**Issue by Toxicable** [okta/okta-oidc-js#393]
## I'm submitting this issue for the package(s):
- [x] jwt-verifier

## I'm submitting a:
- [x] Feature request

## Current behavior
There are no type definitions for this package

## Expected behavior
There to be type definitions for this package

## Minimal reproduction of the problem with instructions
N/A

## Extra information about the use case/user story you are trying to implement
N/A

## Environment
N/A

**Comment by elecompte60** [comment]
Please!
These are widely used libraries from a large technology company. There's no reason these libraries should not include proper Typescript type signatures.

**Comment by bretterer** [comment]
@Toxicable & @elecompte60  - Thanks for your enhancement request for type definitions. This is on our roadmap to investigate. I have no information on a date of release at this time, but keep an eye on this issue for updates.

**Comment by shellscape** [comment]
@bretterer how's that roadmap looking now? `okta-auth-js` got types in.

**Comment by swiftone** [comment]
TS support has moved from "something we are considering" to "something we are committed to doing".

`okta-auth-js`, `okta-react`, `okta-angular`, and `okta-vue` (PR under review) are converted to some real level of TS support.  The line before `jwt-verifier` is definitely shorter, but I don't have a specific timeline yet for `jwt-verifier` getting the conversion.

**Comment by swiftone** [comment]
Internal ref: OKTA-279270

**Comment by ryansonshine** [comment]
@swiftone are you open to accepting a PR from the community?

**Comment by ryansonshine** [comment]
@swiftone are you open to accepting a PR from the community on this one?

**Comment by swiftone** [comment]
@ryansonshine - Of course! I can't promise anything, of course, without first seeing the code, but we welcome and appreciate contributions.   Please make sure to sign our Contributor License Agreement (CLA) found here: https://developer.okta.com/cla/ 

Thanks for the interest!

**Comment by ryansonshine** [comment]
Type definitions being submitted to DefinitelyTyped in the interim: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51418

**Comment by swiftone** [comment]
Just touching on this PR as the team discussed it during sprint planning and are looking to get it attention.

**Comment by shellscape** [comment]
I was hesitant to post this, and it should not be misread as a denigration to those who give their time freely - It's a bit bananas that open source contributions are tied to corporate sprint planning within the owning company. Terrible way to run open source projects, doesn't reflect well on Okta's understanding of open source.
