### ISSUE TITLE
TypeError: Cannot read property 'getWithRedirect' of undefined

### ISSUE THREAD

**Issue by geethu-u** [okta/okta-oidc-js#396]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
-  okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

-  Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
After updrading to 1.2.0 from 1.1.4, I'm getting this error in console.
Uncaught (in promise) TypeError: Cannot read property 'getWithRedirect' of undefined
    at Auth._callee8$ (Auth.js?bca5:427)
    at tryCatch (runtime.js?4a57:62)
    at Generator.invoke [as _invoke] (runtime.js?4a57:296)
    at Generator.prototype.(:3000/anonymous function) [as next] (webpack-internal:///1435:114:21)
    at step (asyncToGenerator.js?7b11:17)
    at eval (asyncToGenerator.js?7b11:35)
    at new Promise (<anonymous>)
    at new F (_export.js?90cd:36)
    at Auth.eval (asyncToGenerator.js?7b11:14)
    at Auth.redirect (Auth.js?bca5:446)

this._oktaAuth.token is undefined

## Expected behavior

Authenticate should work as expected 

## Environment

- Package Version:1.2.0
- Browser:Chrome
- OS:Windows
- Node version (`node -v`):10.14.2
- Other:The login works well in 1.1.4

**Comment by geethu-u** [comment]
This happens in 1.1.4 and 1.2.0 of okta-react with okta-auth @2.3.1

**Comment by swiftone** [comment]
Thanks for the report @geethu-u - can you clarify the steps involved to trigger the error?  (Example: this happens when loading any page, or when loading a page that requires authentication, etc )

**Comment by Stetchy** [comment]
Getting the same error. It happens when calling the this.props.auth.login function for me/attempting to get to the login page with the widget.
Using React, with Typescript so I have been typing everything myself.

Stack trace:

`Uncaught (in promise) TypeError: Cannot read property 'getWithRedirect' of undefined
    at Auth._callee8$ (node_modules\@okta\okta-react\dist\Auth.js:427)
    at tryCatch (node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:62)
    at Generator.invoke [as _invoke] (node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:296)
    at Generator.prototype.(anonymous function) [as next] (ode_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (node_modules\babel-runtime\helpers\asyncToGenerator.js:17)
    at node_modules\babel-runtime\helpers\asyncToGenerator.js:35
    at new Promise (<anonymous>)
    at new F (node_modules\core-js\library\modules\_export.js:36)
    at Auth.<anonymous> (node_modules\babel-runtime\helpers\asyncToGenerator.js:14)
    at Auth.redirect (node_modules\@okta\okta-react\dist\Auth.js:446)`

The trace above resolves to `this._oktaAuth.token.getWithRedirect(...)`.

This occurs when I click a Button component which calls a 
`login = async () => {
    this.props.auth.login('/home');
}`

Where: auth is an interface like:

`
export interface Auth {
  login(redirectUri: string): {};
  logout(redirectUri: string): {};
  isAuthenticated(): boolean;
  getAccessToken(): string;
  redirect(sessionToken: any): any;
}
`

**Comment by aarongranick-okta** [comment]
@geethu-u Are you also using Typescript in your React project?

**Comment by geethu-u** [comment]
> @geethu-u Are you also using Typescript in your React project?

No, I'm using ES6

**Comment by geethu-u** [comment]
> Thanks for the report @geethu-u - can you clarify the steps involved to trigger the error? (Example: this happens when loading any page, or when loading a page that requires authentication, etc )

This happens on trying to load the app.

**Comment by aarongranick-okta** [comment]
@geethu-u Without seeing the code, my guess is that `this` within the `login()` function is not bound correctly. If you are able to debug and inspect the value of `this`, you may be able to confirm if this is the case.

If you are able to attach the source for your application, we can take a look at it and try to reproduce the issue on our side.

**Comment by richi1717** [comment]
Is this going to be addressed and fixed any time soon?

**Comment by aarongranick-okta** [comment]
@richi1717 See my earlier comment on function binding. If the method is being called from a button `click()` event it may not be bound to the component and therefore the value of `this` may not be what you expect. It is common to add event handlers as properties of your component: ```
this.onLogin = this.onLogin.bind(this)
```

See https://reactjs.org/docs/handling-events.html

**Comment by Stetchy** [comment]
I think you can also disregard my comment. I believe the issue I was having is specific to Electron and the way it's implemented, as there was no address for an location implicit callback to actually go to, hence it wasn't defined and neither was the "auth" prop. In the other cases I would assume it's `this` not being defined like you said.

**Comment by swiftone** [comment]
Closing as the issue has been answered - anyone finding this issue when searching, please check on the binding of `this` as mentioned above.

**Comment by cartbeforehorse** [comment]
> 
> 
> @richi1717 See my earlier comment on function binding. If the method is being called from a button `click()` event it may not be bound to the component and therefore the value of `this` may not be what you expect. It is common to bind and add event handlers as properties of your component:
> 
> ```
> this.onLoginClick = this.onLoginClick.bind(this)
> ```
> 
> See https://reactjs.org/docs/handling-events.html
> and https://developer.okta.com/docs/guides/sign-into-spa/react/add-signin-button/

I stumbled across this post as a Vue developer trying to work out why I was getting an error in the browser console:

```
[Vue warn]: Error in v-on handler (Promise/async): "TypeError: Cannot read property 'setFromUri' of null"
```
Developer documentation [here >>](https://developer.okta.com/blog/2018/01/31/build-secure-todo-app-vuejs-aspnetcore) suggests that a `v-on:click` authentication can be called directly from within the template.

```
      <template v-else>
        <button v-on:click='$auth.loginRedirect'>Log in</button>
      </template>
```
Your solution of passing the call into a `method` and then calling `this.$auth.loginRedirect();` from within the method worked (or at least allowed me to advanced into the next error).

Might I suggest the developer docs be updated?

**Comment by shuowu** [comment]
@cartbeforehorse As you noticed, the blog post you referred to is outdated. Please try guide/sample from https://developer.okta.com/code/vue/  instead.

**Comment by cartbeforehorse** [comment]
> @cartbeforehorse As you noticed, the blog post you referred to is outdated. Please try guide/sample from https://developer.okta.com/code/vue/ instead.

Thanks for the reply.  But that's the link I directed you towards with the bug in it.

**Comment by shuowu** [comment]
I see the link points to https://developer.okta.com/blog/2018/01/31/build-secure-todo-app-vuejs-aspnetcore, did I miss anything?

**Comment by cartbeforehorse** [comment]
Your link is to a directory of resources.
One of the resources in that directory is the to-do app:

![image](https://user-images.githubusercontent.com/3742356/94032311-be31d200-fdb7-11ea-9ead-7f9f222cc795.png)

**Comment by shuowu** [comment]
@cartbeforehorse Thanks for reporting the issue! We will get the guide fixed. Meanwhile, you can try sample [here](https://github.com/okta/samples-js-vue). This sample repo should be up to date.

Internal Ref: OKTA-331911
