### ISSUE TITLE
okta-react - React-Router Peer Dependency

### ISSUE THREAD

**Issue by ccjx** [okta/okta-oidc-js#401]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report 
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
When running `npm install` or equivalent, okta-react expects a react-router peer-dependency. 
```
[3/4] Linking dependencies...
warning " > @okta/okta-react@1.2.0" has unmet peer dependency "react-router@>=4".
```

## Expected behavior
However, as of react-router v4, the react-router package is the "core" package that is used by both react-router-native and react-router-dom. Since this project targets ReactJS, the correct peer-dependency should be react-router-dom.

## Minimal reproduction of the problem with instructions
- Add react-router-dom to a React project
- Add Okta-react to the same project
- `npm install`

## Environment

- Package Version: 1.2.0
- Browser: -
- OS: Windows 10
- Node version (`node -v`): v10.15.1
- Other: -

**Comment by Sheparzo** [comment]
The is affecting us. React Router 5 was published way back in March.  Please fix this.

**Comment by barbalex** [comment]
What is more: We use react but not react-router. As a matter of fact everyone using GatsbyJS uses reach-router instead of react-router. We use GatsbyJS so our app includes reach-router, even though it has integrated its routing in the store.

So please do not expect users to be using any other dependencies.

**Comment by swiftone** [comment]
@barbalex - Message received.  We're working on reducing/expanding our dependency options right now.  Thanks for the feedback!

**Comment by swiftone** [comment]
The `@okta/okta-react` 2.x still LISTS react-router as a peer dependency, as we continue to provide react-router-specific components, but can now be used with other packages.

Sadly, it seems there is no "optional peer dependency" from npm, despite multiple requests.
