### ISSUE TITLE
okta-react implicit dependencies (history, Router)

### ISSUE THREAD

**Issue by aarongranick-okta** [okta/okta-oidc-js#405]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [X ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [ ] Feature request
- [X ] Other (Describe below)

## Current behavior

The core 'Auth' object in this library has an undocumented / implicit dependency on 'history' which it (typically) receives (via the 'Security' component) from the Router component.

To use Auth outside of a component context (such as in actions / workers, or at any point before first render) it should be constructed outside of any component.  The internal dependency on 'history' makes this complicated. A history object must be created first for Auth, and this same object must be passed to Router in the component layer.

## Expected behavior

Auth could be passed generic callback functions for host app to provide needed functionality. ie, getCurrentLocation(). If Auth is being constructed by the Security component, the binding to history could be done there.

## Environment

- Package Version:
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by swiftone** [comment]
The reliance on `history` has been removed (by you :) ) in the 2.x series.

`react-router-dom` is now optional, for devs that are using react-router, but the 2.x series can be used with other routers.
