### ISSUE TITLE
publish  @okta/jwt-verifier to fix Out-of-bounds Read audit error with njwt

### ISSUE THREAD

**Issue by Toxicable** [okta/okta-oidc-js#417]
I'ts been fixed with https://github.com/okta/okta-oidc-js/commit/494c52e35449ecfda0a2386410b5af0178537051, just needs a deploy

**Comment by robertjamesmiller** [comment]
please fix this because it blocking all of our okta related integrations, thanks!

**Comment by swiftone** [comment]
@robertjamesmiller  Thanks for the poke.   Looking into this...

**Comment by stcleezy** [comment]
I believe this issue can be closed as part of @0.0.15
