### ISSUE TITLE
[okta-react] Resource not found (Session) error kills app with no redirect

### ISSUE THREAD

**Issue by dbryantm** [okta/okta-oidc-js#418]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
I'm using the @okta/okta-react package and sometimes we randomly have an error that will completely kill the app. Tried looking through existing issues with no success. I'm including the error below as I'm not entirely sure if the issue could just be in our setup:

```
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { BrowserRouter as Router } from 'react-router-dom';
import { Security } from '@okta/okta-react';
import store from './store';
import { okta } from './config';
import App from './components/App';
import * as serviceWorker from './serviceWorker';

ReactDOM.render(
  <Provider store={store}>
    <Router>
      <Security
        issuer={okta.issuerId}
        client_id={okta.clientId}
        redirect_uri={okta.redirectUrl}
        onAuthRequired={({ history }: any) => {
          history.push('/login');
        }}
      >
        <App />
      </Security>
    </Router>
  </Provider>,
  document.getElementById('root')
);
```
Also, here's the error that we're getting at random intervals that terminates the app:
```
Unhandled Rejection (AuthApiError): Not found: Resource not found: me (Session)./node_modules/@okta/okta-auth-js/lib/errors/AuthApiError.js
node_modules/@okta/okta-auth-js/lib/errors/AuthApiError.js:26
__webpack_require__
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:786
  783 | };
  784 | 
  785 | // Execute the module function
> 786 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^
  787 | 
  788 | // Flag the module as loaded
  789 | module.l = true;
View compiled
fn
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^
  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
./node_modules/@okta/okta-auth-js/lib/http.js
node_modules/@okta/okta-auth-js/lib/http.js:19
__webpack_require__
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:786
  783 | };
  784 | 
  785 | // Execute the module function
> 786 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^
  787 | 
  788 | // Flag the module as loaded
  789 | module.l = true;
View compiled
fn
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^
  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
./node_modules/@okta/okta-auth-js/lib/tx.js
node_modules/@okta/okta-auth-js/lib/tx.js:15
__webpack_require__
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:786
  783 | };
  784 | 
  785 | // Execute the module function
> 786 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^
  787 | 
  788 | // Flag the module as loaded
  789 | module.l = true;
View compiled
fn
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^
  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
./node_modules/@okta/okta-auth-js/lib/builderUtil.js
node_modules/@okta/okta-auth-js/lib/builderUtil.js:14
__webpack_require__
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:786
  783 | };
  784 | 
  785 | // Execute the module function
> 786 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^
  787 | 
  788 | // Flag the module as loaded
  789 | module.l = true;
View compiled
fn
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^
  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
./node_modules/@okta/okta-auth-js/lib/browser/browser.js
node_modules/@okta/okta-auth-js/lib/browser/browser.js:20
__webpack_require__
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:786
  783 | };
  784 | 
  785 | // Execute the module function
> 786 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^
  787 | 
  788 | // Flag the module as loaded
  789 | module.l = true;
View compiled
fn
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^
  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
./node_modules/@okta/okta-auth-js/reqwest/index.js
node_modules/@okta/okta-auth-js/reqwest/index.js:17
__webpack_require__
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:786
  783 | };
  784 | 
  785 | // Execute the module function
> 786 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^
  787 | 
  788 | // Flag the module as loaded
  789 | module.l = true;
View compiled
fn
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^
  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
./node_modules/@okta/okta-auth-js/lib/browser/browserIndex.js
node_modules/@okta/okta-auth-js/lib/browser/browserIndex.js:14
__webpack_require__
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:786
  783 | };
  784 | 
  785 | // Execute the module function
> 786 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^
  787 | 
  788 | // Flag the module as loaded
  789 | module.l = true;
View compiled
fn
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^
  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
./node_modules/@okta/okta-react/dist/Auth.js
node_modules/@okta/okta-react/dist/Auth.js:41
__webpack_require__
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:786
  783 | };
  784 | 
  785 | // Execute the module function
> 786 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^
  787 | 
  788 | // Flag the module as loaded
  789 | module.l = true;
View compiled
fn
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^
  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
./node_modules/@okta/okta-react/dist/Security.js
node_modules/@okta/okta-react/dist/Security.js:37
__webpack_require__
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:786
  783 | };
  784 | 
  785 | // Execute the module function
> 786 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^
  787 | 
  788 | // Flag the module as loaded
  789 | module.l = true;
View compiled
fn
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^
  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
./node_modules/@okta/okta-react/dist/index.js
node_modules/@okta/okta-react/dist/index.js:8
__webpack_require__
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:786
  783 | };
  784 | 
  785 | // Execute the module function
> 786 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^
  787 | 
  788 | // Flag the module as loaded
  789 | module.l = true;
View compiled
fn
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^
  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
Module../src/index.tsx
http://localhost:8000/static/js/main.chunk.js:1333:74
__webpack_require__
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:786
  783 | };
  784 | 
  785 | // Execute the module function
> 786 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^
  787 | 
  788 | // Flag the module as loaded
  789 | module.l = true;
View compiled
fn
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:149
  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^
  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {
View compiled
0
http://localhost:8000/static/js/main.chunk.js:3444:18
__webpack_require__
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:786
  783 | };
  784 | 
  785 | // Execute the module function
> 786 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^
  787 | 
  788 | // Flag the module as loaded
  789 | module.l = true;
View compiled
checkDeferredModules
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^
  46 | 	}
  47 | }
  48 | return result;
View compiled
Array.webpackJsonpCallback [as push]
/Users/dmoore/Development/ags/frontend/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^
  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
(anonymous function)
http://localhost:8000/static/js/main.chunk.js:1:57
```
Our only current resolution requires us to clear the local storage manually and any cache that we have which is not ideal.

## Expected behavior
When the session expires, it should redirect the app to the URL supplied to the `onAuthRequired` prop of the `<Security/>` component.

## Minimal reproduction of the problem with instructions
We use the login page example provided from https://github.com/okta/okta-signin-widget and https://developer.okta.com/code/react/okta_react_sign-in_widget/. Not sure what else would be needed to document the issue.

## Extra information about the use case/user story you are trying to implement
N/A

## Environment

- Package Version: @okta/okta-react@^1.2.0, @okta/okta-signin-widget@^2.18.0
- Browser: Chrome 73.0.3683.86
- OS: macOS 10.14.4
- Node version (`node -v`): 10.15.3
- Other: create-react-app with react@16.8.6, react-dom@16.8.6, and react-scripts@2.1.8

**Comment by swiftone** [comment]
Thanks for the report - to help in our diagnosis: Is your browser set to deny 3rd party cookies?  
( For your chrome: chrome://settings/content/cookies , the switch "Block third party cookies" )

If so, does changing that setting remove the problem?   (Asking for diagnosis, not as the recommended solution)

**Comment by dbryantm** [comment]
Hi @swiftone, 

I do not have that setting currently enabled.

<img width="683" alt="Chrome - Cookie Settings" src="https://user-images.githubusercontent.com/1263310/55419195-38c2be00-5542-11e9-8ca3-02380b913e7f.png">

**Comment by jakehova** [comment]
Can confirm this happens in Brave browser.   Had a user that could not log out.  When I walked them through their settings to enable 3rd party cookies, he was able to log out properly.

**Comment by sibelius** [comment]
is there any workaround for this?

**Comment by swiftone** [comment]
@sibelius - We are still reviewing our longer-term solution, but short term:

If you do NOT have 3rd party cookies blocked, this should be as simple as handling the rejected promise from `this.props.auth.logout()` in your JSX files (where this is will depend on your files).  Example: 

`this.props.auth.logout('/').catch( err => console.log(err) );`

You can customize how you wish to handle the situation: 

* You can have the callback passed to catch silently do nothing: `.catch( () => {} );`
* You can have the callback report a message to any internal logging they wish ( similar to above `console.log()` call).
* You can only accept the 404 and still throw other errors:
```
.catch( err => {
  // Silently ignore no such session errors
  if(err.errorCode !== "E0000007") { 
    throw err;
  } 
});
```

Now that this situation has been highlighted to us we’re reviewing our documentation, guides, and samples.

**Comment by stephan-mclean** [comment]
Hi @swiftone ,

Just checking if there are any updates on this issue? I have a similar problem in that I have users that can't logout using Firefox or Safari. We are using the React SDK v1.2.3. Adding the catch block above seems to slightly improve things, but it's inconsistent. Sometimes the logout works, and sometimes the user just gets redirected back to the application still logged in. 

I can open a separate issue for this if needed, but I figured I'd chime in here since this one is still open. 

Thanks for all the help.

**Comment by swiftone** [comment]
Hi @stephan-mclean - Hmm.  We've seen something similar, it appears to be related but not quite the same thing.  I'd suggest opening a separate issue so you can get focus on your specifics, and mention this there so we can pull in anything that is related.

Meanwhile, we can confirm your sanity (well, at least regarding this :) ) and we're looking at it, but your issues ( and the details, particularly any kind of consistent repro steps ) will help determine our priorities.

**Comment by stephan-mclean** [comment]
Thanks for your response, @swiftone , I'll open a new issue for this one.

**Comment by luisfarzati** [comment]
Can also report the same here. Handling the rejection doesn't solve the problem. Inspecting the network tab I can see the failed request:

```
DELETE https://dev-430802.okta.com/api/v1/sessions/me

404 Not Found

{
  "errorCauses": [],
  "errorCode": "E0000007",
  "errorId": "oaeoLbLloviQ3mzDN-xXC3BPg",
  "errorLink": "E0000007",
  "errorSummary": "Not found: Resource not found: me (Session)"
}
```

```bash
Unhandled Rejection (AuthApiError): Not found: Resource not found: me (Session)
(anonymous function)
/lib/errors/AuthApiError.js:26
  23 |     this.xhr = xhr;
  24 |   }
  25 | }
> 26 | AuthApiError.prototype = new Error();
  27 | 
  28 | module.exports = AuthApiError;
  29 | 

(anonymous function)
/lib/http.js:15
  12 |  */
  13 | 
  14 | /* eslint-disable complexity */
> 15 | var util = require('./util');
  16 | var Q = require('q');
  17 | var AuthApiError = require('./errors/AuthApiError');
  18 | var constants = require('./constants');

(anonymous function)
/lib/tx.js:15
  12 |  */
  13 | 
  14 | /* eslint-disable complexity, max-statements */
> 15 | var http              = require('./http');
  16 | var util              = require('./util');
  17 | var Q                 = require('q');
  18 | var AuthSdkError      = require('./errors/AuthSdkError');

(anonymous function)
/lib/builderUtil.js:13
  10 |  * See the License for the specific language governing permissions and limitations under the License.
  11 |  */
  12 | 
> 13 | var AuthSdkError = require('./errors/AuthSdkError');
  14 | var tx = require('./tx');
  15 | var util = require('./util');
  16 | 

(anonymous function)
/lib/browser/browser.js:19
  16 | 
  17 | require('../vendor/polyfills');
  18 | 
> 19 | var AuthSdkError      = require('../errors/AuthSdkError');
  20 | var builderUtil       = require('../builderUtil');
  21 | var constants         = require('../constants');
  22 | var cookies           = require('./browserStorage').storage;
```

**Comment by aarongranick-okta** [comment]
@luisfarzati Thank you for the detailed information. This is the expected error in this case. Our next release of `okta-react` (@1.3) will catch and ignore this error automatically.

**Comment by sovushka-utrom** [comment]
What if user does have the third party cookies disabled? What should we do in such case?
For the moment, I just catch the error and redirect user to login, seems like user is indeed logged out.   
I'm experiencing this with Angular, not React, but it's the same system & I'm not sure whether I have to submit an issue or it's a normal behaviour.

**Comment by swiftone** [comment]
@sovushka-utrom We've recently released updates for all our front end SDKs (including Angular) to support our redirect-based logout, which will work regardless of the settings for third party cookies.  You can read more about it here: https://github.com/okta/okta-auth-js#additional-options by setting postLogoutRedirectUri.

**Comment by swiftone** [comment]
To all users impacted by this issue - if your issue is related to the third-party cookie settings in the browser, you can avoid that problem by passing the `postLogoutRedirectUri` setting to your auth settings.  

You can see how to pass options below (note this is an extended option, so it's not yet explicitly listed in each front end SDK README, but is listed in the Auth README that these link to)

React: https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#configuration-options

Angular: https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#configuration-options

Vue: https://github.com/okta/okta-oidc-js/tree/master/packages/okta-vue#configuration

**Comment by sovushka-utrom** [comment]
@swiftone Well, I guess redirect-based logout is only available in v1.3.0, as Angular cdk v1.2.2 OktaConfig object doesn't have a `postLogoutRedirectUri` setting. So I'm waiting for https://github.com/okta/okta-oidc-js/issues/627 to be resolved.
By the way, the Angular link is pointing to React, should be: 
https://github.com/okta/okta-oidc-js/tree/master/packages/okta-angular#okta_config ;)

**Comment by swiftone** [comment]
@sovushka-utrom - Correct, 1.3.x in Angular for the redirect-based logout.  Thanks for the correction in the link!

**Comment by sovushka-utrom** [comment]
I confirm that it's fine now for my app after i added the `postLogoutRedirectUri `setting, no more need to manually catch the error.
`"@angular/core": "^9.0.0-rc.7"` & `"@okta/okta-angular": "~1.3.1"`.
Thank you!

**Comment by swiftone** [comment]
Because the new `postLogoutRedirectUri` option to redirect for logout should resolve this issue, I'm closing this.  If anyone is still experiencing this issue after making the change (see list below for docs) please open a new issue with details and reference this issue in the description.

React: /packages/okta-react@master#configuration-options 

Angular: /packages/okta-angular@master@master#okta_config 

Vue: /packages/okta-vue@master#configuration
