### ISSUE TITLE
Add canActivateChild to Angular Okta guard.

### ISSUE THREAD

**Issue by jraadt** [okta/okta-oidc-js#424]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [X] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [X] Feature request
- [ ] Other (Describe below)

## Current behavior

OktaAuthGuard only implements CanActivate. It would help if it also implemented CanActivateChild so we can use it to guard child routes as well.

## Expected behavior

Just need to add `CanActivateChild` to the `implements` and the following lines to the bottom of OktaAuthGuard:
```
async canActivateChild(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
  return this.canActivate(route, state);
}
```

## Minimal reproduction of the problem with instructions

Add this to a route and it blows up:
`canActivateChild: [OktaAuthGuard]`

## Environment

- Package Version: 1.2
- Browser: Chrome
- OS: Mac
- Node version (`node -v`): 10.12.0
- Other:

**Comment by krabouilleur** [comment]
Hi, 
Is there no canActivateChild again ?

**Comment by swiftone** [comment]
Internal ref: OKTA-283009

**Comment by jraadt** [comment]
The new OktaAuthGuard has canActivateChild. Thanks!
