### ISSUE TITLE
Provide hooks api

### ISSUE THREAD

**Issue by sibelius** [okta/okta-oidc-js#429]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [x] Feature request
- [ ] Other (Describe below)

## Current behavior

It does not have hooks api

## Expected behavior

It should provide hooks api

`useAuth` for instance

## Environment

- Package Version: 1.2.0
- Browser: chrome
- OS: mac
- Node version (`node -v`): 10.15.0
- Other:

**Comment by swiftone** [comment]
Thanks for the issues and the PR - we're reviewing the involved efforts (including the requirement change for our customers).

**Comment by swiftone** [comment]
`@okta/okta-react` 2.x now includes hooks support along with a number of improvements in the handling of async information.

**Comment by swiftone** [comment]
Thanks to @sibelius for the PR that got it all rolling.
