### ISSUE TITLE
Redirecting user from Okta back to application results in "AuthSdkError: Unable to parse a token from the url"

### ISSUE THREAD

**Issue by sudravi** [okta/okta-oidc-js#432]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

I'm using the Okta React sample code for hosted login (https://github.com/okta/samples-js-react/tree/master/okta-hosted-login). When I try password reset or signup activation, I'm not able to redirect from Okta to the sample app. Instead, I get an error saying "AuthSdkError: Unable to parse a token from the url".

## Expected behavior

I should redirect from Okta back to the sample app login page. If I switch to the custom-login sample code (https://github.com/okta/samples-js-react/tree/master/custom-login), where I install okta-signin-widget, everything works fine. So it seems like a limitation with the hosted login.

## Minimal reproduction of the problem with instructions

Run the sample code mentioned above, and try going through a password reset or signup activation, and you should see the error.

## Extra information about the use case/user story you are trying to implement

I'm trying to use Okta to sign in to my custom application.

## Environment

- Package Version: okta-react 1.2.0
- Browser: Chrome
- OS: MacOS
- Node version (`node -v`): 10.13.0
- Other:

**Comment by saichandesh** [comment]
The same error is happening in one of our application.

**Scenario**:

There are two applications, let's say App1, App2. App1 is non-okta app and App2 is okta app. App2 is implemented with okta implicit flow. It refresh the access token whenever it's expired. 

As long as the user uses App2, the implicit flow works fine but when the user has expired okta token in App2 and they navigate from App1 to App2. Then App2 routes `Implicit CallBack` component but the url doesn't have any token and then user has to refresh App2 to get the token.

It's so weird and been hard to debug it. Trying to see if someone can help with it.

**Comment by nharrisanalyst** [comment]
I am getting this same error also

when I click on my app inside the okta dashboard

**Comment by aarongranick-okta** [comment]
@saichandesh @nharrisanalyst In these cases (when a token is not returned), there is usually helpful information in the developer console. Be sure to select the option 'preserve log' since there is a redirect happening. Please let us know if this is able to resolve your issue. Thanks!

**Comment by lockykeaney** [comment]
Has there been any updates on this issue? I am getting the same thing, but even when preserving logs, my console has no errors or logs with any new information.

**Comment by swiftone** [comment]
@lockykeaney  - We cannot reproduce this error as a general issue.  I suggest you reach out to developers@okta.com to generate a support ticket so we can learn what is going on in your case.

**Comment by gjgd** [comment]
@lockykeaney What setting did you change? I have the same error in the same conditions with no error in the console

**Comment by azadbolour** [comment]
I have the same issue when a newly signed-up user clicks on the email activation link.

I have created a case for this with support: 

https://support.okta.com/help/s/case/5001Y00001MMaphQAD/email-activation-causes-authsdkerror

Please refer to that case for details. 

The advice from support is either 1. Explicitly create the user without having them go through the hosted signup process. That requires more work and complexity on our side and is less than optimal for us. Or 2. Find out from engineering if there is a way in our React application to check for the conditions leading to this issue, and avoid the issue. 

As per Dragos Gaftoneanu's suggestion, I am writing to ask engineering if they can advise on the latter solution. If so, a code sample and directions showing how to do that would be real helpful.

Many thanks.

Azad

**Comment by dragosgaftoneanu** [comment]
Hi @azadbolour 

As discussed on the support case, at the moment this use-case is not applicable for the SDK. The best solution for this use-case (user is redirected to Okta to authenticate -> registers a new account through self service registration -> activates his account -> he is redirected to /callback endpoint with authentication hints instead of tokens) is to implement a new route handler in the app which will become the default callback endpoint for the OIDC application and will either redirect to /authorize endpoint in case it receives the hints as query parameters or pass the tokens/authorization code to the SDK's callback endpoint and authenticate the user.

Dragos Gaftoneanu
Developer Support Engineer
Okta Global Customer Care
