### ISSUE TITLE
@okta/okta-angular does not work with Angular 8 when Ivy is enabled

### ISSUE THREAD

**Issue by mraible** [okta/okta-oidc-js#442]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [x] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

After adding Okta's Angular SDK to an Angular 8 project with Ivy enabled, an error happens on compilation:

```
ERROR in There is no format with import statements in '.../node_modules/@okta/okta-angular' entry-point.
```

According to https://github.com/angular/angular/issues/29564, it might be possible to fix it with https://github.com/ng-packagr/ng-packagr. 

## Expected behavior

No compilation errors.

## Minimal reproduction of the problem with instructions

Install Angular 8 CLI:

```
npm i -g @angular/cli@v8.0.0-rc.2
```

Create a new app:

```
ng new secure-app --routing --style css --enable-ivy
```

Add Okta for auth (values don't matter) since the app doesn't compile:

```
cd secure-app
ng add @oktadev/schematics --issuer=foo --clientId=bar
```

Run the app:

```
ng serve
```

You'll see the error.

As a workaround, you can modify `tsconfig.app.json` to disable Ivy.

```json
"angularCompilerOptions": {
  "enableIvy": false
}
```

**Comment by kschwidder** [comment]
with latest angular 9.x-next release it does not work too. 

getting


ERROR in Cannot resolve type entity ɵngcc1.OktaCallbackComponent to symbol
ℹ ｢wdm｣: Failed to compile.
    
    ERROR in node_modules/@okta/okta-angular/dist/okta/okta.module.d.ts(4,25): error TS2307: Cannot find module './callback.component'.
    node_modules/@okta/okta-angular/dist/okta/okta.module.d.ts(5,25): error TS2307: Cannot find module './login-redirect.component'.

**Comment by mraible** [comment]
I tried it with Angular CLI 9.0.0-rc.0 today and it works fine. 👍

```
> app@0.0.0 postinstall /Users/mraible/app
> ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points

⠹ Installing packages...Compiling @okta/okta-angular : main as commonjs
npm WARN @okta/okta-angular@1.2.2 requires a peer of @angular/common@>=4 but none is installed. You must install peer dependencies yourself.
npm WARN @okta/okta-angular@1.2.2 requires a peer of @angular/core@>=4 but none is installed. You must install peer dependencies yourself.
npm WARN @okta/okta-angular@1.2.2 requires a peer of @angular/platform-browser@>=4 but none is installed. You must install peer dependencies yourself.
npm WARN @okta/okta-angular@1.2.2 requires a peer of @angular/router@>=4 but none is installed. You must install peer dependencies yourself.

added 12 packages from 10 contributors and audited 21025 packages in 12.245s
found 0 vulnerabilities
```

**Comment by swiftone** [comment]
@mraible - I presume you want to wait for a full Angular 9 release before closing this issue - is there more you'd like?

**Comment by mraible** [comment]
I'll close it and open a new one if the Angular 9 GA release has issues.

**Comment by haovanvo** [comment]
@mraible can you fix it in Angular v8.x? I have tried the both ways: enabled/disabled ivy compiler but issue still happen.

**Comment by mraible** [comment]
@haovanvo I don't think it's possible. Ivy was beta in Angular 8 and [didn't have CommonJS/UMD support](https://github.com/angular/angular/issues/29564). They seem to have fixed this in Angular 9. You can turn off Ivy support in Angular 8 as a workaround.
