### ISSUE TITLE
@okta/jwt-verifier Cannot find module 'jsonwebtoken'

### ISSUE THREAD

**Issue by brvinodh** [okta/okta-oidc-js#448]
## I'm submitting this issue for the package(s):

- [x] jwt-verifier
## I'm submitting a:

- [x] Bug report  

Getting error on installing okta verifier and then running the node project

## Current behavior

Nodejs app stops immediately after running the program with the error: 
#### Error: Cannot find module 'jsonwebtoken'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

Error is at this module:  node_modules\jwks-rsa\lib\integrations\passport.js
## Expected behavior

Application should continue to run without aborting

## Minimal reproduction of the problem with instructions

create any nodejs app
`npm install --save @okta/jwt-verifier`

create a file: index.js add the below contents

`let lib = require('@okta/jwt-verifier')`

run the program
`node index.js`

## Environment

- Package Version: 0.0.14
- Browser: 
- OS:
- Node version (`node -v`): v10.15.3
- Other:

**Comment by redbmk** [comment]
I'm on the same version of Node and getting the same error. I also tried downgrading to an older package version (`0.0.12`) and it still wasn't working.

I then tried `npm i jsonwebtoken` to manually add it as a dependency, and now I get:
> Error: Cannot find module '@okta/jwt-verifier'

**Comment by redbmk** [comment]
I have used this in the past and took a look at the yarn.lock for another project, which was using jwks-rsa@1.2.1. Installing that exact version fixed the problem for me, so it sounds like a breaking change was introduced in `jwks-rsa` somewhere between 1.2.1 and 1.5.0.

**Comment by redbmk** [comment]
Also for more info see this issue - they're aware of it and it sounds like v1.4.0 should be OK: https://github.com/auth0/node-jwks-rsa/issues/90

**Comment by brvinodh** [comment]
@redbmk  Thanks for your findings. 
I was able to get the app working with  `npm i jsonwebtoken` 
Hoping a permanent fix comes from okta which does not break the jwt-verifier

**Comment by robertjd** [comment]
This problem should now be response if you update to the `0.0.15` version of @okta/jwt-verifier`.  In that version we have pinned to a version of `jwks-rsa` that doesn't have this problem.

**Comment by redbmk** [comment]
Perfect, thanks @robertjd. If this is working for you @brvinodh then I'd say this is safe to close now.

**Comment by brvinodh** [comment]
@robertjd and @redbmk Thank you for your support. It works now.
