### ISSUE TITLE
it is not asking user to re-authenticate

### ISSUE THREAD

**Issue by sibelius** [okta/okta-oidc-js#454]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [x] Feature request
- [ ] Other (Describe below)

## Current behavior

This is what is happening to me

- User logs into my application A
- redirect to Okta, and needs to enter email and password
- redirect back to application A
- User logout from my application A (I call auth.logout() here)
- User logs into my application A again
- redirect to Okta, does not need to enter email/password (I need the user to put the email and password again on Okta screen)
- redirect back to application A

## Expected behavior

- [ ] it should ask user to re-authenticate again on okta

## Minimal reproduction of the problem with instructions

We use `auth.login()` to login okta user on our platform

and we call `auth.logout()` to logout okta user on our platform

We use `auth.isAuthenticated()`, to check if the user is authenticated or not

If we don't call `logout()`, `isAuthenticated()` will keep return `true`
When we call `logout()`, ``isAuthenticated()` returns false

Then when I try to login againg using `auth.login()`, it will redirect to Okta login, but it will redirect back to us, without users having to input login and password again
 
## Extra information about the use case/user story you are trying to implement

related to this one https://github.com/okta/okta-oidc-js/issues/397#issuecomment-493525977

## Environment

- Package Version: 1.2.0
- Browser: Chrome
- OS: mac
- Node version (`node -v`): 10
- Other:

**Comment by swiftone** [comment]
Thanks for opening this as a separate issue.

Per our original discussion, your expectations are correct, the behavior you are reporting is not, and I'm unable to replicate your scenario (in my tests I am prompted for a username/password on the Okta site before being redirected to my application.  

In Chrome DevTools, "Network", do you see a call to DELETE /sessions/me when you do a "logout"?  (given the redirects you should check the "Preserve Logs" box)

It should look something like this:

![Screen Shot 2019-05-17 at 3 18 27 PM](https://user-images.githubusercontent.com/492300/57959114-1fd65800-78b7-11e9-8c97-1f4765b19d4f.png)

**Comment by sibelius** [comment]
![image](https://user-images.githubusercontent.com/2005841/57959277-781e5180-78d9-11e9-8d90-35c227572fdb.png)

For some weird reason this call is being cancelled

**Comment by sibelius** [comment]
fixed

```
await auth.logout()
```

I await okta logout process finish, so I can finish my own logout process

tks for the help
