### ISSUE TITLE
Getting a SigningKeyNotFoundError trying to verify access token

### ISSUE THREAD

**Issue by tonywuhl** [okta/okta-oidc-js#46]
I am getting access tokens from `https://company.okta.com/oauth2/v1/authorize`, with something like:

`https://company.okta.com/oauth2/v1/authorize?client_id=<clientId>&redirect_uri=<callbackUrl>&response_type=id_token%20token&scope=openid&state=123&nonce=4`

However when I try to verify the `access_token` that comes back, I am getting `SigningKeyNotFoundError: Unable to find a signing key that matches ...`

I can't seem to figure out whats wrong. When I call the `/oauth2/v1/introspect` endpoint directly, the `access_token` comes back as being valid.

Here's my config for OktaJwtVerifier

```
const oktaJwtVerifier = new OktaJwtVerifier({
  issuer: Config.OKTA_ISSUER, // https://company.okta.com/oauth2
  clientId: Config.OKTA_CLIENT_ID,
  assertClaims: {}
});
```

**Comment by mraible** [comment]
This is likely because you're using your org's Authorization server rather than the default one (or a new one that you created).

**Comment by robertjd** [comment]
Hi @tonywuhl , at the moment you'll only be able to verify tokens that are issued by a custom authorization server.  In your example you're using the authorization server for the Org itself.

**Comment by tonywuhl** [comment]
@robertjd what is the reason that we can only verify tokens from a custom auth server? Is that simply a limitation of this module?

**Comment by lboyette-okta** [comment]
@tonywuhl Org access tokens are only intended to be used against the userinfo endpoint and in the future, other Okta api's. Okta is the only audience for these tokens, so your app shouldn't be trying to verify them even though it's possible via the introspection endpoint ([spec link for the aud claim](https://tools.ietf.org/html/rfc7519#section-4.1.3)). 

Here's an example of the claims in an org access token:
```
{
  "ver": 1,
  "jti": "AT.vmR-c-IE0418H_A_lNXnhQA6Aau1buXKeTO-SPA6Y0Y",
  "iss": "https://dev-222222.oktapreview.com",
  "aud": "https://dev-222222.oktapreview.com", <-- this should be your client_id
  "sub": "lboyette@okta.com",
  "iat": 1511911845,
  "exp": 1511915445,
  "cid": "0oacepm3kxoNH43Q10h7",
  "uid": "00ubqzxky19KUuI0L0h7",
  "scp": [
    "openid",
    "profile"
  ]
}
```

To create tokens that you can verify, you'll need a custom auth server. This isn't a limitation of the module; it's a limitation imposed by the spec.

**Comment by marcelschulze** [comment]
Thanks, got the same problem. I had to specify the issuer by myself in the OktaAuthClient eg.:
`issuer: 'https://your-org.okta.com/oauth2/default`
