### ISSUE TITLE
Logout issue with @okta/okta-react-native

### ISSUE THREAD

**Issue by RohanAmpra** [okta/okta-oidc-js#461]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

- Click on Login Button
- Call `await tokenClient.signInWithRedirect();` method to login
- App gets redirected to login screen with username and password text box
-  Enter correct username and password for User A and press login
- Gets Redirected back to app.
- Click logout from app and call `await tokenClient.signOut();` method
- Check if user logged out from `await tokenClient.isAuthenticated();` which return False.
- Call `await tokenClient.signInWithRedirect();` to Allow user B to enter his credentials
- App gets redirect to browser and comes back without asking for username and password.
- Still gives tokens for User A

## Expected behavior

- Call `await tokenClient.signInWithRedirect();` method to login
- App gets redirected to login screen with username and password text box
-  Enter correct username and password for User A and press login
- Gets Redirected back to app.
- Click logout from app and call `await tokenClient.signOut();` method
- Check if user logged out from `await tokenClient.isAuthenticated();` which return False.
- Call `await tokenClient.signInWithRedirect();` to Allow user B to enter his credentials
- App Should redirect user to enter new username and password.
- After login It should return tokens for new credentials of User B. 

## Environment

- Package Version: @okta/okta-react-native: "^0.1.2"
- Browser: 
- OS: iOS and android
- Node version (`node -v`): 12.1.0
- Other: "expo": "^32.0.0",
    "expo-cli": "^2.13.0"

**Comment by swiftone** [comment]
@RohanAmpra - Thanks for the feedback.  You're running into something that isn't a bug, per se, but a mismatch in expectations.  You can read more about it here: https://github.com/okta/okta-oidc-js/issues/397#issuecomment-493494960

We will be updated our SDKs to match the more common expectations, but until we do so, you can use the existing logout process to remove the user session local to your application AND redirect them to the appropriate logout url on the issuer site: https://developer.okta.com/docs/api/resources/oidc/#logout

**Comment by swiftone** [comment]
Closing as the issue appears to have been dealt with. (at least until documentation and related code is modified)
