### ISSUE TITLE
can I use the same application for both okta-react and okta-react-native?

### ISSUE THREAD

**Issue by sibelius** [okta/okta-oidc-js#470]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [ ] Feature request
- [x] Other (Describe below)

## Current behavior

I need 2 applications to make work on okta-react web and okta-react-native app

## Expected behavior

I'd like to need only one

## Environment

- Package Version:
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by swiftone** [comment]
The Auth handling will be different between them, but your components should be similar.  I suggest asking in our Forums ( https://devforum.okta.com/ ) to get more discussion.
