### ISSUE TITLE
[okta-vue] does not compile in nuxt.js at all

### ISSUE THREAD

**Issue by scottgale** [okta/okta-oidc-js#475]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [X] okta-vue

## I'm submitting a:

- [X] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Try compiling using nuxt, you get this response:

> nuxt --spa

 ERROR  window is not defined                                         

  ReferenceError: window is not defined
  at Object.<anonymous> (node_modules/@okta/okta-vue/dist/okta-vue.js:1)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)

## Expected behavior

Successful compile

## Minimal reproduction of the problem with instructions

Run nuxt with okta-vue installed in your packages.

## Extra information about the use case/user story you are trying to implement

Using okta login on a nuxt SPA app.

## Environment

- Package Version: 
- Browser: n/a (not a browser issue)
- OS: macOS Mojave 10.14.5
- Node version (`node -v`): v10.15.3
- Other:

**Comment by dalecarslaw** [comment]
Issue also present when trying to build Vuepress that makes use of okta-vue

**Comment by swiftone** [comment]
@scottgale and @dalecarslaw - Thanks for the comments.  I wanted to note that this issue isn't being ignored, it just hasn't risen in priority enough to be acted on yet.  I know how frustrating it can be to shout into an uncaring void, so I wanted to say the void cares, even if the void isn't acting yet.

**Comment by mraible** [comment]
@dalecarslaw We did publish a [blog post on how to add auth to VuePress](https://developer.okta.com/blog/2019/06/14/add-authentication-and-personalization-to-vuepress). Not sure if it helps, but I figured it's worth a shot.

**Comment by dalecarslaw** [comment]
@mraible this is the blog which I followed in the first place that brought me to okta. The issue is present even on the blogs demo code when trying to build.

**Comment by noelmace** [comment]
Looks like this package does not support SSR anymore (based on the tutorial @mraible talked about). IMO, you should at least add a warning to the README and the tutorial.

**Comment by swiftone** [comment]
Correct on all points @noelmace - we've added updating our documentation on this point to our backlog.

**Comment by noelmace** [comment]
Thx, @swiftone. Do you know if there is any plan to support SSR again any time soon?

**Comment by swiftone** [comment]
@noelmace - Unfortunately, SSR was only accidentally working, and SSR support is not currently on our backlog.

Feel free to open a request for that and garner some +1s for it - I'll make sure our PM is aware of any demand for such a feature.

**Comment by noelmace** [comment]
This issue already has 6 👍, making it the 4th most wanted one for this all monorepo before you closed it 🤷‍♂️

Even if it was accidental, i don't understand why you didn't keep it as a top priority after your documentation about vuepress integration got so popular.

**Comment by bmounteer** [comment]
Almost a year later, SSR support would be really great. We had to hack together a solution with Socialite on our laravel backend to get okta working.

**Comment by swiftone** [comment]
@bmounteer - I can't offer any specific deadline, but SSR support is a discussion that has come up more than once and I've certainly been paying attention to the popularity of the requests.  I'll raise it with the team for consideration for priorities.

**Comment by hamzanaveedmalik** [comment]
Wished it had been addressed. Blocked by this issue to implement Okta integration.

**Comment by bmounteer** [comment]
@hamzanaveedmalik I havent attempted it, but based on this blog post perhaps you could add it as a nuxt plugin and make sure it only renders client side? https://medium.com/@codebeast_/why-your-third-party-plugin-dont-work-in-nuxt-and-how-to-fix-it-d1a8caadf422

**Comment by hamzanaveedmalik** [comment]
@bmounteer  I gave it a try but still the error persists.
