### ISSUE TITLE
Config to work with Social Login & hybrid flows ?

### ISSUE THREAD

**Issue by fgyara2** [okta/okta-oidc-js#48]
I can see that at present this doesn't quite vibe with the Social Login capabilities that Okta has:
- for one the base for the issuer (e.g. https://dev-xxxx.oktapreview.com/oauth2/ _default_ ) is marginally different from url generated for social login ( e.g.  https://dev-xxxx.oktapreview.com/oauth2/ _v1_ )
- the social login auth URL requires an `idp` query parameter
- from a quick skim of the docs, it looks like social uses hybrid flow.

Are there any plans to support Social through this library ?

**Comment by robertjd** [comment]
HI @fgyara2 , thank you for the request.  We don't have social (hybrid) support on deck yet, but may in the future.

**Comment by jmelberg-okta** [comment]
This is possible by passing the `idp` parameter through one of the login methods.

See how in any of the following libraries:
  - [okta-angular](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-angular#oktaauthloginredirectfromuri-additionalparams)
  - [okta-react](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#authloginfromuri-additionalparams)
  - [okta-vue](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-vue#authloginredirectfromuri-additionalparams)
