### ISSUE TITLE
Update @okta/jwt-verifier to 1.0.0 on npm

### ISSUE THREAD

**Issue by fuzzthink** [okta/okta-oidc-js#488]
## I'm submitting this issue for the package(s):

- [x] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [ ] Feature request
- [x] Other (Describe below)

## Current behavior
@okta/jwt-verifier published as 0.16.0

## Expected behavior
Update @okta/jwt-verifier to 1.0.0 on npm since it's already at 1.0.0:
https://github.com/okta/okta-oidc-js/blob/master/packages/jwt-verifier/CHANGELOG.md#fixes

## Minimal reproduction of the problem with instructions
npm i @okta/jwt-verifier@1.0.0

npm ERR! notarget No matching version found for @okta/jwt-verifier@1.0.0

## Environment
any

**Comment by swiftone** [comment]
Hi @fuzzthink - sorry for the delay in getting back to you, but 1.0.0 was published to npm.  Let us know if you encounter any problems.
