### ISSUE TITLE
okta-react requires react-router (not nextjs et al)

### ISSUE THREAD

**Issue by dimacros** [okta/okta-oidc-js#499]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [x] Feature request
- [ ] Other (Describe below)

## Current behavior

It only works with react-router.

## Expected behavior

If we apply the SOLID principles, this library must be independent of the router you use.

## Extra information about the use case/user story you are trying to implement

I think that if the behavior of the library is to authenticate, then it must be agnostic with the library you use to route, but in this case it is not. This library forces me to use react-router and I am currently working with nextjs, you must create a way that is independent to the router or add support for nextjs.

**Comment by swiftone** [comment]
Note: include this in internal discussions about removing dependency on any particular router.

**Comment by abachuk** [comment]
any update on this?

**Comment by swiftone** [comment]
@abachuk - No update other than the JS team agreeing with the request and it is just about getting it to the top of the priority list to fix.  Sorry we don't have better news to report.

**Comment by swiftone** [comment]
Internal ref: 232097

**Comment by samantha-wong** [comment]
+1 on this issue. Would love to be able to use Nextjs with okta.

**Comment by swiftone** [comment]
`@okta/react-router` 2.x no longer requires the use of react-router.

It continues to provide support for react-router, and react-router is listed as a `peerDependency` (there is no "optional peer dependency" option that I'm aware of), but this version should work with other routers without react-router installed.
