### ISSUE TITLE
Add support for asserting claims that are an array (jwt-verifier)

### ISSUE THREAD

**Issue by vijetmahabaleshwar-okta** [okta/okta-oidc-js#50]
Currently we don't support asserting claims that can be an array.
E.g

`const oktaJwtVerifier = new OktaJwtVerifier({
  issuer: "http://localhost:9090/oauth2/default",
  assertClaims: {
    aud: 'api://default',
    scp: ['read','write','execute']
  },
});`

If we try to verify an access token that contains all these claims, we will throw a 401, as we only do string comparison on the claims.

We need to add support for array comparison on claims

**Comment by lobabob** [comment]
This should be more than just an enhancement. Afaik, the spec says the `aud` claim can be either a string or array and this ticket existing prevents validating that.

**Comment by swiftone** [comment]
The syntax is different, but I believe this is all covered under the new(ish) custom claims assertions: https://github.com/okta/okta-oidc-js/tree/master/packages/jwt-verifier#custom-claims-assertions

If that doesn't resolve the need, please open a new issue with details and reference this one.
