### ISSUE TITLE
User can’t login / User/Groups assign

### ISSUE THREAD

**Issue by oferRounds** [okta/okta-oidc-js#507]
In the readme file, it says:

> Note: As with any Okta application, make sure you assign Users or Groups to the OpenID Connect Client. Otherwise, no one can use it.

Now, i think somethings basic is not clear to me: If I want to allow external users to login to our platform via Okta SSO, how can I assign them first? As I don’t "know" them

Specifically, we already allow Okta login on our web-desktop platform, and we now want to add the ability to login also from our app

Currently, we have created the mobile native app, as described in the Readme, but sign in fails (probably because of the un-assigning)

Would be happy for your help!

Thanks so much!
Ofer

**Comment by swiftone** [comment]
@oferRounds - Thanks for the feedback, it's a fair question.  I suggest you try asking this question on our forums ( https://devforum.okta.com/ ) as you'll get a wider audience.  The GitHub issues are reserved for technical issues.

If the forums don't provide an answer, feel free to reopen this issue!
