### ISSUE TITLE
React Native pod install for OktaSdkBridgeReactNative spec fails validation

### ISSUE THREAD

**Issue by ludu12** [okta/okta-oidc-js#511]
**Submitting this for okta-react-native package**

Following the iOS setup instructions results in an error when running `pod install`:

```
Fetching podspec for `OktaSdkBridgeReactNative` from `../node_modules/@okta/okta-react-native`
[!] The `OktaSdkBridgeReactNative` pod failed to validate due to 1 error:
    - WARN  | source: Git sources should specify a tag.
    - ERROR | [iOS] name: The name of a spec should not contain a slash.
```

Looks like it doesn't pass cocoapods linter. Another way to reproduce issue is running `pod spec lint --verbose` in okta-react-native dircectory

Looks like because the package.json name is '@okta/okta-react-native' and used in spec file is why the error occurs.

https://github.com/okta/okta-oidc-js/blob/1f3261abbd3c27ca134fea238bc95af84b9ff655/packages/okta-react-native/OktaSdkBridgeReactNative.podspec#L6

**Comment by IldarAbdullin-okta** [comment]
Fixed in okta-react-native@1.1.0
