### ISSUE TITLE
Okta JWT Verifier SSL Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by foxymoron** [okta/okta-oidc-js#523]
##  I'm submitting this issue for the package(s):

- [x] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [x] Feature request
- [ ] Other (Describe below)

## Current behavior

Behind a proxy firewall, it is sometimes necessary to disable SSL so the strictSSL flag needs to be passed down via Okta.

Without this getting a SSL Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE.

## Expected behavior

Currently the OktaJwtVerfier constructor has no option to pass strictSsl: false
Internally it is using jwks-rsa module as jwksClient to make further calls.
The jwks-rsa constructor takes the option strictSsl but Okta is not using it.
Maybe it is opinionated but the flexibility is lost.

Below is the sample code that needs to be used via nodejs to resolve the issue.
```
const oktaJwtVerifier = new OktaJwtVerifier({
  clientId: '{{client_id}}',
  issuer: ''{{okta_domain}}',
  assertClaims: {
    aud: 'api://default',
  },
  strictSsl: false,
});
```

## Minimal reproduction of the problem with instructions

Simulate a proxy environment with no SSL certificate in http node server.

## Extra information about the use case/user story you are trying to implement

Unable to use OktaJwtVerifier node module behind proxy firewall.

## Environment

- Package Version: 1.0.0
- Browser: Chrome
- OS: Windows 10
- Node version (`node -v`): 10.16.0
- Other: Proxy Environment

**Comment by jerrychong25** [comment]
@foxymoron @swiftone Is this Okta JWt Verifier error (UNABLE_TO_VERIFY_LEAF_SIGNATURE) already resolved?

Just now my end also reproduce the same error, but can't find a way to resolve it.

**Comment by swiftone** [comment]
@jerrychong25 - Are you having the problem inside a proxy firewall, or are you encountering it otherwise?

**Comment by swiftone** [comment]
Internal ref: OKTA-286874

**Comment by jerrychong25** [comment]
> @jerrychong25 - Are you having the problem inside a proxy firewall, or are you encountering it otherwise?

Finally able to resolve it. 

I am using wrong Okta domain, as my end no longer use /default url path.

So now the issue is fixed.

**Comment by swiftone** [comment]
@jerrychong25 - Glad to hear it is resolved, and thanks for sharing the answer for others!
