### ISSUE TITLE
incomplete sample code in the documentation

### ISSUE THREAD

**Issue by jasonrberk** [okta/okta-oidc-js#526]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [ ] Feature request
- [x ] Other (Describe below)

documentation error - sample code incomplete

## Current behavior
at https://www.npmjs.com/package/@okta/okta-react#example-with-auth-object

<img width="809" alt="Screen Shot 2019-08-15 at 2 15 04 PM" src="https://user-images.githubusercontent.com/31823413/63116350-6c3d3c80-bf67-11e9-86ad-50fce464cbda.png">

the `Login` route is missing

**Comment by swiftone** [comment]
@jasonrberk - Thanks for the feedback!  On review, this example wasn't trying to show a customLoginComponent, so there was no /login route, but that leaves it not 100% clear what it is trying to demonstrate.  We will revise!

**Comment by swiftone** [comment]
Documentation was revised, thanks for the report!
