### ISSUE TITLE
Okta-React tokens are not verified and are not revoked.

### ISSUE THREAD

**Issue by Itachi-Ichigo** [okta/okta-oidc-js#547]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
Based on my understanding, the okta-token-storage (in local storage for example), is used to store the tokens (Access or/and Id from the authz server). The `isAuthenticated()` function exposed, for any components to check if the User is currently authenticated merely checks the presence of the tokens in local storage and DOES NOT verify them (for instance, by making an introspect call). If I were to manually revoke the tokens and somehow populate the local storage with the previous values or some random values, it will continue to return `isAuthenticated()` = true. 

`isAuthenticated()`: https://github.com/okta/okta-oidc-js/blob/896ca25019621edc04c8576cb6695a6ba7883c6a/packages/okta-react/src/Auth.js#L63

The other issue, is the `logout()` function exposed by OktaAuth, which is meant to sign the user out. But here again, the local storage is cleared and the "session ID" is deleted, but the tokens received as part of login are not really revoked. Basically, the tokens received are still valid after the user logs out. 

`logout()`: https://github.com/okta/okta-oidc-js/blob/896ca25019621edc04c8576cb6695a6ba7883c6a/packages/okta-react/src/Auth.js#L123

## Expected behavior
The expected behavior for `isAuthenticated()` would be to verify the tokens, not just verify their presence.

The expected behavior for 'logout()` would be to revoke the tokens.

## Minimal reproduction of the problem with instructions
`isAuthenticated()`: Using the sample App:
1. login 
2. get into application localstorage using Chrome dev tools
3. edit the okta-token-storage, change the access token value
4. refresh the page, it should return `isAuthenticated()` is true

`logout()`: Using the sample App:
1. login
2. get into app local storage, copy the access token or id token
3. logout
4. manually call your authz server `/introspect` with the copied token, it should show up as active 

## Extra information about the use case/user story you are trying to implement
We are building a react based SPA, server rendered using Express.js. 

## Environment

N/A

**Comment by Itachi-Ichigo** [comment]
I could use the jwt verifier to do the verification manually, but I feel `isAuthenticated` should verify that for me.

**Comment by aarongranick-okta** [comment]
@Itachi-Ichigo your observation is correct that the behavior of isAuthenticated is fairly simple. It is also called quite frequently, potentially multiple times per render. The entire `okta-react` library implements a very thin wrapper around the `okta-auth-js` library. There is an option to pass your own `Auth` object (which is the thin wrapper). Advanced users can easily customize or synthesize this wrapper. In this case, a custom `isAuthenticated()` method could implement any desired criteria, something like:
```
import { Auth, Security } from '@okta/okta-react'
const auth = new Auth(config);
auth.isAuthenticated = function() {
// custom logic, use jwt verifier?
};

<Security auth={auth} />
```

There is more information on using a custom `Auth` object here: https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#alternate-configuration-using-auth-object

While admittedly not as slick as built-in support, this method is very powerful and will be applied consistently within the React components and routes.

Please let us know if this workaround resolves your issue.

**Comment by Itachi-Ichigo** [comment]
@aarongranick-okta Thank you for the follow up. I'm still not quite convinced about the rationale behind why okta-react should not verify the tokens as part of `isAuthenticated()`. Our app uses mobx stores, so we currently wrap the okta-react `Auth` object with some of our own logic like you pointed out above, within the store. 

But in terms of what the correct logic behind checking if the user `isAuthenticated` within our SPA, would you agree that I would need to verify the validity of the tokens?

I would assume the same applied to the logout flow as well then? We are responsible for revoking the tokens.

**Comment by aarongranick-okta** [comment]
@Itachi-Ichigo The client can do some checks, such as expiration, etc. but only the server can fully validate the token. Even with constant polling it would be impossible to avoid every scenario where a token which is considered valid on the client-side could produce an error when used in a request to the server. 

A false positive occurs when the token is invalid (from server point of view), but appears valid from the client point of view. The React OIDC library assumes that only the OIDC app would be manipulating local storage and that sessions will not be ended except by logging out within the app, or by expiring.

There are some cases, as you have discovered, where these assumptions do not hold. In these cases, and others, the fact that a token is not valid may not be discovered until a request is made to an Okta server. 

With `autoRenew` set to true, that request is made by `okta-auth-js` internally when the TokenManager renews tokens. Token lifespan can be set as low as 5 minutes. 
You could check authentication status at any point with a call to `getUser()` method. If the promise throws, the exception should indicate the user is no longer logged in.

As for logging out, we have a more detailed writeup here: https://developer.okta.com/docs/guides/sign-users-out/react/sign-out-of-okta/

**Comment by Itachi-Ichigo** [comment]
@aarongranick-okta Understood, thank you again for all the information. I shall take this to my team and will close this issue sometime tomorrow, if we have no other questions.

**Comment by rohit-nsit08** [comment]
Facing the same situation. Because `isAuthenticated()` is just looking for tokens in localStorage, SecureRoute renders component on page reload, while `App.js` which has `authenticated=null` in its state, waits for `isAuthenticated()` check to finish and thus leading to duplicate component render and memory leak if components are calling APIs to fetch data and get unmounted before they can use that data.

**Comment by luispeerez** [comment]
I have the same problem as @rohit-nsit08 , before calling isAuthenticated, localStorage items on `okta-token-storage` `okta-cache-storage` are empty. After calling isAuthenticated, checking on the inspector, those items are full. I don't know if `isAuthenticated` internally writes those values in localstorage
