### ISSUE TITLE
Working example project

### ISSUE THREAD

**Issue by MarcoNisi** [okta/okta-oidc-js#550]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [x ] Feature request
- [ ] Other (Describe below)

Hi, can you provide a working example project using @okta/okta-react-native for authentication? I tried to follow the steps inside your README but, after the `signIn` method, no one of the listeners has ever been activated.
Thanks

**Comment by IldarAbdullin-okta** [comment]
Hi @MarcoNisi ,

Please refer to https://github.com/okta/samples-js-react-native repo. It contains `BrowserSignIn` sample app that will give you an idea how to use the SDK

Ildar

**Comment by IldarAbdullin-okta** [comment]
I will also add reference to the sample app into the README
