### ISSUE TITLE
Support @reach/router with react-router

### ISSUE THREAD

**Issue by jackmac92** [okta/okta-oidc-js#555]
Hi,

I'm trying to setup `@okta/okta-react` with a gatsby project. However gatsby uses `@reach/router` to handle routing instead of `react-router`. 

I was looking into forking to support @reach/router, and looking through the source of `@okta/okta-react` it seems [this](https://github.com/okta/okta-oidc-js/blob/32b9a99e3065c34cdcc97018075697356403f11d/packages/okta-react/src/Security.js#L14) use of `withRouter` is the only  aspect that could require some hacking (`@reach/router` does not ship with a comparable HOC). 
But I'm not sure what purpose it currently serves. 

Hoping someone can help me understand what it is doing, I'd be happy to send a PR with any changes I make  to allow support for  `@reach/router`

edit:

to clarify I do know what withRouter  does, just not sure why it is used here

**Comment by swiftone** [comment]
We have an item on our backlog to reduce the dependency on react-router, but it is not yet in progress.  

`withRouter` has the job of wrapping the Auth prop into the route handlers - you don't necessarily need to create an exact parallel if you're working with a router that has different higher-level abstractions.

We're always happy to look at PRs, provided you follow the recommendations in our contribution guidelines: https://github.com/okta/okta-oidc-js/blob/master/CONTRIBUTING.md

**Comment by jamesliupenn** [comment]
@jackmac92 were you able to get it to support `@reach/router`? I'm running into the same issue given the current dependency on `react-router`

**Comment by aarongranick-okta** [comment]
internal ref: OKTA-263509

**Comment by swiftone** [comment]
`@okta/react-router` 2.x no longer requires react-router.

`react-router` is still supported, and is listed as a "peerDependency" (there is no "optionalPeerDependency" that I could find), but version 2.x of SDK should work with other routers (some assembly required).
