### ISSUE TITLE
Add PKCE Flow to React SDK Documentation

### ISSUE THREAD

**Issue by mraible** [okta/okta-oidc-js#558]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [ ] Feature request
- [x] Documentation update

## Current behavior

The React SDK added PKCE support in the [1.2.2 release](https://github.com/okta/okta-oidc-js/releases/tag/%40okta%2Fokta-react%401.2.1), yet only implicit flow is listed in the [README](https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/README.md).

## Expected behavior

We should advertise that we support auth code flow with PKCE.

**Comment by robertjd** [comment]
Here? https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/README.md#configuration-options

**Comment by mraible** [comment]
No. At the very top of the README.

This library currently supports:

* OAuth 2.0 Implicit Flow

It should say Authorization Code Flow as well.

**Comment by swiftone** [comment]
Internal ticket: OKTA-254167

**Comment by swiftone** [comment]
Completed
