### ISSUE TITLE
Does Okta widget compatible with Nativescript?

### ISSUE THREAD

**Issue by ONeville** [okta/okta-oidc-js#560]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [x] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [x] Feature request
- [ ] Other (Describe below)

## Current behavior

 okta-angular is not compatible with Angular Nativescript
OktaAuthModule, is throwing exception:

Successfully synced application org.nativescript.pocokta on device emulator-5554.
JS: HMR: Hot Module Replacement Enabled. Waiting for signal.
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ERROR Error: Uncaught (in promise): Error: com.tns.NativeScriptException: Failed to find module: "./../../buffer/index.js", relative to: app/
JS:     com.tns.Module.resolvePathHelper(Module.java:151)
JS:     com.tns.Module.resolvePath(Module.java:56)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1109)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1089)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1081)
JS:     com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
JS:     android.app.Activity.performCreate(Activity.java:7136)
JS:     android.app.Activity.performCreate(Activity.java:7127)
JS:     android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
JS:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
JS:     android.app.server...

## Expected behavior

Okta widget to work properly with Nativescript Angular

## Minimal reproduction of the problem with instructions

npm i -g @angular/cli

npm i -g @nativescript/schematics

ng new --collection=@nativescript/schematics project-name --shared

npm install @okta/okta-angular @okta/okta-signin-widget

## Environment

- Package Version: 8.2+
- Browser:
- OS: Android
- Node version (`node -v`): 12+
- Other:

**Comment by mraible** [comment]
You might try looking for a NativeScript library that supports OIDC and try that with Okta. When I last looked, I was unable to find one.

**Comment by swiftone** [comment]
@ONeville - We have no current plans for NativeScript support, sorry.  Hopefully the suggestion above to seek generic OIDC libraries that Okta is compatible with is helpful.

Future readers - If you have found this response in my future and the question is still relevant, feel free to reopen to revisit the issue.

**Comment by ONeville** [comment]
Thanks @mraible and @swiftone.
I was able to develop a custom solution that supports OIDC with Okta for NativeScript.
Thus I'm confirming that the current Okta oidc js is not compatible with Nativescript as it's a fully web browser library.

**Comment by mraible** [comment]
@ONeville I discovered something similar with Ionic. I used 3rd party OIDC libraries as a workaround. Are you able to share your solution for NativeScript?

**Comment by cah-kamal-balwani** [comment]
@ONeville , can you please share how you implmented the nativescript with OKTA?

**Comment by keithgulbro** [comment]
@cah-kamal-balwani @ONeville @mraible 

I was able to integrate Okta for iOS & Android even with the iOS 14 release which has recently seemed to mess a lot of projects up. Here's a link to the repository: [Nativescript oAuth2](https://github.com/alexziskind1/nativescript-oauth2)

Nativscript platform versions:
Android: 6.5.3
iOS 6.5.2

**NOTE:** Make sure you're not using the latest version of this plugin as it's configured for Nativescript 7 which I've yet to test due to stability issues.

Here's the basic implementation inside my Nativescript-Vue project.

```
import * as nativescript_oauth2 from "nativescript-oauth2";

import * as providers from "nativescript-oauth2/providers";

import { OktaProviderTns } from "~/providers/okta";
import { mapGetters, mapActions } from "vuex";
import * as application from "application";

export default {
  data() {
    return {
      client: null,
    };
  },
    configureOAuthProviders() {
      const oktaProvider = configureOAuthProviderOkta();
      nativescript_oauth2.configureTnsOAuth([oktaProvider]);
    },
    configureOAuthProviderOkta() {
       const oktaProviderOptions = {
            clientId: "<CLIENT_ID>",
            openIdSupport: "oid-full",
            redirectUri: "<REDIRECT_URI>", // I.E. com.oktapreview.test:/callback
            urlScheme: "<URL_SCHEME>", // I.E. com.oktapreview.test
            scopes: ["openid", "profile", "offline_access"],
       };

      return new OktaProviderTns(oktaProviderOptions);
    },
    tnsOauthLogin(providerType) {
      this.client = new nativescript_oauth2.TnsOAuthClient(providerType);

      this.client.loginWithCompletion((tokenResult, error) => {
        if (error) {
          this.tnsOauthLogin("okta");
        } else {
          console.log(tokenResult)
        }
      });
    },
    async tnsOauthRefresh() {
      let client = new nativescript_oauth2.TnsOAuthClient("okta");

      // I recommend saving the access token & refresh token that are given from the loginWithCompletion method to be used here (My example shows references these values from VueX storage but you can use a more generic plugin if you'd prefer [Nativescript Secure Storage Plugin](https://www.npmjs.com/package/nativescript-secure-storage))
      client.tokenResult = this.oktaClientTokenResult;
      client.codeVerifier = this.oktaClientCodeVerifier;

      return new Promise((resolve, reject) => {
        client.refreshTokenWithCompletion((tokenResult, error) => {
          if (error) {
            this.tnsOauthLogout();
            this.tnsOauthLogin("okta");
            reject;
          } else {
            console.log(tokenResult)
            resolve(tokenResult);
          }
        });
      });
    },
    tnsOauthLogout() {
      this.removeAuthCredentials();

      let client = new nativescript_oauth2.TnsOAuthClient("okta");

      // Assign client properties used to identify the actively authenticated session
      client.tokenResult = this.oktaClientTokenResult;
      client.codeVerifier = this.oktaClientCodeVerifier;

      client.logoutWithCompletion((result, err) => {
        if (result) {
          console.log(result);
        } else {
          console.log(err);
        }
      });

      setTimeout(() => {
        if (application.ios) {
          // Required to logout iOS because the Logout route redirects to an "Undefined" (blank) page instead of the login URL
          const controller =
            application.ios.nativeApp.windows[0].rootViewController;

          controller.dismissViewControllerAnimatedCompletion(true, () => {
            console.log("Safari dismissed");
          });
          this.tnsOauthLogin("okta");
        } else {
          this.tnsOauthLogin("okta");
        }
      }, 2000);
    },
  },
};

export function configureOAuthProviders() {
  var oktaProvider = configureOAuthProviderOkta();
  nativescript_oauth2.configureTnsOAuth([oktaProvider]);
}

function configureOAuthProviderOkta() {
       const oktaProviderOptions = {
            clientId: "<CLIENT_ID>",
            openIdSupport: "oid-full",
            redirectUri: "<REDIRECT_URI>", // I.E. com.oktapreview.test:/callback
            urlScheme: "<URL_SCHEME>", // I.E. com.oktapreview.test
            scopes: ["openid", "profile", "offline_access"],
       };

  return new OktaProviderTns(oktaProviderOptions);
}

export class OktaProviderTns {
  constructor(options) {
    this.cookieDomains = ["okta"];
    this.providerType = "okta";
    this.options = options;
        this.authority = "https://test.oktapreview.com";
        this.authorizeEndpoint = "/oauth2/default/authorize";
        this.tokenEndpoint = "/oauth2/default/token";
        this.endSessionEndpoint = "/oauth2/default/logout";
        this.tokenEndpointBase = "https://test.oktapreview.com";
  }
  parseTokenResult(jsonData) {
    return jsonData;
  }
}
```

Make sure to register the URL schemes inside your Info.plist

If you encounter issues please reach out and I'll try to help.

Currently I'm working on implementing the Okta SDK as a standalone plugin instead of leveraging this generic oAuth2 plugin that has a lot of unused code which doesn't pertain to Okta.
