### ISSUE TITLE
Vuepress build fails at render HTML

### ISSUE THREAD

**Issue by krab7191** [okta/okta-oidc-js#565]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [X] okta-vue

## I'm submitting a:

- [X] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Vuepress build fails at HTML rendering step: `ReferenceError: window is not defined
    at Object.<anonymous> (node_modules/@okta/okta-vue/dist/okta-vue.js:1:222)`

## Expected behavior

The build succeeds

## Minimal reproduction of the problem with instructions

Add okta-vue to vuepress site and run Vuepress build per tutorial [here](https://developer.okta.com/blog/2019/06/14/add-authentication-and-personalization-to-vuepress)

## Environment

- Package Version: 1.1.1
- Browser: Chrome
- OS: Ubuntu 18.04 LTS
- Node version (`node -v`): 12.2.0
- Other: Vuepress 1.1.0

**Comment by swiftone** [comment]
@krab7191  - Thanks for the comment.  Unfortunately, we do not currently support server-side rendering(SSR) for our front end SDKs (including Vue), and Vuepress is heavily SSR dependent.  

If you have a particular use-case for server-side rendered OIDC interactions, I suggest you reach out to our support team at developers@okta.com with details.
