### ISSUE TITLE
express middleware not validating access token exp

### ISSUE THREAD

**Issue by saratgutha** [okta/okta-oidc-js#570]
## I'm submitting this issue for the package(s):

- [x] oidc-middleware

## I'm submitting a:

- [x] Bug report

## Current behavior
oidc-middleware isn't validating exp on access token for subsequent requests. The middleware lets users access secure endpoints even after an access token has expired.

## Expected behavior
oidc-middleware needs to validating exp on access token and redirect the user to login if the access token is expired.

## Minimal reproduction of the problem with instructions
**Configuration In Okta**

1. Create an OAuth Web application
2. Select "Authorization Code" selected for allowed grant types.
3. Add login redirect URL - http://127.0.0.1:3000/authorization-code/callback (The application on localhost will be on http://127.0.0.1:3000)
4. Add the test user/group to the Oauth app so the user is granted access to this app.
5. Modify the authorization server to set Access token lifetime to 5 minutes. Security -> API --> Authorization Servers --> Edit --> Access Policies --> Default Policy (or the relevant policy) --> Default Policy Rule (or the relevant one) --> Edit --> THEN Access token lifetime is 5 minutes. Note: The default validity of access tokens is one hour, and reducing this to 5 minutes expedites the testing.

**Steps On localhost**
1. Set up a sample OIDC application to use the above middleware. Have it use cookie-session. The issue is reproducible with express-session too getting started with and testing with cookie-session is easier. I can provide a sample app if needed.
2. Access the application in a browser at http://127.0.0.1:3000 to start the login process. Login with a user that is assigned to the Okta OAuth application either directly or through a group (See step 4 in "In Okta" above).
3. After a successful authorization, you will see two cookies 'express:sess' and 'express:sess.sig' which are both set to expire in 10 minutes.
7. Reload the page within 5 minutes of the initial request. At this point both the access token and the cookie are valid i.e. not expired. On reloading the page, there is no call to okta authorize endpoint. This is expected behaviour.
8. Reload the page between 5 and 10 minutes of the initial request. At this point, the access token has expired but cookie hasn't. On reloading the page, there is no call to okta authorize endpoint. This is NOT the expected behaviour. Expected behaviour - okta oidc middleware needs to check the exp on access token, and as the access token is expired, it needs to redirect the user to login.

## Extra information about the use case/user story you are trying to implement
While it is possible to set the expires on the cookie and access token to be the same, there is nothing that stops an end user from modifying the cookies on their browser to exceed the lifetime of the access token and therefore the middleware needs to validate the expiry on the access token before letting users access secure resources.

## Environment

- Package Version: 2.0.0
- Browser: Chrome Version 77.0.3865.90 (Official Build) (64-bit)
- OS: Ubuntu 18.04
- Node version (`node -v`): v8.10.0 (but reproducible with later versions too)
- Other:

**Comment by robertjd** [comment]
Hi @saratgutha , thanks for the question.  This library does not use access tokens as an access control mechanism for routes within the express application.  After authentication, a local session is created for the express application and you can use this as you need. The access tokens are made available if you wish to use those for access control decisions, we leave that decision up to you and our use case.
