### ISSUE TITLE
How should I sign out when using a custom sign in for React Native?

### ISSUE THREAD

**Issue by lemonlimemango** [okta/okta-oidc-js#572]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [x] Feature request
- [ ] Other (Describe below)

## Current behavior

When using a custom sign in flow with React Native (like in this [branch example](https://github.com/okta/samples-js-react-native/tree/iabdullin/native-sign-in/custom-sign-in)), I don't have a good way to sign out. 

There is the [`signOut`](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react-native#signout) method listed in the readme, but that only works if I am using browser log in.

## Expected behavior

I would like to be able to sign out of a react native app (delete the tokens from the store, and ideally revoke them) that uses custom sign in.

## Minimal reproduction of the problem with instructions

Try to sign out on the [`custom-sign-in` branch](https://github.com/okta/samples-js-react-native/tree/iabdullin/native-sign-in/custom-sign-in)

## Environment

- Package Version: 1.2.1
- OS: iOS
- Node version (`node -v`): 11.11.0
- Other: React Native

cc @andrewvanbeek-okta who helped troubleshoot this issue

**Comment by jdnichollsc** [comment]
for me it works but if you call `createConfig` before :)

**Comment by swiftone** [comment]
@lemonlimemango - Does the suggestion from @jdnichollsc resolve your issue?

**Comment by swiftone** [comment]
Closing as this seems to be resolved.  If this problem persists please reopen the issue or create a new one with details.

**Comment by sadikyalcin** [comment]
Just bumped into this; `signOut` is opening browser and asking for `sign in` permission on iOS (haven't tried android yet). I'm using native signIn and this doesn't feel slick. Is this intended or we don't have such feature yet?

**Comment by shuowu** [comment]
@sadikyalcin The `signOut` function exposed from `okta-react-native` is for `browser-sign-in&out` purpose. Please use `clearTokens` function if you are working on `custom-sign-in` flow, you can also find sample code here: https://github.com/okta/samples-js-react-native/blob/master/custom-sign-in/app/ProfileScreen.js#L71

**Comment by sadikyalcin** [comment]
> @sadikyalcin The `signOut` function exposed from `okta-react-native` is for `browser-sign-in&out` purpose. Please use `clearTokens` function if you are working on `custom-sign-in` flow, you can also find sample code here: https://github.com/okta/samples-js-react-native/blob/master/custom-sign-in/app/ProfileScreen.js#L71

Ow I've missed that out. Thank you.
