### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. 

### ISSUE THREAD

**Issue by RobinClowers** [okta/okta-oidc-js#573]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
When logging in to our single page app, okta-react renders this error on the page: `AuthApiError`. In the console, I see this: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://logon.okta.com/oauth2/default/.well-known/openid-configuration.`

This happens in Chrome and Firefox.

## Expected behavior
I should be able to log in successfully

I can't build a repro, it doesn't happen locally. This same code works fine in other environments. This is a React single page app built with Create React App. We recently upgraded the Okta client libraries to fix another bug we ran into. It worked fine locally, but fails in some live environments.

My issue seems to be exactly the same as this closed issue: https://github.com/okta/okta-oidc-js/issues/337. Possibly a regression?

## Environment

- Package Version: okta-auth-js 2.8.0 and okta-react 1.2.3
- Browser: Chrome 77, Firefox 69
- OS: macOS 10.14.6
- Node version (`node -v`): 8.11.3
- Other:

**Comment by swiftone** [comment]
@RobinClowers  - Thanks for the report.  We've not gotten any reports nor test failures similar to what you describe.

Common issues: 
1) Do you have the CORS setting enabled for the _exact_ proper domain (Trusted Origins in Admin UI)?  
2) Check the network tab in the Chrome debugger and see if the call is a 200 code or not.  Calls that report errors (4xx, 5xx) will often not include the CORS headers, leading to a misleading message from the browser (the issue isn't CORS, but instead whatever caused the error)

**Comment by RobinClowers** [comment]
Thanks for getting back to me. I don't know what changed, but I'm no longer seeing this issue. I don't have access to see the settings on the application, so it's possible it was a cors misconfiguration.
