### ISSUE TITLE
okta-react-native dependency causes `global.document` definition error

### ISSUE THREAD

**Issue by lemonlimemango** [okta/okta-oidc-js#575]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Adding the `okta-react-native` library breaks other libraries in React Native apps.

The library [`mrsCrypto`](https://github.com/kevlened/msrCrypto) depends on `global.document`, and, when `global.document` is not present, [the library defines it](https://github.com/kevlened/msrCrypto/blob/1.5.7/dist/msrcrypto.mjs#L38):

```js
if (typeof document === 'undefined' && glb) {
    glb.document = {
        attachEvent: function() {}
    };
}
```

Here you can see that `mrscrypto` is a nested dependency of the `okta-react-native` package:

```
➜ CustomSignIn git:(iabdullin/native-sign-in) ✗ npm ls msrcrypto
CustomSignIn@0.0.1 /src/samples-js-react-native/custom-sign-in/CustomSignIn
└─┬ @okta/okta-react-native@1.2.1
  └─┬ jwt-lite@1.1.4
    └─┬ jws-lite@0.1.2
      └─┬ isomorphic-webcrypto@1.6.2
        └── msrcrypto@1.5.7
```

Other libraries, such as [`emotion`](https://github.com/emotion-js/emotion), quite reasonably use `document` to [determine if the code is running in a browser or not](https://github.com/emotion-js/emotion/blob/16ff233061e35fe71bfb1671da54ac12d6fc9eeb/packages/cache/src/index.js#L9):

```js
let isBrowser = typeof document !== 'undefined'
// ...
if (isBrowser) {
  container = options.container || document.head
  const nodes = document.querySelectorAll(`style[data-emotion-${key}]`)
```
https://github.com/emotion-js/emotion/blob/16ff233061e35fe71bfb1671da54ac12d6fc9eeb/packages/cache/src/index.js#L68-L71

This results in `document.querySelectorAll` running in the React Native App, which causes an error like

```
document.querySelectorAll is not a function
```

## Expected behavior

Installing and using the `okta-react-native` library should not result in `global.document` being defined.

## Minimal reproduction of the problem with instructions

Try using storybook with `okta-react-native` installed

## Extra information about the use case/user story you are trying to implement

There is a bad workaround in which I reset `global.document = undefined` in my app, but I would really rather not do this.

## Environment

- Package Version: 1.2.1
- Browser: N/A
- OS: iOS
- Node version (`node -v`): 11.11.0
- Other: React Native

cc @andrewvanbeek-okta

**Comment by BenjaminWatts** [comment]
I seem to be having this issue on a new react native app. Did it ever get fixed?
