### ISSUE TITLE
`revokeAccessToken` in React Native with custom sign in doesn't seem to work

### ISSUE THREAD

**Issue by lemonlimemango** [okta/okta-oidc-js#576]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Calling [`revokeAccessToken`](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react-native#revokeaccesstoken) in a React Native app when using custom sign in doesn't seem to actually revoke the tokens. Calling `isAuthenticated` after revoking continues to return `true`.

## Expected behavior

After calling `revokeAccessToken`, `isAuthenticated` should return `false`.

## Minimal reproduction of the problem with instructions

I have created a sample of the functionality I am looking for in this pull request: https://github.com/lemonlimemango/samples-js-react-native/pull/1

## Extra information about the use case/user story you are trying to implement

I was trying to use `revokeAccessToken` as a backup for the lack of `signOut` support (which I reported in this issue: https://github.com/okta/okta-oidc-js/issues/572).

I really need a way to log users out of my React Native app.

## Environment

- Package Version: 1.2.1
- Browser: N/A
- OS: iOS/React Native
- Node version (`node -v`): 11.11.0
- Other:

**Comment by swiftone** [comment]
Hey @lemonlimemango - Thanks for the report.

This is a known complication and common misunderstanding.  `isAuthenticated()` talks about the local application, and calling `revoke` does not remove the token from the local app.  `isAuthenticated()` does not do a check for revoked tokens (part of the concept of tokens is that you don't check the source for revocation on every check - the idea is to get a token, confirm the signature, and it is good for the lifespan of that token.  Any introspection call to check for revocation would have to be explicitly done.

Your concern is valid, and we're trying to come up with a good representation that is clearly understood and does not greatly increase the amount of traffic.  In this particular case, where `revoke` is called the intent that the user no longer be authenticated is _probably_ clear, though it is just the more clear example.  

That covers the longer term issue (i.e. we're looking into it), but for your immediate signout need I'll poke our mobile folks to see what the recommended logout path for non-browser apps is.

**Comment by IldarAbdullin-okta** [comment]
@lemonlimemango , please use latest iOS OIDC SDK - 3.5.2. This version should resolve reported issue
