### ISSUE TITLE
`refreshTokens` doesn't work in React Native with Custom Sign In

### ISSUE THREAD

**Issue by lemonlimemango** [okta/okta-oidc-js#577]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Calling [`refreshTokens`](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react-native#refreshtokens) in React Native using a custom sign in fails. It appears to be a `403` error.

## Expected behavior

Calling `refreshTokens` should succeed.

## Minimal reproduction of the problem with instructions

I have made a Pull Request that highlights the functionality I am looking for: https://github.com/lemonlimemango/samples-js-react-native/pull/2

## Extra information about the use case/user story you are trying to implement

I don't have access to the refresh token itself, since it was saved to the phone's storage when calling `authenticate` earlier in the flow, and there doesn't seem to be a `getRefreshToken` method available, so I can't workaround by manually making the API call to refresh the tokens.

## Environment

- Package Version: 1.2.1
- Browser: N/A
- OS: iOS/React Native
- Node version (`node -v`): 11.11.0
- Other:

**Comment by IldarAbdullin-okta** [comment]
Hi @lemonlimemango ,

Please use latest Okta OIDC SDK. This issue should be fixed in 3.5.2 version

Ildar
