### ISSUE TITLE
okta-react doesn't work with TypeScript

### ISSUE THREAD

**Issue by mraible** [okta/okta-oidc-js#58]
I created a React application with TypeScript and Create React App:

```
npm install -g create-react-app
create-react-app my-app --scripts-version=react-scripts-ts
```

When I try to import `Security` and `ImplicitCallback` in `src/App.tsx`, I get the following error:

```
(3,22): error TS7016: Could not find a declaration file for module '@okta/okta-react'. 
'/Users/mraible/dev/okta/spring-boot-react-example/client/node_modules/@okta/okta-react/dist/index.js' 
implicitly has an 'any' type.
  Try `npm install @types/@okta/okta-react` if it exists or add a new declaration (.d.ts) file   
  containing `declare module '@okta/okta-react';`
```

**Comment by mraible** [comment]
I created `src/okta.d.ts` with the following as a workaround.

```typescript
declare module '@okta/okta-react';
```

Now I get the following error.

![screen shot 2017-11-28 at 6 56 02 am](https://user-images.githubusercontent.com/17892/33323341-738f5c34-d409-11e7-8638-899c355022f0.png)

To reproduce this error, perform the following steps:

```bash
git clone git@github.com:oktadeveloper/spring-boot-react-example.git
git checkout okta
cd client 
yarn
yarn start
```

You can also see [this commit](https://github.com/oktadeveloper/spring-boot-react-example/commit/d076110960baa7fdfe209993f3057a8c7a8ef932) where I attempt to get @okta/okta-react working.

**Comment by robertjd** [comment]
Thanks @mraible , TS isn't a huge prio for this repo ATM but if you keep exploring please post what you find.

**Comment by mraible** [comment]
@robertjd I've written a React + Spring Boot example for a blog post and two presentations I'm doing next week. This is a blocker for me demoing the Okta SDK. I'm fine with that, just wanted to make you aware.

BTW, is there an easier way to integrate `props.auth` with React? Wrapping a whole class with `withAuth` seems strange. Also, I'm not sure how to export the class by name (to import into other classes) when it's wrapped like this.

**Comment by mraible** [comment]
Nevermind, I got it to work. ;)

**Comment by lboyette-okta** [comment]
@mraible the `withAuth` pattern for higher-order components is the same approach taken by `react-router`: https://reacttraining.com/react-router/web/api/withRouter

**Comment by mraible** [comment]
Thanks for the explanation @lboyette-okta. I learned it's also possible to pass the auth between components. For example:

```html
<div className="Buttons">
  <button onClick={this.props.auth.logout}>Logout</button>
  <BeerList auth={this.props.auth}/>
</div>
```

**Comment by tsiq-swyx** [comment]
@mraible could you share your .d.ts?? what did you do!!

**Comment by mraible** [comment]
See https://github.com/okta/okta-oidc-js/issues/66#issuecomment-394574326

**Comment by christopher-caldwell** [comment]
It's 2020 and this package is still not typed.

**Comment by swiftone** [comment]
@christopher-caldwell - thanks for sharing.

Hopefully you'll be happy to notice that we have updated `okta-auth-js` (https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-4.0.0) to include typescript.

`okta-react` consumes `okta-auth-js` so that migration was an important step to convert `okta-react` and our other JS libraries to include typescript types, and those changes are on the way.
