### ISSUE TITLE
Okta is not working with Internet Explorer 

### ISSUE THREAD

**Issue by farhan711** [okta/okta-oidc-js#583]
Okta login is not working on Internet Explorer 9 or any version till 11. Why is that happening? 
API call to login page is not even getting triggered

**Comment by swiftone** [comment]
Older versions of IE are not supported by Okta (see https://help.okta.com/en/prod/Content/Topics/Miscellaneous/Platforms_Browser_OS_Support.htm for our official support policies)

I cannot speak for Okta as to "why", but as a web developer I can say it is important to get the security benefits of newer browsers that are supported by their manufacturer (you can see the following link to see that only IE 11 is supported by Microsoft, and they recommend moving to Microsoft Edge: https://support.microsoft.com/en-us/help/17454/lifecycle-faq-internet-explorer )
