### ISSUE TITLE
OktaAuthModule for Angular breaks unrelated HttpClientModule

### ISSUE THREAD

**Issue by EthanStandel** [okta/okta-oidc-js#591]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [x] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

1. Import the OktaAuthModule into the root module in any Angular application that may otherwise support IE11
2. Make sure the OKTA_CONFIG provider specifies { pkce: true }
3. Load the application in IE11
4. Notice no errors are thrown until you try to make any request through HttpClient.

All requests throw before even being attempted, and the only way to notice is to pipe the request observable and add a catchError operator that logs the error.  The error is an object with an errorSummary property that says "This browser doesn't support PKCE".

## Expected behavior

I would hope that if there's a problem with instantiating the OktaAuthModule, the instantiation of that module would throw the error and identify itself.  I'd also hope that any errors with particular modules could also be siloed to only those modules and/or dependents of them.  HttpClientModule should not be throwing errors because the OktaAuthModule was missing a dependency.  I assume this is because of an HttpInterceptor in the OktaAuthModule, but if my request has nothing to do with Okta or authentication, then the interceptor should not interfere with my request.

## Minimal reproduction of the problem with instructions

( the same steps as listed above )
1. Import the OktaAuthModule into the root module in any Angular application that may otherwise support IE11
2. Make sure the OKTA_CONFIG provider specifies { pkce: true }
3. Load the application in IE11
4. Notice no errors are thrown until you try to make any request through HttpClient.

## Environment

- Package Version: @okta/okta-angular@1.2.2
- Browser: IE11
- OS: Windows 10
- Node version (`node -v`): v10.15.3
- Other:

**Comment by EthanStandel** [comment]
The reason I ran into this was because I was testing my application in IE11 and we request a series of resource bundles at startup.  We use the HttpClient to get these and sort them out, and seemingly those requests were bombing out but the network monitor said that were never attempted.  I spent a lot of time digging into the intricacies of the pita that is IE and it's compatibility mode and other stuff.  I thought I'd somehow blown up my polyfill configuration and I was missing something essential that was making requests fail before they were made.  Turns out it was this issue and I only realized once I thought to actually log the error itself (which never auto-logged, because we were catching errors and managing them in our resource-bundle library).

**Comment by swiftone** [comment]
@EthanStandel, thanks for the report!

IE11 doesn't support webcrypto, and thus doesn't support PKCE.  

https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto

It can be a difficult to detect this (my sympathies!) - we're looking into how to improve the error messaging.

If you need to check for this, there is a check you run through the exposed Auth object: `OktaAuth.features.isPKCESupported()` - but in general we recommend users use modern browsers that fully support security options. 

https://github.com/okta/okta-auth-js#pkce-oauth-20-flow describes the issue and options in more detail.

**Comment by EthanStandel** [comment]
Unfortunately, a large portion of my user base is on IE11 so I made it a priority to make it work.  But the ticket was only a request that the OktaAuthModule not interfere with requests from HttpClientModule in Angular.  But I do get why the exception is thrown in general, but the error being thrown outside of any Okta context really obfuscates the problem.

Outside of the scope of this ticket, but:

I was able to make the authorization flow with PKCE work in IE11 by polyfilling [Crypto.subtle](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle) and [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) with [webcrypto-shim](https://github.com/vibornoff/webcrypto-shim) and [text-encoding](https://github.com/inexorabletash/text-encoding) respectively.  I got the links off the MDN docs so I figured they must be at least mildly trustworthy (and I did a vague vetting myself).

But does your team have any documentation for how to support IE11 if we have to?  I've found at least [one place that states that your SDKs support it](https://help.okta.com/en/prod/Content/Topics/Miscellaneous/Platforms_Browser_OS_Support.htm).

**Comment by swiftone** [comment]
Hey @EthanStandel - The SDK supports IE11, the PKCE _feature_ does not.  If you had `pkce: false` there should be no error.

The link you found correctly lists the browsers we support - sorry if I made it sound otherwise (we support IE11, but we don't recommend it, which I believe matches Microsoft's position).  I certainly appreciate business realities about supporting it - I was just justifying why we don't better highlight the `isPKCESupported()` call.  Sorry about that.

> But does your team have any documentation for how to support IE11 if we have to?

So far as I know (and I could be wrong, but...) PKCE is the only SDK feature that has requirements beyond the Okta support (excluding obvious things like `localStorage` etc).  We do support IE11, so if you need PKCE support beyond what you've uncovered you can open an issue to request that (I'd recommend also contacting our support team at developers@okta.com to ensure the issue gets appropriate prioritization).

But outside of PKCE, I'm not aware of any complication regarding IE11 and our SDKs.  

Hope that helps!  And thanks for sharing your investigations into polyfilling support - anyone else looking to do the same will benefit from your work before and if we end up adding IE11 PKCE support.

**Comment by EthanStandel** [comment]
Yeah, that does help, thank you.  I just wanted to make sure I wasn't going to run into any other unexpected hiccups with any other feature that I might implement.  I definitely wish I didn't have to support IE but that's why I try to research stuff ahead of time rather than debugging problems as they appear.  The actual debugger in IE crashes sites constantly, especially if you're debugging source-mapped TypeScript in Angular's case.

**Comment by swiftone** [comment]
@EthanStandel - Looks like we have some work in progress that addresses Edge as well as IE.  See the updates to the README in this PR: https://github.com/okta/okta-auth-js/pull/284/files

**Comment by EthanStandel** [comment]
@swiftone That's exactly what I was hoping for!  And it definitely makes more sense that the change had to be implemented in that repo rather than this one!  Thanks for the update.  Should I close this ticket now (seeing as the problem was more related to the dependency) or when the version of okta-oidc-js utilizes the okta-auth-js dependency.

**Comment by swiftone** [comment]
Let's leave it open for now until we get that PR in.  The packages in okta-oidc-js should consume minor version bumps, so no need to wait for a second round of updates.

**Comment by aarongranick-okta** [comment]
@EthanStandel We have updated `okta-auth-js` to include detection of missing `TextEncoder` in this `isPKCESupported` method. With a `TextEncoder` polyfill, we have tested and verified PKCE flow on IE Edge.

**Comment by EthanStandel** [comment]
Sorry to get back to this so late!  Thank you @swiftone & @aarongranick-okta, closing!
