### ISSUE TITLE
Package is broken: Published okta-react while ignoring dist folder

### ISSUE THREAD

**Issue by mbergeronupgrade** [okta/okta-oidc-js#60]
The published package is lacking the dist folder.

Since the main resolves to the `dist` folder the package cannot be used anymore.

The ignore is being picked up from your .gitignore, you'd need a separate .npmignore to unignore it for publishing purposes.

See https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by mbergeronupgrade** [comment]
Issue resolved, thank you.

**Comment by robertjd** [comment]
Perfect!  We did just release 0.9.0 with a dist/ folder in it.  You beat us back to this issue :)
