### ISSUE TITLE
`refreshTokens` does not persist new tokens in React Native

### ISSUE THREAD

**Issue by lemonlimemango** [okta/okta-oidc-js#605]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Currently, calling `refreshTokens` in React Native using custom-sign-in will return new tokens, but will not save them anywhere. So, calling `getAccessToken` after calling `refreshTokens` returns the **_old_** tokens.

## Expected behavior

Calling `refreshTokens` should write the new tokens to secure storage, or at least there should be a method exposed to me to write the new tokens to storage.

## Minimal reproduction of the problem with instructions

Call the methods in this order:

```js
const accessToken1 = await getAccessToken(); // note value
const tokensFromRefresh = await refreshTokens(); // note value in accessToken1.access_token
const accessToken2 = await getAccessToken(); // note value
```
In this example, `accessToken1 === accessToken2` and `tokensFromRefresh.access_token` is a different value.

## Extra information about the use case/user story you are trying to implement

Looking through the code a bit, the iOS library seems to suggest that the consumer needs to manage persisting the new tokens. (https://github.com/okta/okta-oidc-ios/blob/253c6995483cf933a9c5aa3c40785751e7a33b5a/README.md#statemanager)

I think potentially this method is incorrectly _not_ persisting the tokens:

https://github.com/okta/okta-oidc-js/blob/32b9a99e3065c34cdcc97018075697356403f11d/packages/okta-react-native/ios/OktaSdkBridge.swift#L349-L355

## Environment
```
"@okta/okta-react-native": "^1.2.1",
"react": "16.8.6",
"react-native": "0.60.5",
```

- Package Version: 
- Browser: N/A
- OS: iOS
- Node version (`node -v`):
- Other:

**Comment by IldarAbdullin-okta** [comment]
@lemonlimemango , this has been fixed in 1.2.2 version
