### ISSUE TITLE
@okta/okta-angular: Provide router options for all calls to navigate

### ISSUE THREAD

**Issue by EthanStandel** [okta/okta-oidc-js#606]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [x] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [x] Feature request
- [ ] Other (Describe below)

## Current behavior

When library users utilize the @okta/okta-angular library, any navigation events in okta.service.ts are passed forward as standard navigation events without any other provided options.

## Expected behavior

I would like all methods which call Angular's router.navigate to open up an additional optional argument to override properties in the NavigationExtras argument of router.navigate calls.

## Minimal reproduction of the problem with instructions

Note that there's no way to override the NavigationExtras options for calls which result in Angular navigation.

## Extra information about the use case/user story you are trying to implement

The main use-case for this feature is so that users can customize how they navigate.  For instance, when the OktaCallbackComponent is routed to, a developer may prefer that they navigate using the option `{ replaceUrl: true }`.  That way a client couldn't accidentally back into the `implicit/callback` route because it's no longer on the history stack.

## Environment

- Package Version: @okta/okta-angular@1.2.2
- Browser: Chrome
- OS: Mac
- Node version (`node -v`): v10.16.3
- Other:

**Comment by aarongranick-okta** [comment]
Thanks for your submission, we will review how best to handle this. We have created an internal issue for reference: OKTA-263507

**Comment by EthanStandel** [comment]
Just came through to clean up this issue. I know the underlying routing model changed for this so the request is irrelevant now.
