### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by jdnichollsc** [okta/okta-oidc-js#608]
## I'm submitting this issue for the package(s):

- [x] okta-react

## I'm submitting a:

- [x] Bug report  

## Current behavior
I'm getting this error after execute the okta widget locally:
<img width="1340" alt="Captura de Pantalla 2019-12-02 a la(s) 9 52 24 a  m" src="https://user-images.githubusercontent.com/2154886/69968945-77ea4a00-14e9-11ea-8547-687d6cad3b9f.png">

## Expected behavior
Be able to run the okta widget locally

## Minimal reproduction of the problem with instructions
- Install npm packages by running: `npm i`
- Start the project: `npm start`

## Environment
- Package Version:
   "@okta/okta-react": "1.0.2"
   "@okta/okta-signin-widget": "2.13.0"
- Browser: Chrome
- OS: MacOS Mojave 10.14.6
- Node version (`node -v`): v10.15.3

**Comment by aarongranick-okta** [comment]
The error indicates that no "issuer" was provided with the config. A value for "issuer" is required. See: https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#security for more information.

**Comment by jdnichollsc** [comment]
You're right, thanks!
