### ISSUE TITLE
Have a redirection prop implicit call back

### ISSUE THREAD

**Issue by vasanthkumar97** [okta/okta-oidc-js#611]
## I'm submitting this issue for the package(s):

- [*] okta-react

## I'm submitting a:

- [ ] Feature request

## Current behavior

The ImplicitCallback component currently redirects to "/" by default or picks the redirection url from local storage. 

## Expected behavior
Can we have a prop to which it is supposed to be redirected. Suppose i i could always say 3rd route in my browser history stack always, it can redirect directly to the page which the user was trying to reach before signing in.

PS : I'm happy to work on this feature request.

**Comment by aarongranick-okta** [comment]
The `ImplicitCallback` component is provided as a bare-bones implementation. For customization, we recommend copying the contents of this file and making your own callback component. This will let you customize any aspect of it's behavior.

**Comment by vasanthkumar97** [comment]
Should work. thanks
