### ISSUE TITLE
[React Native - Android] Detox build fail

### ISSUE THREAD

**Issue by mmeissonnier** [okta/okta-oidc-js#612]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
When building with detox, the build fail with the following error :
```
> Task :@okta_okta-react-native:mergeExtDexDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@okta_okta-react-native:mergeExtDexDebugAndroidTest'.
> Could not resolve all files for configuration ':@okta_okta-react-native:debugAndroidTestRuntimeClasspath'.
   > Failed to transform artifact 'oidc-androidx.aar (com.okta.android:oidc-androidx:1.0.2)' to match attributes {artifactType=android-dex, dexing-enable-desugaring=false, dexing-is-debuggable=true, dexing-min-sdk=19}.
      > Execution failed for DexingNoClasspathTransform: /Users/mathieu/.gradle/caches/transforms-2/files-2.1/856742d3536e7d44ba9bcaece8879a76/oidc-androidx-1.0.2/jars/classes.jar.
         > Error while dexing.
           The dependency contains Java 8 bytecode. Please enable desugaring by adding the following to build.gradle
           android {
               compileOptions {
                   sourceCompatibility 1.8
                   targetCompatibility 1.8
               }
           }
           See https://developer.android.com/studio/write/java8-support.html for details. Alternatively, increase the minSdkVersion to 26 or above.

```
## Expected behavior
It should build without problem

## Minimal reproduction of the problem with instructions
Install Detox.
Follow Detox setup for android : 
https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md

Launch command: detox build -c android.emu.debug

## Extra information about the use case/user story you are trying to implement
It works if i add these lines in node_modules/@okta/okta-react-native/android/build.gradle  :

```
android {
 ...
 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

## Environment

- Package Version: @okta/okta-react-native@1.2.1
- Browser: --
- OS: Mac OS 10.14.4
- Node version (`node -v`): 12.6
- Other:

**Comment by mraible** [comment]
I recently did a screencast with our React Native SDK and was able to use Java 12. https://youtu.be/mkT_I5tm3Ig?t=52

Adding these lines will likely force Java 8, but I expect that with Android these days.

**Comment by mmeissonnier** [comment]
Hello, thanks for the quick answer.

It also works if i set minSdkVersion to 26. Unfortunately that's not an option because the app i'm working on will have to run on tablet with API 24.

I don't have much experience in Java/Gradle build (I am a front-end developer), but if i'm getting this right, it seems that when detox launch "cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd .. " it gets oidc-androidx.aar, which is pre-compiled module, and try to recover sources back from it (what they called "desugar" ?). And that's when it fails, because the module contains Java 8 bytecode apparently...

FYI i set the compileOptions block in my app/build.gradle as well, but no success.

Thanks for your help

**Comment by swiftone** [comment]
Internal ref: OKTA-267202

**Comment by FeiChen-okta** [comment]
Hi @mmeissonnier, 

From the logs it shows desugaring is disabled `dexing-enable-desugaring=false`. Check if you have the following 

```gradle
android {
 ...
 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```
In your apps build.gradle `{yourReactNativeApp}/android/app/build.gradle`
If you already have it then check your `gradle.properties` to see if it have desugaring disabled
`android.enableDesugar=false`

**Comment by StevenHarlow** [comment]
I have also run into this issue, and I do have the following code implemented:
```
android {
 ...
 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```
and do not have desugaring disabled

**Comment by mmeissonnier** [comment]
Thanks @FeiChen-okta for your answer. I did what you advised, unfortunately that din't work.
I guess i'll have to switch minSdkVersion to 26 then.

Thank you for your time.

**Comment by swiftone** [comment]
Closing this issue.  If the minSdkVersion doesn't work for you, feel free to reopen with more details.

**Comment by david50407** [comment]
try `./gradlew assembleDebugAndroidTest` or `./gradlew assembleReleaseAndroidTest` to build Test apk

these work for me in react-native with detox (`./gradlew assembleAndroidTest` always throws like this issue)
