### ISSUE TITLE
Feature request: Allow SecureRoute to pass additional params to login

### ISSUE THREAD

**Issue by whawker** [okta/okta-oidc-js#614]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report
- [x] Feature request
- [ ] Other (Describe below)

## Current behavior
The `SecureRoute` component does not allow passing additional params through to login, when not authenticated

https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/src/SecureRoute.js#L21

## Expected behavior
I would like to be able to pass additional information through to login, such as the [`idp` parameter](https://developer.okta.com/docs/reference/api/oidc/#request-parameters), as I am using Okta with the Hub and Spoke architecture, and would like to smooth the login journey.

**Comment by aarongranick-okta** [comment]
Take a look at the `onAuthRequired` callback. This will allow you to redirect to any route with any parameters. https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#configuration-options

**Comment by whawker** [comment]
Thanks for the update, that seems to work for passing additional params to redirect.
