### ISSUE TITLE
Using "basename" in react router results in incorrect redirect after login, e.g. "example.com/app/app/path"

### ISSUE THREAD

**Issue by enuchi** [okta/okta-oidc-js#620]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

When react-router-dom `"basename"` prop is used on the BrowserRouter then I get redirected to the wrong path after successful login. See example below. 
```
// src/App.js

import React, { Component } from 'react';
import { BrowserRouter as Router, Route } from 'react-router-dom';
import { Security, ImplicitCallback } from '@okta/okta-react';
import Home from './Home';

const config = {
  issuer: 'https://${yourOktaDomain}/oauth2/default',
  redirectUri: window.location.origin + '/implicit/callback',
  clientId: '{clientId}',
  pkce: true
}

class App extends Component {
  render() {
    return (
      <Router basename="/app">
        <Security {...config}>
          <Route path='/home' exact={true} component={Home}/>
          <Route path='/implicit/callback' component={ImplicitCallback}/>
        </Security>
      </Router>
    );
  }
}

export default App;
```
If I visit `https://www.example.com/app/home` then I will successfully be redirected to the login page, and then incorrectly redirected to `https://www.example.com/app/app/home`.

## Expected behavior

If I visit `https://www.example.com/app/home` then I should be redirected to the login page and then redirected to `https://www.example.com/app/home`.

## Minimal reproduction of the problem with instructions

See above base example.

## Extra information about the use case/user story you are trying to implement

The issue seems to be that the `referrerPath` item stored in localStorage contains the basename. It should either not store the basename as part of the location, or the ImplicitCallback should remove the basename when returning the `<Redirect />`.

Here are the relevant sections.

```
  // okta-react/src/Auth.js
  async login(fromUri, additionalParams) {
    const referrerPath = fromUri
      ? { pathname: fromUri }
      : this._history.location;
    localStorage.setItem(
      'secureRouterReferrerPath',
      JSON.stringify(referrerPath)
      );
    if (this._config.onAuthRequired) {
      const auth = this;
      const history = this._history;
      return this._config.onAuthRequired({ auth, history });
    }
    await this.redirect(additionalParams);
  }
```

```
  // okta-react/src/ImplicitCallback.js
  render() {
    if (this.state.authenticated === null) {
      return null;
    }

    const referrerKey = 'secureRouterReferrerPath';
    const location = JSON.parse(localStorage.getItem(referrerKey) || '{ "pathname": "/" }');
    localStorage.removeItem(referrerKey);

    return this.state.authenticated ?
      <Redirect to={location}/> :
      <p>{this.state.error}</p>;
  }
```

## Environment

- Package Version:
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by aarongranick-okta** [comment]
internal ref: OKTA-265889

**Comment by aarongranick-okta** [comment]
@enuchi We have released a new version of the `okta-react` library (2.0) which should no longer have this flaw. If you are able to upgrade and let us know if it works for you, we would greatly appreciate it.

**Comment by swiftone** [comment]
Closing as the issue should be resolved.

**Comment by enuchi** [comment]
Thanks @aarongranick-okta @swiftone, have not had a chance to upgrade with the new version but hope to do so in the future and thanks for letting me know about the updates. Okay to close this issue.
