### ISSUE TITLE
Seeing "release: okta-angular@1.3.0, okta-react@1.30, okta-vue@1.2.0" here 3 days ago, but new versions not on NPM.

### ISSUE THREAD

**Issue by mgdodge** [okta/okta-oidc-js#622]
## I'm submitting this issue for the package(s):

- [ x ] okta-angular
- [ x ] okta-react
- [ x ] okta-vue

## I'm submitting a:

- [ x ] Other (Describe below)

## Current behavior
npmjs.com showing 3-month-old versions of packages

## Expected behavior
new versions mentioned here should be simultaneously released on npmjs.com - delay in release should not be 3+ days

## Extra information about the use case/user story you are trying to implement
I am trying to update the typescript definitions for @okta/okta-vue on DefinitelyTyped (which are a couple versions behind) and noticed the new releases here. When running the linter provided by DefinitelyTyped, it checkes whether a corresponding version has been published to npm, and fails if one is not found. This is preventing me from being able to submit typescript definitions.

## Environment

- Package Version: @okta/okta-vue 1.2
- OS: Linux
- Node version (`node -v`): 10.17.0
- Other: npm v 6.13.1

**Comment by aarongranick-okta** [comment]
Expect a release very soon!

**Comment by robertjd** [comment]
@mgdodge @mraible these packages are released now
