### ISSUE TITLE
[REACT-NATIVE] missing social login

### ISSUE THREAD

**Issue by paulux84** [okta/okta-oidc-js#625]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-react
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report
- [x] Feature request
- [ ] Other (Describe below)

## Current behavior
Actually i can't see an idps section in config so i can't use the social login function

## Expected behavior
Can use social login (es. facebook)

**Comment by swiftone** [comment]
Hi @paulux84 - Thanks for the request.  

There are several follow-up questions to better understand that context of your request - I suggest you contact our support team at developers@okta.com.  They can help with your issue and funnel any needed enhancement/documentation requests in our direction.

**Comment by oleggnidets-okta** [comment]
Hi @paulux84 
There's the parameter `idp`, please, look at [documentation](https://github.com/okta/okta-react-native#browser-sign-in).

Thanks for contribution!
