### ISSUE TITLE
React Native Debugger not working

### ISSUE THREAD

**Issue by jdnichollsc** [okta/okta-oidc-js#628]
## I'm submitting this issue for the package(s):

- [x] okta-react-native

## I'm submitting a:

- [x] Bug report

## Current behavior
We're getting an `AuthApiError` exception while the React Native Debugger is enabled, crashing the app when `authClient.signIn()` method is executed.
<img width="584" alt="auth api error" src="https://user-images.githubusercontent.com/2154886/70657479-e20d9800-1c29-11ea-8cf2-73efab6d4a69.png">

## Expected behavior
Be able to debug the app with React Native debug.

## Minimal reproduction of the problem with instructions
- Download react native samples: https://github.com/okta/samples-js-react-native
- Update packages of the `custom-sign-in` project and run from iOS simulator with react-native command: `react-native run-ios`
- Enable Debug when RN app is opened

## Extra information about the use case/user story you are trying to implement
Be able to use PKCE flow from our React Native apps with a custom UI (or using a custom okta widget from an external domain)

## Environment

- Package Version:
  "@okta/okta-auth-js": "^2.11.0",
  "@okta/okta-react-native": "^1.2.3",
  "react": "16.12.0",
  "react-native": "0.61.5",
- Browser: N/A
- OS: iOS 13.2
- Node version (`node -v`): v10.15.3

**Comment by jdnichollsc** [comment]
Also we're getting this other issue getting the access token with RN debug disabled => https://github.com/okta/samples-js-react-native/issues/27

**Comment by jdnichollsc** [comment]
Ok, it only happens using React Native debugger tool, it works using Chrome instead :)

**Comment by konampruthvirajkumar** [comment]
> Ok, it only happens using React Native debugger tool, it works using Chrome instead :)

I am getting Unable to parse response from server error when debug in on in both chrome dev tools and react native debugger.

Would you mind please share the configuration

**Comment by oleggnidets-okta** [comment]
I close the issue as fixed. 

Thanks for feedback!
