### ISSUE TITLE
jwt-verifier: issuer doesn't match error when I upgrade to 1.0.0

### ISSUE THREAD

**Issue by bunnyc1986** [okta/okta-oidc-js#632]
## I'm submitting this issue for the package(s):

- [x] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
When I upgrade to the jwt-verifier@1.0.0, it starts to verify the issuer differently.
my actual issuer is `https:/{domain}/`, but I had to set `issuer: "https://{domain}/oauth2",` because the [verifier use issuer as the API base URL to lookup keys](https://github.com/okta/okta-oidc-js/blob/master/packages/jwt-verifier/lib.js#L109).
Then I got this error: 
```
issuer https://{domain} does not match expected issuer: https://{domain}/oauth2
```
When I use the version 0.0.16, I don't see this error.

## Expected behavior

I expect either to fix the verification logic or provide a way to specify the API base URL.

## Minimal reproduction of the problem with instructions

I followed this document https://developer.okta.com/quickstart/#/react/nodejs/express

## Environment

- Package Version: 1.0.0
- Browser: Chrome
- OS: Ubuntu 18
- Node version (`node -v`): 11.11.0
- Other:

**Comment by swiftone** [comment]
Hi @bunnyc1986 - thanks for the report.  

Based on your report, everything is working as intended.  Per the README: 
> Okta Custom Authorization Servers require the API Access Management license. If you are using Okta Org Authorization Servers (which don’t require API Access Management) you can manually validate against the /introspect endpoint ( https://developer.okta.com/docs/reference/api/oidc/#introspect ).

You can also view the comments on this related issue: 
https://github.com/okta/okta-oidc-js/issues/489 

and our documentation around authorization servers: https://developer.okta.com/docs/concepts/auth-servers/

I'm not entirely sure why the pre 1.x code didn't cause you any problems - it is possible it wasn't doing the validation you expected.  We didn't remove any functionality.

Hope that helps!

**Comment by swiftone** [comment]
Closing due to lack of response.  If this issue remains a problem, feel free to reopen with more details.
