### ISSUE TITLE
Angular 8 (8.2.14) is failing to compile after upgrading to latest Okta schematics version 1.3.0

### ISSUE THREAD

**Issue by TonyGregg** [okta/okta-oidc-js#638]
## I'm submitting this issue for the package(s):

- [ ] okta-angular

## I'm submitting a:

- [ ] Bug report  

## Current behavior
ng build and serve are failing with error below
ERROR in @okta/okta-angular/dist/src/okta/models/okta.config.ts(24,22): Error during template compile of 'OKTA_CONFIG'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler.
@okta/okta-angular/dist/src/okta/models/okta.config.ts(24,22): Error during template compile of 'OKTA_CONFIG'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler.
Unexpected value 'OktaAuthModule in c:/Users/anton/Documents/Tools/angular/mini-social-app/node_modules/@okta/okta-angular/dist/src/okta/okta.module.d.ts' imported by the module 'AuthRoutingModule in c:/Users/anton/Documents/Tools/angular/mini-social-app/src/app/auth-routing.module.ts'. Please add a @NgModule annotation.
Invalid provider for the NgModule 'AuthRoutingModule in c:/Users/anton/Documents/Tools/angular/mini-social-app/src/app/auth-routing.module.ts' - only instances of Provider and Type are allowed, got:
[?[object Object]?, ...]

## Expected behavior
Application should build and run fine

## Environment

- Package Version: Angular CLI: 8.3.20
Node: 10.16.0
OS: win32 x64
Angular: 8.2.14
- Browser: Chrome
- OS: Windows and Mac
- Node version (`node -v`): Node: 10.16.0
- github app link with this error : https://github.com/TonyGregg/mini-social-app

**Comment by TonyGregg** [comment]
The sample app having this error is at https://github.com/TonyGregg/mini-social-app

**Comment by sovushka-utrom** [comment]
Looks like this one is about the same problem: https://github.com/okta/okta-oidc-js/issues/627

**Comment by swiftone** [comment]
Internal ref: OKTA-267793

**Comment by swiftone** [comment]
`@okta/okta-angular` v1.3.1 has been released that should fix support for AOT compilation (it also supports Angular 9).  Props to @aarongranick-okta for prioritizing and fixing the issue.  

@TonyGregg / @sovushka-utrom - Can you check to see if this update corrects the problems you were running into?

**Comment by sovushka-utrom** [comment]
Yes, it's fine now, `"@angular/core": "^9.0.0-rc.7"` & `"@okta/okta-angular": "~1.3.1"`.
Thank you for fixing it so fast, good job!

**Comment by TonyGregg** [comment]
Yes, it is fixed. Thanks.
