### ISSUE TITLE
React Native package login() does not opens the browser

### ISSUE THREAD

**Issue by mwss1996** [okta/okta-oidc-js#641]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

I have tried to use the package in my app and also tried using the provided example. But the login() function does not opens the browser to fill the login form. Also, no error message is printed on the console.

There are a existing discussion on the forum about this issue with more cases: https://devforum.okta.com/t/react-native-client-sdk-samples-not-working/6852/5

## Expected behavior

Open the browser for fill the login form.

## Environment

- Package Version: "@okta/okta-react-native": "^1.3.0"
- OS: Android AVD emulator api level 28
- Node version (`node -v`): v13.3.0

**Comment by swiftone** [comment]
Thanks for the report @mwss1996 - We'll need to find time to reproduce with your Android/node/SDK version combination

**Comment by Rajesh071** [comment]
It should match the auth redirect url for example redirectUri: 'com.okta.dev-686719

So in your project under android/forgotname.gradle you should add same config

redirectUri: 'com.okta.dev-686719

**Comment by swiftone** [comment]
Thanks for the assist @Rajesh071.  @mwss1996 - does this resolve your issue?

**Comment by mwss1996** [comment]
@swiftone I can't check it now because I am working on another project at the moment. But I will check it as soon as I have the time for that.

**Comment by swiftone** [comment]
Closing ticket as presumed fixed by config change.  If that is not the case, feel free to reopen with details.
