### ISSUE TITLE
Okta Angular 1.3.0 doesn't work with Angular 9.0

### ISSUE THREAD

**Issue by mraible** [okta/okta-oidc-js#643]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [x] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

If you use OktaDev Schematics to install Okta Angular 1.3.0 in a new Angular 9.0 RC7 (or RC5) app, it fails to compile.

```
ERROR in node_modules/@okta/okta-angular/dist/src/okta/okta.module.d.ts:3:22 - error TS-996002: 
  Appears in the NgModule.imports of AuthRoutingModule, but could not be resolved to an NgModule class

3 export declare class OktaAuthModule {
                       ~~~~~~~~~~~~~~
src/app/auth-routing.module.ts:45:14 - error TS-996002: 
  Appears in the NgModule.imports of AppModule, but itself has errors

45 export class AuthRoutingModule { }
                ~~~~~~~~~~~~~~~~~
```

## Expected behavior

I expect everything to compile and work out-of-the-box.

## Minimal reproduction of the problem with instructions

1. Install Angular CLI and create a new app

        npm install -g @angular/cli@9.0.0-rc.7
        ng new notes --routing --style css

2. Create a SPA app on Okta and change the login redirect URI to:

        http://localhost:4200/implicit/callback

3. Use OktaDev Schematics to install the Okta Angular SDK

        ng add @oktadev/schematics --issuer=$issuer --clientId=$clientId

4. Run `ng serve -o` and you'll see the error mentioned above.

## Extra information about the use case/user story you are trying to implement

If I downgrade to `@okta/okta-angular@1.2.2`, everything works.

## Environment

- Package Version: Okta Angular 1.3.0
- Browser: Chrome 79.0.3945.88
- OS: macOS Catalina
- Node version (`node -v`): v12.13.0
- Other:

**Comment by swiftone** [comment]
Internal ref: OKTA-269859

**Comment by swiftone** [comment]
`@okta/okta-angular` v1.3.1 has been released that adds support for Angular 9.

**Comment by mraible** [comment]
I can confirm that this is fixed. Thanks!
