### ISSUE TITLE
[REACT-NATIVE] signUp method

### ISSUE THREAD

**Issue by bsehovac** [okta/okta-oidc-js#650]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [x] Feature request
- [ ] Other (Describe below)

## Current behavior

No method for opening signUp page directly.

## Expected behavior

To have method which will open signUp page directly.

## Extra information about the use case/user story you are trying to implement

Since we can use custom login page in rn following this example [okta/samples-js-react-native/custom-sign-in](https://github.com/okta/samples-js-react-native/tree/master/custom-sign-in), we need a method which will open signUp page directly, instead of currently available signIn only option.

**Comment by robertjd** [comment]
Hi @bsehovac , can you clarify what you mean by "a method which will open signUp page directly" ?

Is the [browser login sample](https://github.com/okta/samples-js-react-native/tree/master/browser-sign-in) not what you need?

**Comment by swiftone** [comment]
Closing due to lack of response.  If you continue to have problems, feel free to reopen the issue with details.
