### ISSUE TITLE
How to handle MFA workflow with custom-ui in my react-native app ?

### ISSUE THREAD

**Issue by kuldip9060** [okta/okta-oidc-js#652]
## I'm submitting this issue for the package(s):
- [ ] okta-react-native

## Current behavior
I would like to use MFA(Mutifactor authentication flow using **Okta verify**) in react native app. 
Working fine with **Browser Sing-in** but I don't understand how it'll work and workflow with **Custom-UI**

## Expected behavior
**Login screen should be in Custom-UI** and MFA work flow should be in same as work like Browser Sign-in.

## Extra information about the use case/user story you are trying to implement
App flow is working fine without unable MFA rule.
Getting Error after enable MFA(Mutifactor authentication flow using **Okta verify**) rule : ERROR: "{"error message" : "Unable to get authorisation code.","error_code":"-600"}" 

## Environment
- Browser: React Native App
- React native version : >60.0

**Comment by swiftone** [comment]
Hi @kuldip9060 - Specific questions are better sent to either our forums (https://devforum.okta.com/) or by contacting our support team (developers@okta.com).

If you have feature requests or bugs to report we're happy (well, you know, interested.  No one is happy to hear about bugs.) to take them here.
