### ISSUE TITLE
Keys are invalid. Failed to obtain information about private key

### ISSUE THREAD

**Issue by jdnichollsc** [okta/okta-oidc-js#653]
## I'm submitting this issue for the package(s):
- [x] okta-react-native

## I'm submitting a:

- [x] Bug report

## Current behavior
Getting an error `Keys are invalid. Failed to obtain information about private key` when [authenticate](https://www.npmjs.com/package/@okta/okta-react-native#authenticate) function is executed from Android simulator, it works from iOS (simulator and device) and Android devices.

<img width="490" alt="Screenshot" src="https://user-images.githubusercontent.com/2154886/73077307-eca88780-3e8d-11ea-95c6-bbd66aaadbce.png">

## Expected behavior
Be able to authenticate the users by using `authenticate` function of `okta-react-native` package

## Minimal reproduction of the problem with instructions
Opening an Android emulator like Pixel 2 API 27 from Android Virtual Device Manager.

## Environment

- Package Version: "@okta/okta-react-native": "^1.3.0"
- OS: macOS Mojave
- Node version (`node -v`): v10.15.3
- Other: "@okta/okta-auth-js": "^2.11.0"

**Comment by FeiChen-okta** [comment]
Hi @jdnichollsc Android Emulators does not support hardware keystore. So you'll have to do a check to see if the device you are running the app on is an emulator. Please see:
https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react-native#createconfig

and set `requireHardwareBackedKeyStore: true` to false if it is running on the emulator

**Comment by swiftone** [comment]
Closing as this appears to be resolved.  If you continue to have this issue, please open a new ticket with details.
