### ISSUE TITLE
AuthSdkError: Unable to retrieve OAuth redirect params cookie, okta-react, Firefox with PKCE

### ISSUE THREAD

**Issue by MassivDash** [okta/okta-oidc-js#654]
# I'm submitting this issue for the package(s):

- [x] okta-react

## I'm submitting a:

- [x] Bug report  

## Current behavior

I am trying to establish an auth flow with PKCE using the latest @okta-react package (1.3.1).
I've managed to get things going on 
1. Chrome
2. Edge 
3. IE11 (with pollyfills)
4. Brave

**However Firefox (71) and FF dev edition (73) does not 'let me in' and shows "AuthSdkError: Unable to retrieve OAuth redirect params cookie" error.** 

This happens after validation through okta during redirect back to the site. Other browsers work fine, even the IE 11 with pollyfills works as expected. 

Tried clearing the cache,  removing all history, using a new computer that did not have any connection to okta whatsoever, using incognito mode. 

At this point, I am a little lost and out of ideas. 

## Expected behavior

Okta redirects to the website as other browsers. 

## Minimal reproduction of the problem with instructions

Using the Security component with pkce={true} prop and trying to login with Firefox   

## Environment
Firefox fails to login on 
Win 10, FF 71 and FF dev 73 
Centos 08, FF dev 73

**Comment by swiftone** [comment]
@MassivDash - Thanks for the report.  We had an issue with cookies on firefox/safari when using @okta/okta-auth-js v2.12.0 (okta-auth-js is a dependency of okta-react).  This issue was fixed in okta-auth-js v2.12.1

Can you check to see if you are running with okta-auth-js v2.12.1 or higher?  If not, can you check to see if updating that corrects the issue?

**Comment by MassivDash** [comment]
Reinstalling okta package have solved the issue. Thanks for this recommendation. Case closed
