### ISSUE TITLE
`auth.getUser` (from `withAuth`) returns `undefined` if called immediately after sign in

### ISSUE THREAD

**Issue by vmaharajh** [okta/okta-oidc-js#656]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
I'm running into some timing issues using the `auth` props provided by `withAuth`.

I use the following to fetch the user and access token from `auth`:

```tsx
    const [user, setUser] = useState<any>();

    useEffect(() => {
      if (props.auth) {
        props.auth.getUser().then(setUser);
      }
    }, [props.auth]);
```

In most cases this works as expected (`setUser` is called with a valid value).

However in the case where my user has just logged in, and is redirected back to my app, `setUser` is called with `undefined`. `auth.getUser` is resolving _successfully_ with an `undefined` value.  In the network tab of F12 dev tools, I don't even see a call to the `/userinfo` endpoint. If I use `setTimeout` to retry in 100ms, the subsequent call succeeds (with the same `auth` object) (and I see a corresponding call to the `/userinfo` endpoint).

## Expected behavior
`auth.getUser` should resolve successfully with a valid user object.

## Minimal reproduction of the problem with instructions
1) Use withAuth to access `auth`, and as soon as it is provided, try to call `getUser`. (A react context provider is a realistic scenario for this (see code below)).
2) Log out the user from the app
3) Log back in, and ensure that the redirect goes to a page that uses the `withAuth` component from step 1)

Here's the code that I'm using for step 1

```tsx
import React from "react";
import { withAuth } from "@okta/okta-react";
import { PropsWithChildren, useState, useEffect } from "react";
import { Auth, AuthContext } from "./Auth";

export interface AuthProviderProps {
  // Injected by withAuth
  auth?: any;
}

/**
 * Injects an `Auth` object in the react context
 */
export const AuthProvider = withAuth(
  (props: PropsWithChildren<AuthProviderProps>) => {
    const [user, setUser] = useState<any>();
    const [accessToken, setAccessToken] = useState<string>();

    const getValue = (): Auth => {
      const result: Auth = {};
      if (user) {
        result.user = { ...user };
      }
      if (accessToken) {
        result.bearerToken = `Bearer ${accessToken}`;
      }
      return result;
    };

    useEffect(() => {
      if (props.auth) {
        props.auth.getUser().then(setUser);
        props.auth.getAccessToken().then(setAccessToken);
      }
    }, [props.auth]);

    return (
      <AuthContext.Provider value={getValue()}>
        {props.children}
      </AuthContext.Provider>
    );
  }
);
```

## Extra information about the use case/user story you are trying to implement
I want to display the user name in my website's header. 
I want to create a react context API provider that injects any component with auth information (eg. the header described above).

## Environment

- Package Version: 1.3.1
- Browser: Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- OS: Windows 10 (1809 OS Build 17763.973)
- Node version (`node -v`): N/A

**Comment by swiftone** [comment]
Thanks for the report @vmaharajh - 

We'll dig into this one, but we have WIP right now to improve our React Hooks integration, so hopefully things will improve soon.

Meanwhile, I'm not sure the approach here will work out for you.  `useEffect` here is triggering some checks, but it will only re-run if props.auth changes...and it will only change once.  This means the first run the async call hasn't finished (useEffect is synchronous), so you're seeing the behavior you describe.

If you have an immediate need, I'd suggest having a `useEffect` call that calls auth.isAuthenticated() AND not passing any limitation params (so the useEffect() is called on every render).

Otherwise we'll work to get the React Hooks updates out to you Soon™️

**Comment by vmaharajh** [comment]
Excited to see the hooks work.

I tried your suggestion, but saw the same repro:

````tsx
    useEffect(() => {
      if (props.auth) {
        props.auth.isAuthenticated().then(() => {
          props.auth.getUser().then(setUser);
          props.auth.getAccessToken().then(setAccessToken);
        });
      }
    }, [props.auth]);
````

It still gets undefined for both `getUser` and `getAccessToken`. 

Since the hooks work may fix it, I can live with my polling + timeout workaround. Looking forward to trying it. 

Not really related, but I left `[props.auth]` in the `useEffect` because the linter (correctly) tells me that my code depends on it, so I should be updating it whenever it changes. You and I know that it won't ever change after the 1st time, but the linter doesn't, and no harm is done, so I left it in.

**Comment by mahearn** [comment]
@vmaharajh - I'd like to make use of your code, as I"m having problems with the code provided in the okta docs (I'm also using functional components and hooks). Can you please share your Auth,js file? TIA

**Comment by vmaharajh** [comment]
@mahearn here are GitHub gists for all of my okta helpers

[Auth.ts](https://gist.github.com/vmaharajh/44e59619f7674a54326e3d653a16e3a0)
[AuthProvider.tsx](https://gist.github.com/vmaharajh/0f40bbea61de2e325c430c39e16a4722)
[waitForAuth.tsx](https://gist.github.com/vmaharajh/240834534cdd0920bf953460477e40c2)

**Comment by mahearn** [comment]
Thanks for your help!


*Michael Ahearn MACS CP*
*Web Developer | Agile PM*
*Mob: 0420 850 400*
LinkedIn profile <http://au.linkedin.com/in/mdawebdevelopment>

**Comment by vmaharajh** [comment]
@swiftone Works like a charm, and I like being able to use a hooks over an HOC. Thank you!

````ts
/**
 * Injects an `Auth` object in the react context
 */
export const AuthProvider: React.FC<PropsWithChildren<{}>> = props => {
  const oktaAuth = useOktaAuth();
  const [user, setUser] = useState<any>();

  const getValue = (): Auth => {
    const result: Auth = {};
    if (user) {
      result.user = { ...user };
    }
    if (!oktaAuth.authState.isPending) {
      result.accessToken = oktaAuth.authState.accessToken;
    }
    return result;
  };

  useEffect(() => {
    if (!oktaAuth.authState.isPending) {
      oktaAuth.authService.getUser().then((x: any) => setUser(x));
    }
  }, [oktaAuth]);

  return (
    <AuthContext.Provider value={getValue()}>
      {props.children}
    </AuthContext.Provider>
  );
};
````

**Comment by aarongranick-okta** [comment]
@vmaharajh We're glad the updates are working well for you! The original problem may have been due to a race with `handleAuthentication()` which is usually called by the callback component. It takes a small amount of time to process the tokens returned from the server and place them into local storage. After the callback is handled, there is another redirect, either to your app root or the path protected by a `<SecureRoute>`, if that is what initiated the login. If the login redirect URI is set to `/` there may be no second redirect and we would expect these types of problems, at least with the previous version of `okta-react`. This is why we recommend having the callback on a dedicated route.
