### ISSUE TITLE
ɵɵdefineInjectable not a function- Issue in okta-angular.umd.js file after installing package

### ISSUE THREAD

**Issue by dineshpvs** [okta/okta-oidc-js#657]
While writing test cases for a component, we imported 
import { OktaAuthService } from '@okta/okta-angular';

While executing the test cases we are getting core.ɵɵdefineInjectable is not a function error.
Verified okta-angular.umd.js file under node_modules/@okta/okta-angular/bundles/okta-angular.umd.js and identified below code:
core["ɵɵdefineInjectable"] and core["ɵɵinject"]. After removing "ɵɵ" from the file, it started working. Please look into this issue.

**Comment by dineshpvs** [comment]
1. npm install -S @angular/material @angular/cdk @angular/animations
2. npm uninstall @angular/core
3. npm install -S @angular/core

Follow these three steps and it will resolve the issue.

**Comment by swiftone** [comment]
@dineshpvs - Thanks for the report and the fix!  Sounds like there is nothing for us to do on our side, just an upgrade issue. 

Let me know if I've misunderstood you.

**Comment by dineshpvs** [comment]
It is working for angular 8 version but facing same issue in angular 7 version. Can you look into this issue?

**Comment by bretterer** [comment]
@dineshpvs - Thanks for the update. We will investigate angular 7 and get back to you.

internal ref: OKTA-278075

**Comment by AndriiDovhopolov-okta** [comment]
@dineshpvs , hi! 

I was not able to reproduce bug using fresh installation of Angular 7.2 and playing around writing tests for component. 

Probably, your issue could be related to Angular's renaming of properties `defineInjectable` and `ɵɵdefineInjectable` which happened several times back and forth while Angular was switching version from 6 to 7 and then to 8. 

Best solution will be to upgrade to Angular 8, and it should do the trick.

**Comment by aarongranick-okta** [comment]
@dineshpvs We have released a new version of `okta-angular` (2.2.1) which is built using Angular 7. This should make it compatible with Angular 7 apps.
