### ISSUE TITLE
SameSite cookies warning in Chrome

### ISSUE THREAD

**Issue by sovushka-utrom** [okta/okta-oidc-js#658]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [x] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [x] Feature request
- [x] Other (Describe below)

## Current behavior

It's an information request and optionally a feature request.

First, we see now this warning in Google Chrome right after we get the access token from Okta : 

> A cookie associated with a cross-site resource at {okta domain} was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

In GoogleChrome 80 beta:

> A cookie associated with a cross-site resource at {okta domain}  was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Confirmed also by Okta mail: 

> Chrome 80 browser that will be released in February 4, 2020 will introduce changes that affect the handling of cross-site cookies. This upcoming change may prevent your users from signing to applications that do not have the proper compatibly. Okta has already verified that its cookies are compatible with this change, however, it’s important to ensure that your applications are compliant to avoid any disruptions to your SSO experiences.
>  
> Impacts
> When Google officially releases Chrome 80, cookies will be treated as same-site by default. For cross-site cookies to work, they must be explicitly labeled with the SameSite=None attribute (see SameSite Updates for details)
>  
> In these configurations, users will not be able to sign in directly to the app using an SP-initiated login flow (initiate the login from the app URL – the most common use cases).
> 
> •	If you are impacted or in case of an issue: Mark the affected cookies as SameSite=None if possible. Please refer to SameSite cookie recipes for better guidance on how to implement a fix for your use case

Despite the warning, I can still log into the application. What is the impact though? Can we do something from our side or should the change be done in okta-angular package?

## Expected behavior

Affected cookies should be marked as SameSite=None.

## Minimal reproduction of the problem with instructions

*STEPS TO REPRODUCE*
1. Open an application using okta-angular in Chrome.
2. Open the devtools console.
2. Log in.

## Environment

- Package Version:    
    "@angular/cdk": "8.0.0",    
    "@okta/okta-auth-js": "^2.11.0",
    "@okta/okta-angular": "1.2.2",
    "@okta/okta-signin-widget": "3.4.2",
- Browser: Google Chrome Version 79.0.3945.79 (64 bits) & Version 80.0.3987.16 beta (64 bits)
- OS: Window 10
- Node version (`node -v`): v10.14.1
- Other: -

**Comment by swiftone** [comment]
Hi @sovushka-utrom!  

We've released an update of @okta/okta-auth-js that updates the settings for cookies set by our library (https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-2.12.1).  You didn't mention what versions of the packages are actually installed (check your `package-lock.json`(for npm) or `yarn.lock` (for yarn) or just look in `node_modules/@okta/okta-auth-js/package.json`) so I can't say if you have this update or not.

The impact of the change can vary, but the most likely result will be an "AuthSdkError: Unable to retrieve OAuth redirect params cookie" error and failed login, as described in this (fixed) issue: https://github.com/okta/okta-oidc-js/issues/654

Hope that helps, let us know if that didn't answer your questions.

**Comment by swiftone** [comment]
Correction: Chrome soon will default to Lax, which is the value we set explicitly in the newer code.  Chrome also does not apply these restrictions to JS-usage, which is how our libraries are using them.  This means the Chrome release should have no impact, even without our newer changes (outside of the warning messages you are seeing).  

Firefox and Safari follow different rules, but they are not yet making these changes.  Our newer code SHOULD handle changes in those browsers as well, unless they change the rules dramatically between now and whenever they release changes.

Hope that helps, sorry for any confusion.

**Comment by sovushka-utrom** [comment]
Hi!
We were on 2.11.0, after switching to 2.13.0 the warning message is still here. Well, in the very last 80beta version of Chrome it still says that 
> Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`

but I'm able to login without any problem. So as no restrictions are applied to libraries calls, we'll just ignore the warning.
Thank you for such a detailed reply, it was really helpful.
