### ISSUE TITLE
Add Type Definitions to okta-react so it can be easily be used in a TypeScript project

### ISSUE THREAD

**Issue by mraible** [okta/okta-oidc-js#66]
More info: https://www.thepolyglotdeveloper.com/2016/05/add-type-definitions-external-javascript-library-typescript/

**Comment by tjpeden** [comment]
@mraible Angular folks need this too. 👍

**Comment by nbankin** [comment]
Express folks need this too. 👍

**Comment by robertjd** [comment]
Hi all, thanks for the requests!  I certainly love typescript :)  Some questions: I assume you're using VS Code?  If so, I wonder if JsDoc annotations can also serve us well?  I ask because it "feels like" VS Code has been getting better at giving intellisense based on those annotations (but maybe I'm imaging things).

**Comment by miguelarca** [comment]
Any news on getting the Type Definitions yet? I am trying to use it with react and typescript but no luck.

**Comment by tsiq-swyx** [comment]
me too

**Comment by mraible** [comment]
Here's a blog post that shows you how to use okta-react with Create React App and TypeScript: https://developer.okta.com/blog/2017/12/06/bootiful-development-with-spring-boot-and-react

Steps after installing okta-react:

```
yarn add -D @types/react-router-dom@4.2.6
```

You'll get an error when you try to import/use any Okta classes:

```
Could not find a declaration file for module '@okta/okta-react'.
```

Create `src/okta.d.ts` with the following declaration to solve this problem:

```
declare module '@okta/okta-react';
```

Hope this helps!

**Comment by tsiq-swyx** [comment]
wow. surprised its that easy. thanks!

**Comment by robertjd** [comment]
Hi everyone, thank you for your thoughts.  We've discussed this and have decided that Typescript should get some first-party support from us, so we will start working it into our roadmap.  Continue to watch this issue for updates.  Thanks!

**Comment by royt-via** [comment]
hi @robertjd @chrismorris-okta 
do you have any updates about this issue?

**Comment by swiftone** [comment]
@royt-via You can see one of the PRs in the works over at auth-js, which is a dependency of all the front end SDKs (react/vue/angular): https://github.com/okta/okta-auth-js/pull/413

**Comment by mraible** [comment]
TypeScript support was added to Okta React in its v4.0 release. https://github.com/oktadeveloper/schematics/releases/tag/v3.1.0
