### ISSUE TITLE
Include ES modules bundle in released package

### ISSUE THREAD

**Issue by shuowu-okta** [okta/okta-oidc-js#666]
## I'm submitting this issue for the package(s):

- [x] jwt-verifier
- [ ] okta-angular
- [x] oidc-middleware
- [x] okta-react
- [x] okta-react-native
- [x] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [ ] Feature request
- [x] Other (Describe below)

## Current behavior

Currently, only pkg.main field is included in `package.json` file in each sub packages, which make modern bundlers, like `webpack`, `rollup`, cannot take advantage of es module features.

## Expected behavior

1. Include pkg.module in each sub packages' package.json file 
2. Generate ES module related folder under `dist` folder to indicate location of bundled es6 modules.
3. Include ES module bundle in release package, like `dist/es/index.js`.

## Extra information about the use case/user story you are trying to implement

Make modules bundles can fully take advantage of ES module's feature to apply proper optimization, such as tree shaking.

## Environment

- Package Version:
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by bretterer** [comment]
Internal Ref: OKTA-278076
