### ISSUE TITLE
Deprecated packages

### ISSUE THREAD

**Issue by ashleym1972** [okta/okta-oidc-js#668]
## I'm submitting this issue for the package(s):

- [x] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

## Expected behavior
No deprecated packages

## Environment

- Package Version: 1.0.0
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by bretterer** [comment]
@ashleym1972 - Thank you for your report. We will take a look at our jwt-verifier to make sure that we get rid of the deprecated packages. 

Do these deprecation messages block you in any way with your project?

internal ref: OKTA-278077

**Comment by aarongranick-okta** [comment]
Closing issue as deprecated packages have been upgraded/removed.
