### ISSUE TITLE
@okta\okta-angular unable to use OKTA_CONFIG from Provider Factory

### ISSUE THREAD

**Issue by elbean** [okta/okta-oidc-js#670]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [x] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
Setting up a Provider for OKTA_CONFIG with useFactory results in an error that the config properties could not be found.
`{ provide: OKTA_CONFIG, useFactory: getOidc, deps: [RuntimeConfigService], multi: true }`

## Expected behavior
Injected OKTA_CONFIG is parsed and used to configure the OktaAuthModule.

## Minimal reproduction of the problem with instructions
Configure a Provider as a factory instead of value.  The injected OKTA_CONFIG is an array of the OKTA_CONFIG object.
Config cannot be parsed and an error is shown in console: `Error: Your Okta URL is missing....` 

app.module.ts
```
...
export function initializeApp(config: RuntimeConfigService) {
  return () => config.load();
}

export function getOidc(config: RuntimeConfigService) {
  return () => config.getOidcConfig();
}
...
...
providers: [
    RuntimeConfigService,
    { provide: APP_INITIALIZER, useFactory: initializeApp, deps: [RuntimeConfigService], multi: true },
    { provide: OKTA_CONFIG, useFactory: getOidc, deps: [RuntimeConfigService], multi: true }
  ],
...
```
runtime-config.service.ts
```

export interface IOidcConfig {
  pkce: boolean,
  issuer: string,
  redirectUri: string,
  clientId: string,
  scopes: string[],
  tokenManager: {
    storage: string,
    secure: string,
    autoRenew: boolean
  }
}

export interface IAppConfig {

  production: boolean

  oidc: IOidcConfig
}

@Injectable({
  providedIn: 'root'
})
export class RuntimeConfigService {
  private _appConfig: IAppConfig;

  constructor(private http: HttpClient) {
  }

  load() {
    const jsonFile = `assets/config.json`;

    return this.http.get(jsonFile)
      .pipe(
        tap((returnedConfig: IAppConfig) => {
          console.log('returnedConfig', returnedConfig);
          this._appConfig = returnedConfig;
        })
      )
      .toPromise();
  }

  public getOidcConfig() {
    return this._appConfig.oidc;
  }
}
```

OKTA_CONFIG dependency is received as Array of one object of IAppConfig.

## Extra information about the use case/user story you are trying to implement
Supporting dynamic configuration from an external configuration provider.

## Environment

- Package Version: 1.4.0
- Browser: Chrome 79.0.3945.130
- OS: Windows 10
- Node version (`node -v`): 12.13.1
- Other: Angular 8.2.14

**Comment by bretterer** [comment]
@elbean - Thank you for your issue and related PR to our repo. We are happy to look into this one, but it appears the library is working as expected. 

Looking at your example, you have the `multi` property set to be `true`. The library would expect this to be set as `false`. If you update your use case to be `false` does this fix your reported issue? Is there a use case that we are not seeing that would require you to use `multi: true`?

Please let us know and we can further help you with your reported issue.

**Comment by elbean** [comment]
@bretterer - Thank you for the response.  Setting `multi: false` does allow the library to function correctly.
