### ISSUE TITLE
[Angular] okta Login not working if using hash - Angular Route { useHash: true } 

### ISSUE THREAD

**Issue by dudumanbogdan** [okta/okta-oidc-js#672]
## I'm submitting this issue for the package(s):

- [X ] okta-angular

## I'm submitting a:

- [X ] Bug report  

## Current behavior
Login does not work:
`10:39:16.347 core.js:6014 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'code'
Error: Cannot match any routes. URL Segment: 'code'
    at ApplyRedirects.noMatchError (router.js:4295)`

Because of this, I don't see anymore a POST call to /token, after the implicit/callback GET endpoint.

## Expected behavior
Okta Angular library should handle this.
Login should work if { useHash: true }.

## Minimal reproduction of the problem with instructions
Setup okta angular + configs for a new Angular application. Used Angular 8.
In app-routing.module.ts, set:
`  imports: [RouterModule.forRoot(routes, { useHash: true })]`

## Extra information about the use case/user story you are trying to implement
Works as expected if **useHash: false** but this is not an option for us, as we have a PROD application which will need to use Okta instead of current implementation Cognito, AWS.

Searching more I observed the issue was mentioned also on the Forum but with no feedback: 
https://devforum.okta.com/t/configuring-the-angular-router-to-usehash-true-breaks-oktaauthservice-loginredirect/7374

**Comment by bretterer** [comment]
@dudumanbogdan - When using the response mode `fragment` this is expected. This is the default response mode.

If you are using PKCE, you can use the [responseMode `query`](https://github.com/okta/okta-auth-js#additional-options) and this should resolve the issue.  

Also, make sure that you are using the latest version of the [auth-js library, version 2.13.0](https://github.com/okta/okta-auth-js/releases/tag/2.13.0)

If this does not solve your issue, please come back with some more information so we can help further.

**Comment by dudumanbogdan** [comment]
Hi @bretterer ,  thanks for the quick reply.
I didn't . saw the "responseMode": "query"

Changing as you have mentioned does not thrown anymore an error but I don't get anymore a POST REST call to /token done by the library (calling the, after the REST GET /implicit/callback?=code....

Thus, I don't have the Token in LocalStorage or infos about the user: await this.okta.getAccessToken(), await this.okta.getUser(), await this.okta.isAuthenticated()). All are undefined.

I reproduce the problem:
1. if I use JS library,  auth-js library, version 2.13.0 by following Tutorial https://developer.okta.com/code/angular/okta_angular_auth_js/
2. and also with using okta-angular package, latest version

I want to mention that for both options, if I use "useHash: false", the login works and I get the POST to token. Everything looks good.

Any ideas what can be wrong, as I don't have anymore any errors but no Token POST call?

**Comment by dudumanbogdan** [comment]
I have managed to fix my problem and works well with "useHash: true".

What I did extra was on login method to use something like this:
`    this.oktaAuth.token.getWithRedirect({
      scopes: ["openid", "email"],
      responseMode: "query",
      responseType: "token"
    });`

and from ctor - AppRouting:
`  this.oktaAuth.token
      .parseFromUrl()
      .then(tokenOrTokens => {
        // manage token or tokens
        tokenOrTokens.forEach(token => {
          if (token.idToken) {
            this.oktaAuth.tokenManager.add("idToken", token);
          }
          if (token.accessToken) {
            this.oktaAuth.tokenManager.add("accessToken", token);
          }
        });` 

to set the tokens. After, I can use the tokenManager to verify if user is logged or if it has a token via a custom Guard. 
The refresh token works as well ok!

Thanks again for the help! I think it can be marked as resolved / closed the issue.
