### ISSUE TITLE
Okta React  - How to use OAuth 2.0 Authorization Code Flow?

### ISSUE THREAD

**Issue by kPOWz** [okta/okta-oidc-js#673]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [ ] Feature request
- [x] Other (Describe below)
Question

## Current behavior
From README :
>This library currently supports:
>OAuth 2.0 Implicit Flow
>OAuth 2.0 Authorization Code Flow
>Proof Key for Code Exchange (PKCE)

I see how (and have used) Implicit flow & PKCE via this library, but don't see examples for Authorization Code flow - is it definitely supported?

If so, how does the `<Security>` component get used/configured?

## Expected behavior
A brief example of which components and/or interfaces are needed to do "OAuth 2.0 Authorization Code Flow" using the @okta/react module

**Comment by swiftone** [comment]
@kPOWz - Using Authorization Code Flow with PKCE is the recommended way to handle a SPA.  If you are using Authorization Code Flow WITHOUT PKCE, you're handling authorization server-side.  The underlying AuthJS library does support this, but our `okta-react` package does not.

Are you trying to use Authorization Code Flow with PKCE, or are you trying to do your authorization server-side?

**Comment by kPOWz** [comment]
@swiftone  understood.

If that's the case, the [okta-react README](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react) is misleading at best.  

> This library currently supports:
> 
> OAuth 2.0 Implicit Flow
> OAuth 2.0 Authorization Code Flow
> Proof Key for Code Exchange (PKCE)

Clicking the second "supported" option,  'OAuth 2.0 Authorization Code Flow', takes you to the RFC for the server side authorization code flow.

**Comment by swiftone** [comment]
@kPOWz - We've revised the README with the okta-react 2.x release, however the RFC covers both the server and client portions, so we kept that link.  

Thanks for the feedback, hopefully fewer devs will misled or confused!
