### ISSUE TITLE
okta-react: ImplicitCallback component only works in ubuntu...

### ISSUE THREAD

**Issue by mrkchang** [okta/okta-oidc-js#674]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x ] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Everything works well in ubuntu in multiple browsers and multiple computers. But in windows, the /implicit/callback route with ImplicitCallback component doesn't do anything... The page stays blank.

I tried writing a customer implicit callback component to try to debug but the functions arent recognized (e.g. this.props.auth.getFromUri is not a function).

**Comment by dragosgaftoneanu** [comment]
This is in regards to isAuthenticated() intermittently returning null value.

**Comment by mrkchang** [comment]
Immediate support would be very much appreciated. This will delay my launch.

**Comment by mraible** [comment]
@mrkchang If it works on one machine, but not another, that's suspicious. Can you try on another Windows machine and see if the problem is reproducible? Are you using the same browser on Windows?

If this is an urgent issue, please email developers@okta.com to create a support ticket.

**Comment by mrkchang** [comment]
@mraible 
Hi, Yes, I have been able to replicate it across 2 machines with 3 different wifi networks. It is also intermittent. One morning it didnt work for 4+ hours, then worked in the evening. The next day, it didn't work at all. 

I was troubleshooting this with Dragos last night on ticket 00770251. He is very helpful, but unfortunately we were not able to diagnose it.

**Comment by swiftone** [comment]
@mrkchang - We have some upcoming changes that may help with this case.  In the meantime, can you share your `<Router>` config?   We're curious if you have multiple potential routes to ImplicitCallback.

In case it is helpful, `auth.getFromUri()` is destructive - once it is called the stored value is removed, so if it gets called multiple times, you will be left without a destination.  That might be related to your symptom, or it may be completely unrelated.

**Comment by dragosgaftoneanu** [comment]
@swiftone The issue was caused by an incorrect computer time. Adding the correct time on the computer resolved the issue.
