### ISSUE TITLE
Angular OktaAuthGuard not working in IE11

### ISSUE THREAD

**Issue by muscleman** [okta/okta-oidc-js#689]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [x] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
The Okta redirect to /implicit/callback does not seem to be working in IE11/Edge.
browser url stays at http://localhost:4200/implicit/callback after successfull auth with okta loging widget. no tokens.

## Expected behavior
user should visit my site, be redirected to Okta  then redirected back to my app after successful auth. this implicit flow with pkce works in chrome.

## Minimal reproduction of the problem with instructions
Create a new angular app. (ng new) and configure to work in IE11
Add @okta/okta-angular module
Import into app module.
Provide config:
provide: OKTA_CONFIG, useValue: { issuer: 'https://xxxx.okta.com', redirectUri: 'http://localhost//implicit/callback', clientId: '', scopes: ['openid', 'profile', 'email'], pkce: true}
add route implicit/callback
add a route protected by canActivate: [OktaAuthGuard]
add the following shims to polyfills.ts. 
   import 'webcrypto-shim/webcrypto-shim.js';
   import 'bluebird/js/browser/bluebird.js';
   import 'polyfill-array-includes';
ng serve

## Environment

Package Version: 1.4.0
Browser: IE11
OS: Windows 10
Node version (node -v): 10.15.3
Other: Angular version: 8.2.13

**Comment by aarongranick-okta** [comment]
@muscleman It is likely that you are missing a needed polyfill for IE. See notes here: https://github.com/okta/okta-auth-js#browser-compatibility

All of our modules include sourcemaps. It may also help in debugging the application to add the [source-map-loader](https://webpack.js.org/loaders/source-map-loader/) plugin to your webpack config.

There may be an uncaught exception / promise rejection from `handleAuthentication()`. In this case, we recommend copying the [ImplicitCallback component](https://github.com/okta/okta-oidc-js/blob/master/packages/okta-angular/src/okta/components/callback.component.ts) and modifying it by adding a `.catch()` block onto the call to `handleAuthentication`, then set the modified component on the `/implicit/callback` route.

**Comment by muscleman** [comment]
hi,

yeah using textencoder, promise and Array.from ain't working.

Do you have a working version i can use?

G.

________________________________

**Comment by muscleman** [comment]
actually with IE11 the first call to okta authorize endpoint just hangs.

this works fine in chrome.

________________________________

**Comment by muscleman** [comment]
so after successfully providing my details to a okta hosted widget and the mfa i'm redirected back to my app, where it dies on the authorized call.

following is whats displayed in the IE11 browser.

http://localhost:4200/implicit/callback#code=E_Hmf8zc2Iks4MxaLBoO&state=rjd6VPKeGl6EBFR0d4xcsKc79nTTKd0RVFlrYf3NAW4KEVGDLM0uDbjyJrrEyqin




________________________________

**Comment by swiftone** [comment]
Per the suggestion above, we suggest you copy the ImplicitCallback component and drop in additional debugging to see where the problem (likely uncaught exception) exists.

We've added this in the latest version (okta-angular 2.x) - let us know what error you see

**Comment by swiftone** [comment]
Closing this ticket as inactive - feel free to reopen with details.

**Comment by muscleman** [comment]
Yeah i wouldn't call this issue closed by and means. 
We ended up creating a browser agnostic c# api that implemented /authorize and /token and then put the returned tokens into a clients browser as a cookie.

then wrote angular authguards that expected token to be available and interceptor to pick up the token and construct the authorization header.

Real shame you guys could provide a working implementation. i liked that for chrome using your angular okta sdk took 30mins. 
however our client base is primarily IE and Edge. 
Maybe you guys should rethink your repo and provide this.

**Comment by polklabs** [comment]
This is still a very open issue. The only way I have gotten Okta to work on IE11 is to get the tokens without redirecting. But now I need to include MFA which is not included in the sign-in widget, forcing me to redirect to Okta. So either I can't use MFA or I can't use Internet Explorer, neither of which are really options.
