### ISSUE TITLE
Unable to get logged in user information

### ISSUE THREAD

**Issue by lawchihon** [okta/okta-oidc-js#691]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [X] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [X] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

When calling `oktaAuth.getUser()`, the return result only have `sub`

## Expected behavior

Should have other information, like `name`, `email`

## Minimal reproduction of the problem with instructions

Call `oktaAuth.getUser()` after logged in through okta

## Environment

- Package Version: 1.4.0
- Browser: Chrome
- OS: Mac
- Node version (`node -v`): v12.13.1
- Other:

**Comment by mraible** [comment]
You need to add profile as a scope to get more information.

**Comment by lawchihon** [comment]
> You need to add profile as a scope to get more information.
> […](#)
> On Mar 7, 2020, at 21:05, Chi Hon Law ***@***.***> wrote: ﻿ I'm submitting this issue for the package(s): jwt-verifier okta-angular oidc-middleware okta-react okta-react-native okta-vue I'm submitting a: Bug report Feature request Other (Describe below) Current behavior When calling oktaAuth.getUser(), the return result only have sub Expected behavior Should have other information, like name, email Minimal reproduction of the problem with instructions Call oktaAuth.getUser() after logged in through okta Extra information about the use case/user story you are trying to implement Environment Package Version: 1.4.0 Browser: Chrome OS: Mac Node version (node -v): v12.13.1 Other: — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Do you mean to add claim for the profile scope? I have added to include any scope, isnt that the same?

**Comment by mraible** [comment]
It's a setting you can pass to your Okta config. For example, `scopes: 'openid profile'`. See https://www.npmjs.com/package/@okta/okta-angular#okta_config for more information.

**Comment by lawchihon** [comment]
> It's a setting you can pass to your Okta config. For example, `scopes: 'openid profile'`. See https://www.npmjs.com/package/@okta/okta-angular#okta_config for more information.
Thanks! That's what I'm missing.
