### ISSUE TITLE
The modules ['@okta_okta-react-native', 'okta_okta-react-native'] point to the same directory in the file system. Each module must have a unique path.

### ISSUE THREAD

**Issue by JohnGom** [okta/okta-oidc-js#694]
I have this issue when i try run command react-native run-android: "The modules ['@okta_okta-react-native', 'okta_okta-react-native'] point to the same directory in the file system. Each module must have a unique path."

this module create two files .iml in it folder android, I think that it this the error

- [ ] okta-react-native

**Comment by swiftone** [comment]
Hi @JohnGom - We've not been able to reproduce your error and haven't heard other similar reports.  Can you tell us a bit more about how to reproduce the error?  Do you get this running our sample app? ( https://github.com/okta/samples-js-react-native )
