### ISSUE TITLE
LoginCallback triggers React error on failure: Objects are not valid as a React child

### ISSUE THREAD

**Issue by bcbee** [okta/okta-oidc-js#699]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [X] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [X] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

If the `LoginCallback` component encounters an error during authorization it improperly attempts to add an object to the React DOM triggering an exception.

## Expected behavior

Errors should be gracefully added to the DOM or console without exception.

## Minimal reproduction of the problem with instructions

1. Download https://github.com/okta/samples-js-react/tree/master/okta-hosted-login
2. Add testing `ISSUER` and `CLIENT_ID` environment variables
3. Run `npm i` and `npm start`
4. Navigate to http://localhost:8080/implicit/callback#id_token=123 (invalid token)
5. Open JS console and observe React internals error triggered within `LoginCallback` component

#### Console output:
[LoginCallbackBug-ConsoleOutput.log](https://github.com/okta/okta-oidc-js/files/4330866/LoginCallbackBug-ConsoleOutput.log)

#### Error message:

```
Error: Objects are not valid as a React child (found: object with keys {name, message, errorCode, errorSummary, errorLink, errorId, errorCauses}). If you meant to render a collection of children, use an array instead.
...
The above error occurred in the <p> component:
```

## Environment

- Package Version: okta-react 2.0.0
- Browser: Google Chrome 80.0.3987.132 (latest)
- OS: macOS Catalina 10.15.3
- Node version (`node -v`): v10.19.0
- Other:

**Comment by swiftone** [comment]
Internal ref: OKTA-282543

**Comment by rodrigowpl** [comment]
Same issue here

**Comment by daveed80** [comment]
@swiftone @rodrigowpl 

+1.... have you heard of any updates on this?

**Comment by swiftone** [comment]
We have a PR in the works: https://github.com/okta/okta-oidc-js/pull/700

**Comment by brettritter-okta** [comment]
After a mild fight with our CI system, `@okta/okta-react 2.0.1` has been released with this fix.  Thanks for your patience.

**Comment by daveed80** [comment]
Thanks much!
