### ISSUE TITLE
Error with scopes when trying to login

### ISSUE THREAD

**Issue by niskah-energies** [okta/okta-oidc-js#704]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ X] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [X ] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

I'm using a fresh angular install with `ng add @oktadev/schematics --issuer=$issuer --clientId=$clientId`
after install I run `ng serve`
and when I'm trying to login with button added by package it returns an error in console:
`[Error] ERROR – Error: Uncaught (in promise): TypeError: e.scopes.join is not a function. (In 'e.scopes.join(" ")', 'e.scopes.join' is undefined)
p@http://localhost:4200/vendor.js:65156:48698
h@http://localhost:4200/vendor.js:65156:48727
http://localhost:4200/vendor.js:65156:51733
onInvoke@http://localhost:4200/vendor.js:46505:39
run@http://localhost:4200/polyfills.js:137:53
http://localhost:4200/polyfills.js:864:43
onInvokeTask@http://localhost:4200/vendor.js:46483:43
runTask@http://localhost:4200/polyfills.js:181:61
drainMicroTaskQueue@http://localhost:4200/polyfills.js:583:46
promiseReactionJob@[native code]
Error: Uncaught (in promise): TypeError: e.scopes.join is not a function. (In 'e.scopes.join(" ")', 'e.scopes.join' is undefined)
p@http://localhost:4200/vendor.js:65156:48698
h@http://localhost:4200/vendor.js:65156:48727
http://localhost:4200/vendor.js:65156:51733
onInvoke@http://localhost:4200/vendor.js:46505:39
run@http://localhost:4200/polyfills.js:137:53
http://localhost:4200/polyfills.js:864:43
onInvokeTask@http://localhost:4200/vendor.js:46483:43
runTask@http://localhost:4200/polyfills.js:181:61
drainMicroTaskQueue@http://localhost:4200/polyfills.js:583:46
promiseReactionJob@[native code]
	defaultErrorLogger (vendor.js:14832)
	handleError (vendor.js:14885)
	next (vendor.js:47304)
	(fonction anonyme) (vendor.js:42832)
	__tryOrUnsub (vendor.js:71502)
	next (vendor.js:71441)
	_next (vendor.js:71391)
	next (vendor.js:71368)
	next (vendor.js:71154)
	emit (vendor.js:42794)
	run (polyfills.js:137)
	onHandleError (vendor.js:46542)
	runGuarded (polyfills.js:150)
	(fonction anonyme) (polyfills.js:684)
	drainMicroTaskQueue (polyfills.js:590)
	promiseReactionJob`

## Minimal reproduction of the problem with instructions

`ng add @oktadev/schematics --issuer=https://xxxxxxxxxxxx --clientId=xxxxxxxxxx`
`ng serve`
try to login using login button added by package in home controller

## Environment

- Package Version: "@okta/okta-angular": "2.0.0" and "@oktadev/schematics": "^1.5.1"
- Browser: Safari
- OS: OSX Mojave (10.14.6)
- Node version (`node -v`): 10.15.1
- Other:

**Comment by mraible** [comment]
This happens because Okta Angular 2.0 changed scopes from a string to an array. In `src/app/auth-routing.module.ts`, change the `scopes` variable from:

```json
scopes: 'openid profile',
```

To:

```json
scopes: ['openid', 'profile'],
```

I'll fix this in 1.5.2 of OktaDev Schematics.

**Comment by niskah-energies** [comment]
Thank you, it works.
