### ISSUE TITLE
ERROR: "The current page is not being served with the HTTPS protocol. For security reasons, we strongly recommend using HTTPS. If you cannot use HTTPS, set "cookies.secure" option to false."

### ISSUE THREAD

**Issue by iameduardod** [okta/okta-oidc-js#707]
"@okta/okta-angular": "^2.0.0",
    "@okta/okta-signin-widget": "^3.8.1",
    "@oktadev/schematics": "^1.5.2"

angular v9

Getting the following error on the console tab and my whole app refuses to load:
ERROR: "The current page is not being served with the HTTPS protocol. For security reasons, we strongly recommend using HTTPS. If you cannot use HTTPS, set "cookies.secure" option to false."

Here's my okta config object:
{
    issuer: 'https://_oktaDevDomain_.okta.com/oauth2/default',
    redirectUri: `${window.location.origin}/content/angular/en/callback.html`,
    clientId: _clientid_
    scopes: ['openid', 'profile'],
    pkce: false,
    tokenManager: {
      secure: false,
      storage: 'cookie'
    },
    disableHttpsCheck: true
  }

**Comment by iameduardod** [comment]
@swiftone @aarongranick-okta please help

**Comment by aarongranick-okta** [comment]
@iameduardod Is this happening for you on local testing (from your machine) or after deployed to a web server? For local testing you can use `http://localhost` Using HTTP with other origins will produce this error. To overcome this, you will need to set `cookies.secure` to false, like this:

```
{
   issuer: ....
   cookies: {
      secure: false
   }
  ....
}

**Comment by iameduardod** [comment]
that worked - thanks!
