### ISSUE TITLE
Login using okta gives :: ERROR Error: "Uncaught (in promise): AuthApiError 

### ISSUE THREAD

**Issue by navirai** [okta/okta-oidc-js#711]
ERROR Error: "Uncaught (in promise): AuthApiError
./node_modules/@okta/okta-auth-js/dist/okta-auth-js.min.js/</<@http://localhost:4200/vendor.js:90242:42693

## I'm submitting this issue for the package(s):
- [ ] okta-angular

## I'm submitting a:
- [ ] Bug report  

## Current behavior
Not able to login using okta 

## Environment

- Package Version:
    "@okta/okta-angular": "^2.0.0",
    "@okta/okta-auth-js": "^3.0.0",
- Browser: latest Chrome and latest FireFox
![oktaErrorPNG](https://user-images.githubusercontent.com/40883100/76867320-6146e380-688b-11ea-957d-7321426328f7.PNG)

![ErrorOnFireFox](https://user-images.githubusercontent.com/40883100/76867207-38265300-688b-11ea-97e4-1018f721f62f.PNG)

- OS: win 10
- Node version (`node -v`): v12.16.1

- Other:

**Comment by swiftone** [comment]
@navirai - Thanks for the report.  Could you run your example using the source maps loader webpack plugin so we can find the code responsible?

https://www.npmjs.com/package/source-map-loader

Many of our calls return promises with the expectation that you can catch the errors and handle them as you desire - odds are that is what you are encountering.

**Comment by navirai** [comment]
@swiftone Hi, could you please tell me how do i use source-map-loader , I am new to all this and I don't have much knowledge ?
for now, i have simply installed the npm and tried to run my application and i got same error.

**Comment by navirai** [comment]
@swiftone I made error while giving url in config for okta. oops
