### ISSUE TITLE
useOktaAuth() hook gives TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by jayjayzheng** [okta/okta-oidc-js#716]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

use the hook useOktaAuth() inside a function called LoginButton which is a link on a Header component. The index.js has the "Security" components. When using the vanilla okta-signin widget, it works fine. 

When the hook is used, it will cause error - TypeError: Object(...) is not a function. 
source code: 
```
import React from "react";
import { useOktaAuth } from "@okta/okta-react";

const LoginButton = () => {
  const { authService, authState } = useOktaAuth();

  const login = async () => {
    authService.login("/");
  };
  const logout = async () => {
    authService.logout("/");
  };

  if (authState.isPending) {
    return <div>Loading...</div>;
  }

  if (!authState.isAuthenticated) {
    return (
      <div>
        <button onClick={login}>Login</button>
      </div>
    );
  }

  return (
    <div>
      <button onClick={logout}>Logout</button>
    </div>
  );
};

export default LoginButton;
```

![image](https://user-images.githubusercontent.com/12238053/77504552-a55b5a80-6e2e-11ea-819b-b40964a64f3f.png)

![image](https://user-images.githubusercontent.com/12238053/77504569-b310e000-6e2e-11ea-8c42-400f034a2ad6.png)

## Environment

- Package Version: react 16.13, okta-react 1.4.1
- Browser: Chrome
- OS: mac 15
- Node version (`node -v`):
- Other:

**Comment by nharrisanalyst** [comment]
Why is this closed I am getting the same error here.
Shouldn't this be investigated?

**Comment by nharrisanalyst** [comment]
not even point the user to this article 
https://devforum.okta.com/t/okta-react-typeerror-object-is-not-a-function/8362/2

**Comment by nharrisanalyst** [comment]
Seems bad that the developers for Okta did not give any guidance on this problem especially since this is a commercial product. 

1. update to okta 3.0 
2. change withAuth to withOktaAuth
