### ISSUE TITLE
SecureRoute dont pass Router props to my component

### ISSUE THREAD

**Issue by LongJohnSilver1504** [okta/okta-oidc-js#724]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Router props like history for example are undefined in my secure component;
in Body component this line fix the problem:
` <SecureRoute path={r.path} component={withRouter(r.component)} exact={!!r.exact} key={r.path} />`
but this dont work:
`<SecureRoute path={r.path} component={r.component} exact={!!r.exact} key={r.path} />`

## Expected behavior

I need use props like history on my secure component

## Minimal reproduction of the problem with instructions

this is some of my code :
```JSX

import React from 'react';
import { BrowserRouter, Route, Switch } from 'react-router-dom';
....

const Body = () => (
  <>
      <Switch>
        {routes.map(r =>
          r.secure ? (
            // I think the SecureRouteComponent dont pass the router props
            <SecureRoute path={r.path} component={r.component} exact={!!r.exact} key={r.path} />
          ) : (
            <Route path={r.path} component={r.component} exact={!!r.exact} key={r.path} />
          )
        )}
      </Switch>
  </>
);

const AuthProvider = ({ children }) => (
  <Security
    issuer: 'https://{yourOktaDomain}.com/oauth2/default',
  clientId: '{clientId}',
  redirectUri: window.location.origin + '/implicit/callback',
  >
    {children}
  </Security>
);


const App = () => (
    <BrowserRouter basename={baseRoute}>
      <AuthProvider>
          <div>
            <Header />
            <Body />
            <Footer />
          </div>
      </AuthProvider>
    </BrowserRouter>
);
```

## Environment

- Package Version: 2.0.1
- Browser:Chrome
- OS:Windows 10
- Node version (`node -v`):v12.14.1
- Other:

**Comment by LongJohnSilver1504** [comment]
May be the SecureRouteComponent dont spread the Router props:
https://reacttraining.com/react-router/web/api/Route/render-func

**Comment by swiftone** [comment]
Internal ref: OKTA-288357

**Comment by vitalii-onyshchenko** [comment]
https://github.com/okta/okta-oidc-js/blob/367e8be52f0ef19af08e2a3f019d48a11992a718/packages/okta-react/src/SecureRoute.js#L44
Should be something like
`render={ (routeProps) => props.render ? props.render({...routeProps, component: WrappedComponent}) : <WrappedComponent {...routeProps} /> } `

**Comment by welljsjs** [comment]
Having the exact same issue on a production system. 

`render` passes the following props: 

```
component: function()
computedMatch: {path: "/...", url: "/...", isExact: true, params: {}}
location: {pathname: "/...", search: "", hash: "", state: undefined, key: "..."}
path: "/..."
render: function(props)
```

and `component` does not pass any props at all. 
This behavior was introduced after migrating to V2.

This is what is should be like: https://reacttraining.com/react-router/web/api/match

**Comment by jsatsvat** [comment]
Facing the same issue on a business-critical system.

We can't deploy our SPA unless authentication is working.
As we are currently migrating from v1 to v2, this is a major drawback for our current development process.
Your early attention to this would be appreciated.
We've requested business customer support. The case number is #00829207

**Comment by jsatsvat** [comment]
@vitalii-onyshchenko Almost got it, you still need to pass the `routeProps` to the `PassedComponent`. The following patch is working fine: 

```js
const SecureRoute = ( {component, ...props} ) => { 

  const PassedComponent = component || function() { return null; };
  const WrappedComponent = (props) => (<RequireAuth><PassedComponent {...props} /></RequireAuth>);
  return (
    <Route
      { ...props }
      render={ (routeProps) => props.render ? props.render({...routeProps, component: WrappedComponent}) : <WrappedComponent {...routeProps} /> } 
    />
  );
};
```

**Comment by swiftone** [comment]
Thanks to @vitalii-onyshchenko, @jsatsvat, and @vaughnderson-su2 for their diagnosis.  

We are now testing a fix for this ( #802 ) and hope to have it published soon.

**Comment by tcjcodes** [comment]
Hi, I'm still seeing this in `@okta/okta-react@3.0.2`, here's the component:

```jsx
const routeConfig = {
        exact: true,
        path: '/',
        render: () => <SearchPage />,
        requiresAuth: true,
    };

<SecureRoute key={routeConfig.path} {...routeConfig} />
```

But it successfully redirects when `render` is replaced by `component: { SearchPage }`

**Comment by pbollaram** [comment]
i have downloaded latest @okta-react v3.0.8 and i still not able to access routing props in my component.
code that i am using is below:
**<SecureRoute path="/notifications" component={Notifications} />**
and in my component i am just printing console.log(props) which is giving me output of empty object {}.

tried with withRouter as suggested by someone on above conversion log and i am still facing same issue.
<SecureRoute path="/notifications" component={withRouter(Notifications)} />
