### ISSUE TITLE
On iOS the onError event is triggered when the user cancels the Browser Sign In

### ISSUE THREAD

**Issue by NikolaMijovic93** [okta/okta-oidc-js#727]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

On iOS, canceling out the Browser Sign-In procedure results with the **'onError'** event being triggered instead of the 'onCancelled'. 
## Expected behavior

The onCancelled event to be triggered.

## Minimal reproduction of the problem with instructions

You can reproduce this on the sample app.

## Environment

- Package Version: 1.3.0
- Browser: N/A
- OS: iOS 13.2
- Node version (node -v): 10.16.3
- Other:

**Comment by swiftone** [comment]
Internal ref: OKTA-288356

**Comment by shuowu** [comment]
@NikolaMijovic93 As mentioned in `okta-react-native` README's [signIn](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react-native#signin) section. `onCancel` is a workaround event listener for iOS device.

**Comment by NikolaMijovic93** [comment]
Okay, so it's basically impossible to differentiate the two on iOS?

**Comment by swiftone** [comment]
@NikolaMijovic93 - Unfortunately, that is the current state on iOS. Per the README, onCancel will not fire on iOS.

**Comment by swiftone** [comment]
Closing as resolved as much as we can (iOS itself is outside our team)
