### ISSUE TITLE
Document token management strategy so it is clear what the developer gets by using these libraries

### ISSUE THREAD

**Issue by omgitstom** [okta/okta-oidc-js#74]
okta-auth-js supports silent authentication/silent refresh.  Let's have a good strategy around exposing this core functionality as part of the client-side sdks

**Comment by lboyette-okta** [comment]
The silent refresh is automatically handled for you in all our integrations using the `tokenManager`. This is abstracted away from the end-developer.

**Comment by nbarbettini** [comment]
This is primarily a documentation issue. [This section of the README](https://github.com/okta/okta-auth-js#tokenmanageraddkey-token) that explains that the `tokenManager` automatically handles refresh is buried far down the page and is easy to miss. It's more prominent in [the guide](https://developer.okta.com/code/javascript/okta_auth_sdk.html) but not everyone will look there.

My own anecdote: I recently used okta-auth-js heavily in a demo project, and I got 75% of the way through implementing my own refresh code before I realized okta-auth-js could do it for me. okta-auth-js worked really well, I just wasted a few hours trying to figure it out on my own!

**Comment by omgitstom** [comment]
Changing the title of this.  Thanks for the information!  I remember talking about this, I had a feeling we weren't there yet.  This is pretty cool and the developer value here is very nice.  We just need to figure out how to merchandise it with documentation :)

**Comment by jmelberg-okta** [comment]
Closing this issue as it is closely related to the feature request in #285
