### ISSUE TITLE
PKCE flow running issue in latest 2.0.0 Version

### ISSUE THREAD

**Issue by andrewvanbeek-okta** [okta/okta-oidc-js#741]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ X] okta-vue

## I'm submitting a:

- [X ] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Using the 2.0 Version of the Vue SDK when the PKCE is set to true, when hitting a protected route with an Okta session or Use of sign in widget I get "Unable to parse a token from the url".  

## Expected behavior

Desired behavior would be the parsing of the code similar to the behavior 1.3.0.   

## Minimal reproduction of the problem with instructions

Download one of the Vue JS Samples provided from Okta such as a custom-login and udpate the package JSON to reflect 2.0.0

## Environment

- Package Version:
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by andrewvanbeek-okta** [comment]
![image](https://user-images.githubusercontent.com/25853552/79269883-fe2c7a80-7e51-11ea-9d2a-4069a526c620.png)

**Comment by swiftone** [comment]
@andrewvanbeek-okta - Thanks for the report.  Until we update the samples, as a workaround, when using PKCE and the Okta Sign-In-Widget with one of our frontend SDKs, you need to set `responseMode` to `query` in the authParams. ( see okta/okta-signin-widget#1094 (comment) )

We're working on updating the widget to automatically default to this behavior when pkce is true.

**Comment by swiftone** [comment]
@andrewvanbeek-okta - Also, this requirement (changing setting for PKCE) should be automatically handled by the latest widget release (4.x)

**Comment by swiftone** [comment]
Note: updating the sample
Internal ref: OKTA-295160
