### ISSUE TITLE
okta-angular missing type for return of `getAccessToken()` in TypeScript

### ISSUE THREAD

**Issue by th3n3wguy** [okta/okta-oidc-js#75]
## Issue:
Within the `okta-angular` package, the typing output for the Okta Service's `.getAccessToken()` function return value is declared as `any`. This causes an issue when attempting to retrieve the access token using the `.accessToken` property on the object that is returned. After a quick search through the repository, it appears that the reason this is occurring is due to the fact that the return type is missing on the `getAccessToken()` function definition located on [this line of code](https://github.com/okta/okta-oidc-js/blob/master/packages/okta-angular/src/okta/okta.service.ts#L80).

## Possible Resolution
Need to define either an interface or a class that will contain the definition for the token than is returned from the [@okta/okta-auth-js](https://github.com/okta/okta-auth-js) function definition for then token and set that as the type for the return value of the function. If I get a chance, I will attempt to create this pull request, but please don't count on it.

**Comment by robertjd** [comment]
Hi @th3n3wguy , thank you for the repot.  We'll take a look at this next week

**Comment by cmckni3** [comment]
In general, types need to be added for TypeScript. I noticed a lot of `any` "types" in the type definitions. I can contribute if I have time.

**Comment by jmelberg-okta** [comment]
Resolved with #157 and #167
