### ISSUE TITLE
authState.isAuthenticated is true when authState.accessToken is undefined 

### ISSUE THREAD

**Issue by gjgd** [okta/okta-oidc-js#755]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

If `authService.getAccessToken` returns `undefined` and `authService.getIdToken` returns a value, then `authState.isAuthenticated` will be `true`. See:

https://github.com/okta/okta-oidc-js/blob/9d53b35f5cfb7a7a82f6a8a68d0d3b748a3d6f21/packages/okta-react/src/AuthService.js#L142

## Expected behavior

[Documentation](https://github.com/okta/okta-oidc-js/tree/9d53b35f5cfb7a7a82f6a8a68d0d3b748a3d6f21/packages/okta-react#configuration-options) says: "By default, authService will consider a user authenticated *if both getIdToken() and getAccessToken() return a value.*

Therefore I expect `authState.isAuthenticated` to be `false` when `authState.accessToken` is `undefined`

## Extra information about the use case/user story you are trying to implement

I want to be able to rely on `authState.isAuthenticated` to know when I can make API call that rely on the `accessToken`. But right now I can't because `authState.isAuthenticated` when `accessToken` is `undefined`.

## Environment

- Package Version: 2.0.1
- Browser: Firefox 75.0
- OS: MacOS
- Node version (`node -v`): 12.6

**Comment by gjgd** [comment]
Looks like a PR is up to rectify the docs: https://github.com/okta/okta-oidc-js/pull/752

Then @swiftone my question is, why is `isAuthenticated = !! (idToken || accessToken)` ?  the desired behavior instead of `isAuthenticated = !! (idToken && accessToken)` ?

**Comment by swiftone** [comment]
@gjgd - The reasoning is historical.  For now, nothing is changing for the sake of consistency, though we are reviewing how to better refine the concepts and update them in a coordinated way.  The original concept was less "Do we have the unexpired information for the user" and more "Has this user provided valid credentials" - as long as one token was still valid, the answer to the latter was "yes".  

Obviously when trying to USE the tokens the former question is more valuable, but we don't want to break anyone relying on the previous definition.  Discussions continue.

**Comment by gjgd** [comment]
Understood. For anyone wanting the `isAuthenticated` value to check for the presence of both tokens, here is my workaround:

```js
// Implement custom isAuthenticated method that enforces the presence of accessToken
// See: https://github.com/okta/okta-oidc-js/issues/755
const authService = new AuthService(OKTA_CONFIG);
// eslint-disable-next-line no-underscore-dangle
authService._config.isAuthenticated = async () => {
  const accessToken = await authService.getAccessToken();
  const idToken = await authService.getIdToken();
  return !!(accessToken && idToken);
};
```
and the Security component:
```js
<Security authService={authService}></Security>
```
