### ISSUE TITLE
Randomly getting AuthSdkError: Unable to parse a token from the url, but it works?!

### ISSUE THREAD

**Issue by DavidLozzi** [okta/okta-oidc-js#759]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

User logs in on Okta's site and gets redirected to our ReactJS app, and randomly users are getting the error `AuthSdkError: Unable to parse a token from the URL`. I've received the error too. But simply going back home works, it appears the token does get set as expected.

I am using a custom authentication check, which is a copy of `LoginCallback.js` with a touch of our own custom code for a custom error page.

```
import React, { useEffect } from 'react';
import { Redirect } from 'react-router';
import { useOktaAuth } from '@okta/okta-react';
import CONFIG from 'config';
import { setPsId } from 'utils/auth/auth';

const ImplicitCallback = () => {
  const { authService, authState } = useOktaAuth();

  useEffect(() => {
    authService.handleAuthentication();
    setPsId(); // sets a new GUID to local storage, 1 liner: localStorage.setItem('psid', 'the-guid');
  }, [authService]);

  if (authState.error) {
    return <Redirect to={CONFIG.UI_URL.ERROR(`401/${authState.error}`)} />; // LoginCallback returns <p>authState.error</p>, we redirect to an error page. For this to fire, then authState.error has to be valid 
  }

  return null;
};

export default ImplicitCallback;
```

## Expected behavior

Doesn't report an error

## Minimal reproduction of the problem with instructions

We can't reliably recreate the issue. It's happened once with me so far, 5,200 times (3% of traffic) since April 1. It seems totally random.

## Extra information about the use case/user story you are trying to implement

Thinking about removing our code and using the library's code, but this is in Prod with 18k users, we don't want to revert to the plan useless error message, yet.

## Environment

- Package Version: 2.0.0
- Browser: Chrome, Firefox
- OS: Windows and Mac
- Node version (`node -v`): 10.16.3
- Other:

**Comment by maneeshsahu** [comment]
Getting this error with okta-vue 2.0.0 as well.

**Comment by robertjd** [comment]
Hi @DavidLozzi , a few things to look at:

- `handleAuthentication` is an async method, so you'll want to `await` on that to avoid race issues
- Look through your router configuration to make sure that other routing logic/controllers aren't trying to run at the same time as this `ImplicitCallback` handler, i.e. make sure that `ImplicitCallback` isn't getting called twice.

If you are having a production issue, please start a conversation through support@okta.com as well.

**Comment by robertjd** [comment]
@DavidLozzi also, try comparing your app to our sample apps for ideas: https://github.com/okta/samples-js-react

**Comment by DavidLozzi** [comment]
looking at the latest code, https://github.com/okta/okta-oidc-js/blob/e4f0aaf8b8b574e6a32d307c5f33732415479dde/packages/okta-react/src/LoginCallback.js#L24,  it looks like there is a check there for pending, which points to @robertjd first bullet. I've added this code we'll see how it goes

**Comment by DavidLozzi** [comment]
Even better, looks like the latest version has what I'm trying to accomplish, having a custom error page: https://github.com/okta/okta-oidc-js/blob/e4f0aaf8b8b574e6a32d307c5f33732415479dde/packages/okta-react/src/LoginCallback.js#L30

I'll revamp my stuff for this and see how it works. Thanks!
