### ISSUE TITLE
Changes in v3, LoginCallback doesn't work

### ISSUE THREAD

**Issue by DavidLozzi** [okta/okta-oidc-js#767]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

I just upgraded to v3 and now I get the error message:

`OAuthError: The response type is not supported by the authorization server. Configured response types: [token, id_token].`

Which Google doesn't have anything good on. I am using `LoginCallback` in my `App.js` for the implicit callback path.

I noticed however that there are some undocumented code changes:

The auth service configuration went from:

```
export default new AuthService({
  history,
  issuer: CONFIG.OKTA.ISSUER,
  client_id: CONFIG.OKTA.CLIENT_ID,
  redirect_uri: `${window.location.origin}${CONFIG.OKTA.REDIRECT_URL}`
});
```

to

```
export default new AuthService({
  history,
  issuer: CONFIG.OKTA.ISSUER,
  clientId: CONFIG.OKTA.CLIENT_ID,
  redirectUri: `${window.location.origin}${CONFIG.OKTA.REDIRECT_URL}`
});
```

noting the slight difference in the `client_id` and `redirect_uri`.

Are there other changes I need to be aware of for this migration? Currently, 3.0 isn't working in my app, but I'm guessing there are other weird things like this.

## Expected behavior

It works

## Environment

- Package Version: 3.0.1
- Browser: Chrome 81
- OS: Mac
- Node version (`node -v`): 10.16.3
- Other:

**Comment by mraible** [comment]
You have to set up your app to use Authorization code flow. If you're already done that, try adding `pkce: true` to your configuration.

**Comment by swiftone** [comment]
I suspect your app is not configured in okta to support PKCE, which is now the default.  You can see the list of changes in the CHANGELOG ( https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/CHANGELOG.md ) or the Release Notes ( https://github.com/okta/okta-oidc-js/releases/tag/%40okta%2Fokta-react%403.0.0 )

The underscore-based variables were moved to not-preferred in version 1.2.2 ( https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/CHANGELOG.md#other-1 )  

If you're upgrading from the 1.x version, you should also see the migration notes https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#migrating-from-1x-to-20 in the README

Let us know if the error you're experiencing isn't resolved by updating your app config in Okta or explicitly passing `pkce: false`

**Comment by DavidLozzi** [comment]
I was afraid of that, am I right in understanding that moving from 2.0 to 3.0 requires a new configuration on the OKTA instance?

**Comment by swiftone** [comment]
@DavidLozzi - If your app worked on 2.0 (with Implicit Flow), the two changes should be:
- make sure you're using the camelCase params (as you already noted)
- Either pass `pkce: false` to `<Security>`  OR update the okta dashboard configuration for your app to allow Authorization Code flow and include PKCE grants

If you don't want to update the okta dashboard config for your app, just pass the `pkce: false` to `<Security>` (or wherever you instantiate AuthService) to continue using the Implicit Flow.

**Comment by DavidLozzi** [comment]
setting `pkce: false` seems to work. Security team is reviewing the option for Authorization Code. Is there a read up that explains what that does/enable?

Also, is there documentation that explains this that I missed? I see the release notes but who reads all that for a version upgrade ;) I like the 1.x to 2 migration notes, maybe a to 3.x is warranted?

**Comment by DavidLozzi** [comment]
Security enabled Authorization Code, and then I removed the `pkce:false` and I'm back at this same error. It appears the auth code setting didn't help. 
![image](https://user-images.githubusercontent.com/3543383/80751440-c848f080-8af7-11ea-8714-da377f3f9bca.png)

**Comment by swiftone** [comment]
@DavidLozzi - We're unable to reproduce your problem and you appear to be doing all the correct steps.  I suggest you reach out to our support team at developers@okta.com as they will be able to look at your org configuration specifically to see what isn't lining up.

**Comment by swiftone** [comment]
Closing this issue as stale (though updating our docs to include a 2.x to 3.x migration remains an active task).
