### ISSUE TITLE
Is it possible to get the original referrer, the page the user came from prior to their OKTA authentication?

### ISSUE THREAD

**Issue by DavidLozzi** [okta/okta-oidc-js#785]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [ ] Feature request
- [x] Other (Describe below)

## Current behavior

We need to capture where the user came from when entering our app. Unfortunately, if the user is not authenticated yet, they'll go to okta, then authenticate, and be redirected to our app. When this happens, we lose the `document.referrer` value of where they came from, it now reports the okta address.

Can we obtain their original referrer value from somewhere?

## Environment

- Package Version: 3.0.0
- Browser: All
- OS: All
- Node version (`node -v`): 10.16.3
- Other:

**Comment by swiftone** [comment]
This should be possibly by setting a `state` param as one of the `additionalParams` object that is passed to `authService.login()` (https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#authserviceloginfromuri-additionalparams)

`state` is sent out with the redirect and then sent back in with the return redirect.  You should make sure:

**Comment by aarongranick-okta** [comment]
@DavidLozzi Was this information able to resolve your issue?

**Comment by DavidLozzi** [comment]
It looks promising, haven't tried it yet, in the back log ;) I can close for now. Thanks!
