### ISSUE TITLE
React Native | MFA prompt results in an Error - Sign in was not authorized

### ISSUE THREAD

**Issue by maneeshsahu** [okta/okta-oidc-js#787]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
I am using the custom-signin to authenticate an Okta user using SMS as a factor. 
```
    signIn({username})
      .then(token => {
        this.setState(
          {
            progress: false,
            error: '',
          },
          () => navigation.navigate('Shows'),
        );
      })
      .catch(e => {
        console.warn('onError', e);
        console.log(JSON.stringify(e));
        this.setState({progress: false, error: e.message});
      });
```
Rather than a response for a MFA prompt, I am getting an error as below. 

```
onError Error: Sign in was not authorized
    at index.js:104
    at tryCallOne (core.js:37)
    at core.js:123
    at JSTimers.js:289
    at _callTimer (JSTimers.js:146)
    at _callImmediatesPass (JSTimers.js:194)
    at Object.callImmediates (JSTimers.js:458)
    at MessageQueue.__callImmediates (MessageQueue.js:366)
    at MessageQueue.js:135
    at MessageQueue.__guard (MessageQueue.js:343)
```

```
{"code":"-1000","detail":{}}
```

## Expected behavior
Expected - a callback for processing the MFA prompt.

## Minimal reproduction of the problem with instructions
Use the custom-signin sample configured against an Okta tenant that has a Sign In policy that uses SMS as the only factor. 

## Extra information about the use case/user story you are trying to implement
Need React Native to support passwordless and/or MFA flow.

## Environment

- Package Version: 1.4.0
- Browser: Google Chrome (latest)
- OS: MacOS Catalina 
- Node version (`node -v`): v14.2.0
- Other: iOS Simulator - Version 11.4.1 (921.9)

**Comment by shuowu** [comment]
@maneeshsahu In SMS MFA, you will need to auth user with the primary auth (username, password) first, then handle SMS as the second factor of authentication. So in the code, you will need to call `signIn({username, password})` to resolve the next state. 

After the response returned for the next state, you can use `getAuthClient` to get an instance of `okta-auth-js` client to communicate with OKTA MFA APIs. For detailed information, please follow https://github.com/okta/okta-auth-js#mfa_required

**Comment by maneeshsahu** [comment]
Hi @shuowu I am able to do passwordless using the raw Okta APIs, why is the SDK restricting functionality?

**Comment by maneeshsahu** [comment]
Also for MFA, what is the EventCallback - I only see these listed:
- signInSuccess
- signOutSuccess
- onError
- onCancelled

**Comment by shuowu-okta** [comment]
@maneeshsahu 
1. Under the [API link](https://developer.okta.com/docs/reference/api/authn/#request-parameters-for-primary-authentication), there is 
> As part of the authentication call either the username and password or the token parameter must be provided.

which means you need to use `username & password` or `token` for primary auth.

2. Per how to handle MFA event callback. 
As `signIn` function returns a `Promise` back, you can try to resolve the transaction state from the promise, like
```
signIn({ username, password })
      .then(transaction => {
        if (transaction.status === 'MFA_REQUIRED') {
          // handle transaction with authClient
        }
      })
```
or you can try consume the `transaction` response in `singInSuccess`

**Comment by shuowu** [comment]
@maneeshsahu 
1. Under the [API link](https://developer.okta.com/docs/reference/api/authn/#request-parameters-for-primary-authentication), there is 
> As part of the authentication call either the username and password or the token parameter must be provided.

which means you need to use `username & password` or `token` for primary auth.

2. Per how to handle MFA event callback. 
As `signIn` function returns a `Promise` back, you can try to resolve the transaction state from the promise, like
```
signIn({ username, password })
      .then(transaction => {
        if (transaction.status === 'MFA_REQUIRED') {
          // handle transaction with authClient
        }
      })
```
or you can try consume the `transaction` response in `singInSuccess`

**Comment by maneeshsahu** [comment]
@shuowu This is the payload in Postman that works without a password.

```{
  "username": "<PHONENUMBER>",
  "options": {
    "multiOptionalFactorEnroll": true,
    "warnBeforePasswordExpired": true
  }  
}
```

**Comment by shuowu-okta** [comment]
Internal-ref: OKTA-300620

**Comment by shuowu** [comment]
Close this issue as `okta-react-native` currently only support `primary auth flow` in exposed `signIn` function. For implementing other auth flows, please use `getAuthClient` function from the SDK. For more information, please refer to [React native usage in auth js](https://github.com/okta/okta-auth-js#node-js-and-react-native-usage)
