### ISSUE TITLE
What's the expected value for appAuthRedirectScheme?

### ISSUE THREAD

**Issue by pittersnider** [okta/okta-oidc-js#788]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [ ] Feature request
- [x] Other: I didn't understand a part of the documentation

## Current behavior
Documentation says to add a property called appAuthRedirectScheme

## Expected behavior
What's the expected value for that field called appAuthRedirectScheme?

## Minimal reproduction of the problem with instructions
No issue to be reproduced.

## Extra information about the use case/user story you are trying to implement
No extra information required.

## Environment
No information required.

**Comment by mraible** [comment]
It's the reverse value of your Okta org domain, but it can be anything, as long as its value matches a redirect URI that you have registered in Okta. For example, my Okta dev account is at `https://dev-737525.okta.com`. If I create a native app in my account, the redirect URI will be `com.okta.dev-737523:/callback`. In this case, `appAuthRedirectScheme` should be `com.okta.dev-737523`.
