### ISSUE TITLE
The Okta guard doesn't have canActivateChild

### ISSUE THREAD

**Issue by baljinder-inmarsat** [okta/okta-oidc-js#791]
I've install okta angular sdk. I tried to add OktaAuthGuard to the canActivateChild prop route. 
But I kept getting an error. I decide to compare the file in github, https://github.com/okta/okta-oidc-js/blob/42e7186079a3588868c724df38ce0c5f72177de9/packages/okta-angular/src/okta/okta.guard.ts, with what is being added in the dependencies. I notice the canactiveChild is not there 
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [x ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x ] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
canActivateChild not working. And not seen in the dependency 

## Expected behavior
canActivateChild  working. And canActivateChild seen in the dependency as a method

## Minimal reproduction of the problem with instructions
install the dependency via npm.
look at the file for example okta.gaurd.d.ts:

no canActivateChild method available

![Screenshot from 2020-05-29 14-28-05](https://user-images.githubusercontent.com/45174015/83264874-a7d48a80-a1b8-11ea-99e7-95f986790f14.png)

or put a break point.

![Screenshot from 2020-05-29 14-28-54](https://user-images.githubusercontent.com/45174015/83264966-c33f9580-a1b8-11ea-951a-60803828f090.png)

 

## Environment

- Package Version: 2.0.0
- Browser: chrome
- OS: linux, fedora
- Node version (`node -v`): 12.4
- Other:

**Comment by aarongranick-okta** [comment]
@baljinder-inmarsat This method exists in the master branch but has not been published to npm yet. We are planning a publish soon, and this method will be available.

**Comment by baljinder-inmarsat** [comment]
Look forward to it when published. At the moment, as a temp solution, I have my own service with canactivatechild which uses oktaauthguard.
