### ISSUE TITLE
Is @okta/okta-react-native compatible with Expo?

### ISSUE THREAD

**Issue by clementizard** [okta/okta-oidc-js#792]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [ ] Bug report  
- [ ] Feature request
- [x] Other (Describe below)

## Current behavior
When using @okta/okta-react-native with Expo, warnings appear on functions like "submit" or "createConfig". And does not seems to be called.
It may be because the line `react-native link @okta/okta-react-native` can't be run with Expo.

## Expected behavior
Maybe provide a "Run with expo" documentation? Or on the other hand "Why is it not possible to use with Expo"?

## Minimal reproduction of the problem with instructions
Simply start an expo project and add the repository.

## Environment

- Package Version:  "@okta/okta-react-native": "1.3.0"
- Browser: Android Emulator
- OS: Windows
- Node version (`node -v`):  13.7.0
- Other: Expo: 37.0.7

**Comment by shuowu** [comment]
@clementizard As `okta-react-native` has dependency on native modules, like `okta-android-odic` and `okta-ios-oidc`. You probably want to eject expo `managed workflow` to `bare workflow` to work with `okta-react-native`. 
For more information please refer to [expo workflow comparison](https://docs.expo.io/introduction/managed-vs-bare/#workflow-comparison)

**Comment by clementizard** [comment]
Alright Thanks for the info, i've been ejecting my app and all's working fine :)
Closing now
