### ISSUE TITLE
OktaSdkBridge.createConfig was called with 6 arguments but expects 5

### ISSUE THREAD

**Issue by jdnichollsc** [okta/okta-oidc-js#795]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
![image](https://user-images.githubusercontent.com/2154886/83802306-21b0bc00-a670-11ea-8604-006e10bba0a8.png)

## Expected behavior
Be able to call **createConfig** method in this way:
```
createConfig({
  clientId: oidc.clientId,
  redirectUri: oidc.redirectUri,
  endSessionRedirectUri: oidc.endSessionRedirectUri,
  discoveryUri: oidc.discoveryUri,
  scopes: oidc.scopes,
  requireHardwareBackedKeyStore:
    oidc.requireHardwareBackedKeyStore
})
```

## Minimal reproduction of the problem with instructions
With the previous code attached.

## Environment

- Package Version: @okta/okta-react-native@1.4.1
- OS: MacOS Mojave 10.14.6
- Node version (`node -v`): v12.16.3

**Comment by jdnichollsc** [comment]
Similar issue from Android: 
![Screenshot_2020-06-04-16-30-31-143_com nordstrom employeeapp debug](https://user-images.githubusercontent.com/2154886/83812331-f97d8900-a680-11ea-8b4f-fd868effe263.jpg)

**Comment by jdnichollsc** [comment]
@swiftone can you publish the new release v1.4.1 to GitHub releases please? thanks in advance!

**Comment by shuowu** [comment]
@jdnichollsc The update from `1.4.1` involves both js change and native change. I assume you only updated in js thread. Maybe you can try to reinstall the app from the emulator/simulator. Also, make sure you run `pod install` in the `ios` folder to update the native dependencies.

**Comment by jdnichollsc** [comment]
I did that, but it looks like **podspec** is pointing to the github release (the version 1.4.1 doesn't exist) :)

**Comment by shuowu** [comment]
@jdnichollsc `okta-react-native` v1.4.1 is released on Github, can you please try again to see if it works now? Thanks

**Comment by jdnichollsc** [comment]
let me verify, thanks for your help!

**Comment by oleggnidets-okta** [comment]
I believe it must be fixed in [our SDK](https://github.com/okta/okta-react-native). If not, please, open the issue in [okta-react-native](https://github.com/okta/okta-react-native).

Thanks for your contribution!
