### ISSUE TITLE
okta-react-native fails to build on rn 0.61.5

### ISSUE THREAD

**Issue by mokingguy** [okta/okta-oidc-js#806]
## I'm submitting this issue for the package(s):

- [x] okta-react-native

## I'm submitting a:

- [x] Bug report  

## Current behavior

Building okta-react-native results on a error on ios, the error in question is:

[..]/node_modules/@okta/okta-react-native/ios/OktaSdkBridge.swift:34:28: Type 'OktaOidcConfig' has no member 'setUserAgent'

## Expected behavior

The project should be able to compile and run

## Minimal reproduction of the problem with instructions

1. Install the package
2. Run pod install
3. Set the target ios to 11.0 
4. Set swift compiler to 4.3
3. Build your project

## Environment

- Package Version: 1.4.1
- OS: iOS 13.2 (target 11.0)
- Node version (`node -v`): 10.16.2
- React-native: 0.61.5
- Xcode: 11.3.1

**Comment by shuowu** [comment]
@mokingguy The latest `okta-react-native` also comes with native ios dependency update, which will not be auto-updated with npm update. Please try `pod update` under your `ios` folder.

**Comment by mokingguy** [comment]
That did the trick, might be worth mentioning it on the installation instructions since mine was a fresh, first time install of the package.

Thanks!
