### ISSUE TITLE
React-native android application is crashing when user try to enable the location service from the application without okta login

### ISSUE THREAD

**Issue by Narasinha** [okta/okta-oidc-js#807]
## I'm submitting this issue for the package(s):

- okta-react-native

## I'm submitting a:

- Bug report

## Current behavior
_Install the okta-react-native library in the react-native android application. Disable the location service of the phone.  Try to access the location service from the app without okta authentication(without okta login).  Location service pop will appear to enable the location. Click "OK" or "NO THANKS" button of the location service popup which will crash the application(only in android)_

## Expected behavior
_User should able to enable the location service of the phone from application without okta authentication_ 

## Minimal reproduction of the problem with instructions

- Create the react-native app
- Add location service permission settings to the project
- Install @okta/okta-react-native library to the project
- Build the project and install it on the device
- Disable the location service of android device
- Open the application which accesses the location without okta authentication(without okta login)
- location pop will appear to enable the location
- Click "OK" or "NO THANKS" button of location popup which will crash the android application

Please find the below link for sample project(Disable the location service from the phone before running app)
https://github.com/Narasinha/sample-project-okta-error

## Extra information about the use case/user story you are trying to implement

--------- beginning of crash
06-18 18:10:35.003  8401  8401 E AndroidRuntime: FATAL EXCEPTION: main
06-18 18:10:35.003  8401  8401 E AndroidRuntime: Process: com.location, PID: 8401
06-18 18:10:35.003  8401  8401 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=42, result=-1, data=Intent { (has extras) }} to activity {com.location/com.location.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object com.okta.oidc.clients.web.WebAuthClient.getSessionClient()' on a null object reference
06-18 18:10:35.003  8401  8401 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4963)
06-18 18:10:35.003  8401  8401 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5004)
06-18 18:10:35.003  8401  8401 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
06-18 18:10:35.003  8401  8401 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-18 18:10:35.003  8401  8401 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-18 18:10:35.003  8401  8401 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
06-18 18:10:35.003  8401  8401 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-18 18:10:35.003  8401  8401 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
06-18 18:10:35.003  8401  8401 E AndroidRuntime: 	at android.a
06-18 18:10:35.021  2289  2425 W InputDispatcher: channel 'ba1d57d com.google.android.gms/com.google.android.location.settings.LocationSettingsCheckerActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
06-18 18:10:35.021  2289  2425 E InputDispatcher: channel 'ba1d57d com.google.android.gms/com.google.android.location.settings.LocationSettingsCheckerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-18 18:10:35.022  2289  4725 W InputDispatcher: Attempted to unregister already unregistered input channel 'ba1d57d com.google.android.gms/com.google.android.location.settings.LocationSettingsCheckerActivity (server)'
06-18 18:10:35.024  2888  3883 W GCoreFlp: No location to return for getLastLocation()
06-18 18:10:35.052  2289  2597 W ActivityTaskManager:   Force finishing activity com.location/.MainActivity
06-18 18:10:35.053  2289  8700 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
06-18 18:10:35.055  2888  2888 I NetRec  : [2] akuz.a: Starting service.
06-18 18:10:35.055  2888  2888 I NetRec  : [2] akxv.a: Now the active scorer.
06-18 18:10:35.056  2071  2129 D eglCodecCommon: allocate: Ask for block of size 0x5da800
06-18 18:10:35.056  2071  2129 D eglCodecCommon: allocate: ioctl allocate returned offset 0x3f66a0000 size 0x5dc000
06-18 18:10:35.088  2289  2337 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
06-18 18:10:35.089  2289  2337 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
06-18 18:10:35.090  8401  8401 I Process : Sending signal. PID: 8401 SIG: 9
06-18 18:10:35.107  2888  2888 I GeofencerStateMachine: sendQueryLocationOptIn
06-18 18:10:35.120  2289  2325 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.nearby.discovery:ACTION_PERMISSION_CHANGE cmp=com.google.android.gms/.nearby.discovery.service.DiscoveryService } U=0: not found
06-18 18:10:35.133  2888  2888 W LocationManager: 
06-18 18:10:35.133  2888  2888 W LocationManager: java.lang.UnsupportedOperationException: GpsStatus APIs not supported in S and above, use GnssStatus APIs instead
06-18 18:10:35.133  2888  2888 W LocationManager: 	at android.location.LocationManager.addGpsStatusListener(LocationManager.java:1871)
06-18 18:10:35.133  2888  2888 W LocationManager: 	at esj.run(:com.google.android.gms@200313022@20.03.13 (040700-289679754):1)
06-18 18:10:35.133  2888  2888 W LocationManager: 	at android.os.Handler.handleCallback(Handler.java:907)
06-18 18:10:35.133  2888  2888 W LocationManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-18 18:10:35.133  2888  2888 W LocationManager: 	at aepo.a(:com.google.android.gms@200313022@20.03.13 (040700-289679754):2)
06-18 18:10:35.133  2888  2888 W LocationManager: 	at aepo.dispatchMessage(:com.google.android.gms@200313022@20.03.13 (040700-289679754):15)
06-18 18:10:35.133  2888  2888 W LocationManager: 	at android.os.Looper.loop(Looper.java:216)
06-18 18:10:35.133  2888  2888 W LocationManager: 	at android.app.ActivityThread.main(ActivityThread.java:7506)
06-18 18:10:35.133  2888  2888 W LocationManager: 	at java.lang.reflect.Method.invoke(Native Method)
06-18 18:10:35.133  2888  2888 W LocationManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-18 18:10:35.133  2888  2888 W LocationManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:956)
06-18 18:10:35.142  2289  3000 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.nearby.discovery:ACTION_PERMISSION_CHANGE cmp=com.google.android.gms/.nearby.discovery.service.DiscoveryService } U=0: not found
06-18 18:10:35.149  2289  2425 W InputDispatcher: channel 'efd1676 com.location/com.location.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0xd
06-18 18:10:35.150  2289  2425 E InputDispatcher: channel 'efd1676 com.location/com.location.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-18 18:10:35.156  2289  4555 I ActivityManager: Process com.location (pid 8401) has died: prcp TOP 
06-18 18:10:35.157  2289  2339 I libprocessgroup: Successfully killed process cgroup uid 10149 pid 8401 in 0ms
06-18 18:10:35.159  2289  2326 I WindowManager: WIN DEATH: Window{efd1676 u0 com.location/com.location.MainActivity}
06-18 18:10:35.160  2289  2326 W InputDispatcher: Attempted to unregister already unregistered input channel 'efd1676 com.location/com.location.MainActivity (server)'
06-18 18:10:35.173  2545  2561 I ndroid.systemu: NativeAlloc concurrent copying GC freed 289(65KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5572KB/10MB, paused 16.325ms total 83.377ms
06-18 18:10:35.174  2057  2057 I Zygote  : Process 8401 exited due to signal 9 (Killed)

## Environment

- Package Version:@okta/okta-react-native": "1.4.1"
- Browser N/A
- OS: Android
- Node version (`node -v`): v12.9.0(any version)
- Other:N/A

**Comment by arch10** [comment]
I am getting this same issue. App crashes when location permission is disabled.

**Comment by arch10** [comment]
```
06-13 19:42:27.438 10488 10488 D AndroidRuntime: Shutting down VM
06-13 19:42:27.439 10488 10488 E AndroidRuntime: FATAL EXCEPTION: main
06-13 19:42:27.439 10488 10488 E AndroidRuntime: Process: com.test.projectname, PID: 10488
06-13 19:42:27.439 10488 10488 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=11403, result=-1, data=Intent { (has extras) }} to activity {com.test.projectname/com.test.projectname.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.okta.oidc.clients.web.WebAuthClient.handleActivityResult(int, int, android.content.Intent)' on a null object reference
06-13 19:42:27.439 10488 10488 E AndroidRuntime: at android.app.ActivityThread.deliverResults(ActivityThread.java:4963)
06-13 19:42:27.439 10488 10488 E AndroidRuntime: at android.app.ActivityThread.handleSendResult(ActivityThread.java:5004)
06-13 19:42:27.439 10488 10488 E AndroidRuntime: at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
06-13 19:42:27.439 10488 10488 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-13 19:42:27.439 10488 10488 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-13 19:42:27.439 10488 10488 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
06-13 19:42:27.439 10488 10488 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
06-13 19:42:27.439 10488 10488 E AndroidRuntime: at a
06-13 19:42:27.472 2291 2419 W InputDispatcher: channel '7845d25 com.google.android.gms/com.google.android.location.settings.LocationSettingsCheckerActivity (server)' ~ Consumer closed input channel or an error occurred. events=0x9
06-13 19:42:27.472 2291 2419 E InputDispatcher: channel '7845d25 com.google.android.gms/com.google.android.location.settings.LocationSettingsCheckerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-13 19:42:27.473 2878 3823 W GCoreFlp: No location to return for getLastLocation()
06-13 19:42:27.474 2291 4058 W InputDispatcher: Attempted to unregister already unregistered input channel '7845d25 com.google.android.gms/com.google.android.location.settings.LocationSettingsCheckerActivity (server)'
06-13 19:42:27.499 2878 2878 I GeofencerStateMachine: sendQueryLocationOptIn
06-13 19:42:27.505 2291 5638 W ActivityTaskManager: Force finishing activity com.test.projectname/.MainActivity
06-13 19:42:27.508 2291 10661 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
06-13 19:42:27.509 2068 7729 D eglCodecCommon: allocate: Ask for block of size 0x5da800
06-13 19:42:27.509 2068 7729 D eglCodecCommon: allocate: ioctl allocate returned offset 0x3fae70000 size 0x5dc000
06-13 19:42:27.518 2878 3860 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
06-13 19:42:27.542 2966 2978 I s.nexuslaunche: NativeAlloc concurrent copying GC freed 4743(309KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 3146KB/6293KB, paused 705us total 142.899ms
06-13 19:42:27.545 2291 2335 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
06-13 19:42:27.546 2291 2335 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
06-13 19:42:27.572 10488 10488 I Process : Sending signal. PID: 10488 SIG: 9
06-13 19:42:27.594 2291 2335 W BroadcastQueue: Background execution not allowed: receiving Intent { act=com.google.android.location.internal.server.ACTION_RESTARTED flg=0x10 } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentInternalReceiver
06-13 19:42:27.615 2878 2878 W LocationManager:
06-13 19:42:27.615 2878 2878 W LocationManager: java.lang.UnsupportedOperationException: GpsStatus APIs not supported in S and above, use GnssStatus APIs instead
06-13 19:42:27.615 2878 2878 W LocationManager: at android.location.LocationManager.addGpsStatusListener(LocationManager.java:1871)
06-13 19:42:27.615 2878 2878 W LocationManager: at esj.run(:com.google.android.gms@200313022@20.03.13 (040700-289679754):1)
06-13 19:42:27.615 2878 2878 W LocationManager: at android.os.Handler.handleCallback(Handler.java:907)
06-13 19:42:27.615 2878 2878 W LocationManager: at android.os.Handler.dispatchMessage(Handler.java:99)
06-13 19:42:27.615 2878 2878 W LocationManager: at aepo.a(:com.google.android.gms@200313022@20.03.13 (040700-289679754):2)
06-13 19:42:27.615 2878 2878 W LocationManager: at aepo.dispatchMessage(:com.google.android.gms@200313022@20.03.13 (040700-289679754):15)
06-13 19:42:27.615 2878 2878 W LocationManager: at android.os.Looper.loop(Looper.java:216)
06-13 19:42:27.615 2878 2878 W LocationManager: at android.app.ActivityThread.main(ActivityThread.java:7506)
06-13 19:42:27.615 2878 2878 W LocationManager: at java.lang.reflect.Method.invoke(Native Method)
06-13 19:42:27.615 2878 2878 W LocationManager: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-13 19:42:27.615 2878 2878 W LocationManager: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:956)
06-13 19:42:27.637 2291 4230 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.nearby.discovery:ACTION_PERMISSION_CHANGE cmp=com.google.android.gms/.nearby.discovery.service.DiscoveryService } U=0: not found
06-13 19:42:27.667 2291 2761 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.nearby.discovery:ACTION_PERMISSION_CHANGE cmp=com.google.android.gms/.nearby.discovery.service.DiscoveryService } U=0: not found
06-13 19:42:27.677 2291 2419 W InputDispatcher: channel 'a1670c9 com.test.projectname/com.test.projectname.MainActivity (server)' ~ Consumer closed input channel or an error occurred. events=0xd
06-13 19:42:27.677 2291 2419 E InputDispatcher: channel 'a1670c9 com.test.projectname/com.test.projectname.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-13 19:42:27.677 2291 5667 I WindowManager: WIN DEATH: Window{a1670c9 u0 com.test.projectname/com.test.projectname.MainActivity}
06-13 19:42:27.677 2291 5667 W InputDispatcher: Attempted to unregister already unregistered input channel 'a1670c9 com.test.projectname/com.test.projectname.MainActivity (server)'
06-13 19:42:27.684 2054 2054 I Zygote : Process 10488 exited due to signal 9 (Killed)
```

`Failure delivering result ResultInfo{who=null, request=11403, result=-1, data=Intent { (has extras) }} to activity`

**Comment by jdnichollsc** [comment]
We're getting a similar issue when we use other Android activities, working with another native plugins like this: https://github.com/react-native-community/react-native-share

Native logs:
```
Process: com.org.myapp.debug, PID: 17677
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=16845, result=-1, data=null} to activity {com.org.myapp.debug/com.org.myapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.okta.oidc.clients.web.WebAuthClient.handleActivityResult(int, int, android.content.Intent)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4464)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4506)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6831)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.okta.oidc.clients.web.WebAuthClient.handleActivityResult(int, int, android.content.Intent)' on a null object reference
        at com.oktareactnative.OktaSdkBridgeModule.onActivityResult(OktaSdkBridgeModule.java:382)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:275)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:703)
        at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:89)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:110)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:67)
        at android.app.Activity.dispatchActivityResult(Activity.java:7590)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4457)
```

Thanks in advance

**Comment by shuowu** [comment]
Internel-ref: OKTA-312425

**Comment by arch10** [comment]
I am able to replicate this crash for mostly all the case where we are expecting some result from the intent. Only happens if you are not logged in to Okta.

```
08-13 21:51:00.716 15115 15115 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=61110, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:26 flg=0x1 }} to activity {com.example.company/com.example.company.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.okta.oidc.clients.web.WebAuthClient.handleActivityResult(int, int, android.content.Intent)' on a null object reference
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.okta.oidc.clients.web.WebAuthClient.handleActivityResult(int, int, android.content.Intent)' on a null object reference
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at com.oktareactnative.OktaSdkBridgeModule.onActivityResult(OktaSdkBridgeModule.java:379)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:275)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:703)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:89)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:110)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:67)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8110)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
08-13 21:51:00.716 15115 15115 E AndroidRuntime: 	... 11 more
08-13 21:51:00.728 11022 11040 W ActivityTaskManager:   Force finishing activity com.example.company/.MainActivity
```

@shuowu any update on this bug?

**Comment by shuowu** [comment]
@arch10 Thanks for the information! 
I don't see a workaround now as the bug looks come from the android native bridge. We'll prioritize the issue to get it fixed.

**Comment by shuowu** [comment]
@Narasinha @arch10 @jdnichollsc 
Looks like [PermissionsAndroid API](https://reactnative.dev/docs/permissionsandroid) need to be set up to work with Android M's new permissions model.

Reference: https://reactnative.dev/docs/geolocation.html#android

**Comment by sam1463** [comment]
I believe this is occurring due to the following code in `android/src/main/java/com/oktareactnative/OktaSdkBridgeModule.java`:

```
@Override
    public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) {
        webClient.handleActivityResult(requestCode & 0xffff, resultCode, data);
        Activity currentActivity = getCurrentActivity();
        registerCallback(currentActivity);
    }
```

The method doesn't make sure `webClient` exists before calling it, resulting in this null pointer exception when it doesn't exist. See the sanity checking found in the method right above it in the same file:

```
@ReactMethod
    public void clearTokens(final Promise promise) {
        try {
            if (webClient != null) {
                webClient.getSessionClient().clear();
            }
...
```

I've updated that code locally in my node_modules directory to add a sanity check, and it's fixing this crash for me:

```
@Override
    public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) {
        if (webClient != null) {
            webClient.handleActivityResult(requestCode & 0xffff, resultCode, data);
            Activity currentActivity = getCurrentActivity();
            registerCallback(currentActivity);
        }
    }
```

Based on the code in that file, since webClient is initialized in createConfig, I think it may be safe to say that this is happening only when `createConfig` has been called, which as the docs for this library say, should be called before this library is used. However, since this error is occurring for my app without calling anything from this library yet (in my case, using react-native-image-picker), I still think this should be considered a bug with this library. If the change I've posted is acceptable, I'm happy to make a pull request.
