### ISSUE TITLE
Error on having issuer domain ends with xxxxcom.com

### ISSUE THREAD

**Issue by wmg-darrenchen** [okta/okta-oidc-js#814]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

We have a custom domain issuer https://somethingecom.com/oauth2/default
It keeps throwing "It looks like there's a typo in your Okta domain." error because the domain contains **ecom.com**

## Expected behavior

This domain should be accepted.

## Environment

- Package Version:
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by aarongranick-okta** [comment]
@wmg-darrenchen Thanks for the report. We will get this fixed as soon as possible in an upcoming release
Internal ref: OKTA-308879

**Comment by shuowu** [comment]
Fixed in @okta/configuration-validation@0.4.3

@wmg-darrenchen Please update your dependencies to use the latest `@okta/configuration-validation`.

**Comment by wmg-darrenchen** [comment]
Thanks for the update.
