### ISSUE TITLE
React-native app with Typescript getting TypeError

### ISSUE THREAD

**Issue by cyangibm** [okta/okta-oidc-js#820]
## I'm submitting this issue for the package(s):

- [ ] okta-react-native

## I'm submitting a:

- [ ] Bug report  
WARNING
18:08
[Unhandled promise rejection: TypeError: Cannot read property 'createConfig' of undefined]

Stack trace:
  node_modules/@okta/okta-react-native/index.js:31:28 in createConfig
  node_modules/regenerator-runtime/runtime.js:45:39 in tryCatch
  node_modules/regenerator-runtime/runtime.js:274:21 in invoke
  node_modules/regenerator-runtime/runtime.js:97:20 in prototype.method
  node_modules/regenerator-runtime/runtime.js:45:39 in tryCatch
  node_modules/regenerator-runtime/runtime.js:135:19 in invoke
  node_modules/regenerator-runtime/runtime.js:170:10 in PromiseImpl$argument_0
  node_modules/promise/setimmediate/core.js:45:4 in tryCallTwo
  node_modules/promise/setimmediate/core.js:200:12 in doResolve
  node_modules/promise/setimmediate/core.js:66:2 in Promise

## Current behavior
React-Native app using Typescript rendered the Login button, but when you click on the button, above TypeError showed up.

## Expected behavior
Login successfully.

## Minimal reproduction of the problem with instructions
You can use any React-Native app using typescript to reproduce.

## Extra information about the use case/user story you are trying to implement
Blocking our app integration with okta.

## Environment

- Package Version:
- Browser:
- OS:ReactNative 0.62
- Node version (`node -v`):v12.16.2
- Other:

**Comment by oleggnidets-okta** [comment]
Hey @cyangibm,
We support TS in our [React Native SDK](https://github.com/okta/okta-react-native). Please, check it out.
