### ISSUE TITLE
OktaCallbackComponent: "AuthSdkError: Could not load PKCE codeVerifier from storage" 

### ISSUE THREAD

**Issue by b1gb3n97** [okta/okta-oidc-js#844]
## I'm submitting this issue for the package(s):

- [ ] okta-react
- [ ] jwt-verifier
- [X] okta-angular
- [ ] oidc-middleware
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [X] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
Currently, our Angular app is set up to immediately redirect the user to a protected route (the main app page), which redirects them to the Okta login (when not already authenticated). After being redirected back, it should load the main page. 

This has been working without problems almost every time, however it seems when I first launch the application in the morning (for the day) it always comes up with this error on the callback page:

`AuthSdkError: Could not load PKCE codeVerifier from storage`

in the HTML, while still sitting at the /implicit/callback route. However if I clear cache/cookies or re-launch in incognito mode, the error doesn't occur and PKCE verification works just fine.

## Expected behavior

The authentication flow should work the first time without a PKCE error, and without having to clear cache/cookies.

## Minimal reproduction of the problem with instructions

1. Launch application
2. Log in through Okta
3. Successful login redirects to /implicit/callback page (with the OktaCallbackComponent), but also returns the AuthSdkError.

## Environment

- Package Version: 2.1.0
- Browser: Chrome 78.0.3904.8
- OS: Windows 7
- Node version (`node -v`): v12.17.0
- Other: Angular 7

**Comment by sleepwalky** [comment]
Sometimes it happens to me as well. I'm using @okta/okta-react@^3.0.2.
Usually I see this error when I'm launching the app and logging in for the first time at the beginning of my working day.

![image](https://user-images.githubusercontent.com/14991709/88829363-29569200-d1d5-11ea-806f-7d7c4cdbf549.png)

Then the page is refreshed (as far as I understand re-login happened) and I'm successfully logged in and redirected to home page.

**Comment by michmerr** [comment]
I've been seeing this, too. It's happening when refreshing an application with an expired session. I get the redirect to login, but on the callback, it give me the error you are encountering. Refreshing the app after that _looks_ like it works, but the auth object passed to the React components fails to generate valid jwt tokens for use when communicating with the application's express layer. As a result, the UI loads, but all the calls to the business logic on the server fail due to invalid access tokens.

@okta/okta-react ^3.0.2, @okta/okta-auth-js ^3.1.4

**Comment by OwenVey** [comment]
I too have been seeing this happen recently and see the same thing @michmerr has pointed out where refreshing with an expired session causing this error. I am using @okta/okta-vue ^2.0.0.

**Comment by shuowu** [comment]
@OwenVey Does this thread (https://github.com/okta/okta-oidc-js/issues/862) help?

**Comment by shuowu** [comment]
@b1gb3n97 For angular SDK, please override the onSessionExpired callback to a no-op function (`() => {}`) as a workaround we'll deprecate the default behavior of that callback function in next angular release.

**Comment by shuowu** [comment]
@sleepwalky @michmerr The issue should have been fixed in react-sdk. The latest version are @okta/okta-react  3.0.4, @okta/okta-auth-js  3.2.3.

**Comment by b1gb3n97** [comment]
> 
> 
> @b1gb3n97 For angular SDK, please override the onSessionExpired callback to a no-op function (`() => {}`) as a workaround we'll deprecate the default behavior of that callback function in next angular release.

Thanks for the reply. This workaround seems to fix it for now.

**Comment by monasterx3** [comment]
Did this ever get resolved? I am still facing these issues

**Comment by shuowu** [comment]
@monasterx3 This error message may happen by different causes. Do you mind to open a new issue thread in https://github.com/okta/okta-angular/issues
