### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection Issue

### ISSUE THREAD

**Issue by jamesnogra** [okta/okta-oidc-js#85]
Hi, I'm getting this error message from time to time:

> (node:10572) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RequestError: Request timed out

I'm not sure what's causing it. Can you help me out on this?

This is my code:
```
oidc.on('ready', () => {
  app.listen(3000, () => console.log('App Started!'));
});
```

**Comment by robertjd** [comment]
Hi @jamesnogra can you try adding this error handler to see if the error is caught in here:
```
oidc.on('error', err => {
  console.error(err)
});
```

**Comment by jamesnogra** [comment]
Thanks for the quick reply. Here's what I got:
```
RequestError: Request timed out
    at timeoutFn (C:\wamp64\www\RVSlinkyLinks\node_modules\openid-client\node_modules\got\index.js:286:53)
    at asPromise (C:\wamp64\www\RVSlinkyLinks\node_modules\openid-client\node_modules\got\index.js:356:18)
    at got (C:\wamp64\www\RVSlinkyLinks\node_modules\openid-client\node_modules\got\index.js:575:10)
    at Function.got.(anonymous function) [as get] (C:\wamp64\www\RVSlinkyLinks\node_modules\openid-client\node_modules\got\index.js:593:31)
    at Object.get (C:\wamp64\www\RVSlinkyLinks\node_modules\openid-client\lib\http.js:14:14)
    at Function.discover (C:\wamp64\www\RVSlinkyLinks\node_modules\openid-client\lib\issuer.js:191:28)
    at Object.oidcUtil.createClient.context [as createClient] (C:\wamp64\www\RVSlinkyLinks\node_modules\@okta\oidc-middleware\src\oidcUtil.js:29:17)
    at ExpressOIDC (C:\wamp64\www\RVSlinkyLinks\node_modules\@okta\oidc-middleware\src\ExpressOIDC.js:107:14)
    at Object.<anonymous> (C:\wamp64\www\RVSlinkyLinks\app.js:35:14)
    at Module._compile (module.js:570:32)
  name: 'RequestError',
  code: 'ETIMEDOUT',
  host: 'dev-XXXXXX.oktapreview.com',
  hostname: 'dev-XXXXXX.oktapreview.com',
  method: 'GET',
  path: '/oauth2/default/.well-known/openid-configuration',
  protocol: 'https:',
  url: 'https://dev-346920.oktapreview.com/oauth2/default/.well-known/openid-configuration'
```

**Comment by robertjd** [comment]
Thanks!  Is this a consistent error, or a sometimes error?  Please take a look at the conversation in #82 , you may need to increate the HTTP timeout.  It seems like the default is 1.5 seconds.  Do you have high latency on the network you are on right now?

**Comment by jamesnogra** [comment]
This only happens maybe 50/50... I also noticed that when the connection is slow, then this error is very common.

**Comment by jamesnogra** [comment]
I added the timeout, 10 seconds, 20 seconds but still the error comes out from time to time. :(

**Comment by robertjd** [comment]
HI @jamesnogra , are you still seeing this problem?  If so I'd like to dig in further.  Could you share the relevant code snippets that show your configuration of the timeout?  Thanks!

**Comment by jamesnogra** [comment]
Yes, I can still see this error. But rarely in the office, common at home. You are right, it's caused by slow internet connection.

```
//this is for okta
const session = require('express-session');
const { ExpressOIDC } = require('@okta/oidc-middleware');

const oidc = new ExpressOIDC({
    issuer: 'https://dev-346920.oktapreview.com/oauth2/default',
    client_id: '0oaczrjeueiua1WMS0h7',
    client_secret: 'culijUMDlOP3_8r9_m8uS7gjr5oKbJebhKqm-yTQ',
    redirect_uri: 'http://localhost:3000/authorization-code/callback',
    scope: 'openid profile'
});

// ExpressOIDC will attach handlers for the /login and /authorization-code/callback routes
app.use(oidc.router);
oidc.on('ready', () => {
//oidc.on('error', err => {
  app.listen(3000, () => console.log('App Started!'));
});
```

This is the Okta related code I have in my app.js

**Comment by jmelberg-okta** [comment]
Hey @jamesnogra - just a [reminder](https://github.com/okta/okta-oidc-js/issues/68#issuecomment-349161310), please do not expose your `client_secret` anywhere public. Please reset your session + `client_secret`, as it has been exposed to anyone watching this repo.

**Comment by jamesnogra** [comment]
Hi @jmelberg-okta that's not my real client_secret :)
I almost cannot work from home (we have a slow internet connection at home) because of this bug.

**Comment by robertjd** [comment]
Hi @jamesnogra , can you show me where you're trying to put in the code that I mention in this comment here: https://github.com/okta/okta-oidc-js/issues/82#issuecomment-356147038

Thanks!

**Comment by robertjd** [comment]
Thanks all, the new 0.1.0 version of this library has set the default timeout to 10 seconds and made it easier to configure.
