### ISSUE TITLE
Warnings about CommonJS or AMD dependencies in Angular 10 

### ISSUE THREAD

**Issue by mraible** [okta/okta-oidc-js#857]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [x] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Install the Okta Angular SDK in an Angular app, then run `npm run e2e`. You'll see errors like the following in your console:

```
WARNING in /Users/mraible/dev/okta/schematics/apps/angular-app/node_modules/
@okta/okta-angular/__ivy_ngcc__/fesm2015/okta-angular.js depends on '@okta/configuration-validation'. 
CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/mraible/dev/okta/schematics/apps/angular-app/node_modules/
@okta/configuration-validation/dist/lib.js depends on 'lodash/merge'. 
CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

## Expected behavior

No warnings after installing the Okta Angular SDK.

## Minimal reproduction of the problem with instructions

I found this when updating [@oktadev/schematics for Angular 10](https://github.com/oktadeveloper/schematics/pull/360).

## Environment

- Package Version: 2.0.0
- Browser: Chrome
- OS: mac
- Node version (`node -v`): v12.16.3

**Comment by swiftone** [comment]
Thanks for the report!

Internal ref: OKTA-320699

**Comment by mraible** [comment]
I used [this guide](https://developer.okta.com/code/angular/okta_angular_sign-in_widget/) to add the Sign-In Widget to an Angular 10 app today. I get some additional warnings after doing it.

```
WARNING in /Users/mraible/ionic-social/src/app/login.component.ts depends on '@okta/okta-signin-widget'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/mraible/ionic-social/node_modules/@okta/okta-angular/__ivy_ngcc__/fesm2015/okta-angular.js depends on '@okta/configuration-validation'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/mraible/ionic-social/node_modules/@okta/okta-signin-widget/dist/js/okta-sign-in.entry.js depends on 'underscore'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in /Users/mraible/ionic-social/node_modules/@okta/configuration-validation/dist/lib.js depends on 'lodash/merge'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

**Comment by aarongranick-okta** [comment]
@mraible Thanks for the info. We are planning on converting configuration-validation to typescript in the near future. This should take care of some of these warnings. The SIW will be a longer term project.

**Comment by mfish0005** [comment]
Awesome good news @aarongranick-okta.  From what I can gather it just means that bundle sizes could be larger if your Angular app has commonjs dependencies.  The doc that the warnings are linking to gives this as a TL;DR: 

> It is recommended that you avoid depending on CommonJS modules in your Angular applications. Depending on CommonJS modules can prevent bundlers and minifiers from optimizing your application, which results in larger bundle sizes. Instead, it is recommended that you use ECMAScript modules in your entire application. For more information, see How CommonJS is making your bundles larger.

**Comment by montyJordanIII** [comment]
@aarongranick-okta   "We are planning on converting configuration-validation to typescript in the near future. This should take care of some of these warnings. The SIW will be a longer term project."

What kind of time frame are we looking at here?
Are there any repercussions of this besides bundle size?

**Comment by mraible** [comment]
These warnings seem to disappear in Angular 11. I used `npm i -g @angular/cli@next` and it installed Angular version `~11.0.0-rc.2`. 

Output when running `npm start` after installing the Oka Angular SDK:

```
> angular-app@0.0.0 start /Users/mraible/dev/okta/schematics/apps/angular-app
> ng serve

✔ Browser application bundle generation complete.

Initial Chunk Files | Names         |      Size
vendor.js           | vendor        |   2.89 MB
polyfills.js        | polyfills     | 141.31 kB
main.js             | main          |  72.56 kB
runtime.js          | runtime       |   6.15 kB
styles.css          | styles        | 119 bytes

                    | Initial Total |   3.10 MB

Build at: 2020-11-09T20:32:34.475Z - Hash: f31e74b14f3f2ef0935d - Time: 6043ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✔ Compiled successfully.
```
