### ISSUE TITLE
Unable to npm install OKTA

### ISSUE THREAD

**Issue by brvinodh** [okta/okta-oidc-js#858]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier

## I'm submitting a:

- [ ] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

npm i @okta/jwt-verifier --cache /tmp/empty-cache

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@okta%2fjwt-verifier - Not found
npm ERR! 404
npm ERR! 404  '@okta/jwt-verifier@^1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\tmp\empty-cache\_logs\2020-08-06T09_41_29_354Z-debug.log

Same error with another package called Winston as well. 
I just wanted to highlight that the install is not working 

Not sure if the npm registry has been compromised or issue with the infrastructure; 

this is a key library and we want to ensure that no one injects malware into it :) (just to be precautious)

## Environment

- Package Version: 1.0.0 
- Browser: 
- OS: WIndows
- Node version (`node -v`): v12.18.2
- Other: VSCODE

**Comment by shuowu** [comment]
@brvinodh I tried to download it locally without any issue. Does this faq from npm help: https://docs.npmjs.com/common-errors#not-found--server-error
