### ISSUE TITLE
TokenStorage option cookie is not setting httponly attributes for the cookies.

### ISSUE THREAD

**Issue by dgangwar** [okta/okta-oidc-js#859]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

I am trying to use the cookie storage option and want to verify that the httpOnly attribute is set for the cookies when a secure flag is passed in the config as mentioned below. I am using the sample okta react app(the sample app(https://github.com/okta/samples-js-react/tree/master/okta-hosted-login).

My Configuration - 
```
oidc: {
    clientId: CLIENT_ID,
    issuer: ISSUER,
    redirectUri: 'http://localhost:8080/implicit/callback',
    scopes: ['openid', 'profile', 'email'],
    pkce: true,
    disableHttpsCheck: OKTA_TESTING_DISABLEHTTPSCHECK,
    tokenManager : {
      secure: true,
      storage: 'cookie',
    },
    cookies: {
      secure: true
   }
  },

## Expected behavior
<!-- Describe what the desired behavior would be. -->


## Minimal reproduction of the problem with instructions
<!--
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem.
You could use one of our sample applications to build a reproduction demo: https://github.com/okta?q=samples-js
-->

## Extra information about the use case/user story you are trying to implement
<!-- Describe the motivation or the concrete use case. -->


## Environment

- Package Version: 3.0.2
- Browser: Chrome
- OS: Mac
- Node version (`node -v`): v12.14.1
- Other:

**Comment by swiftone** [comment]
okta-react is a front-end JS package that needs to set and consume the token, and therefore cannot use the 'httpOnly' flag that would prevent JS from using that cookie.  

I'm not aware of any frontend JS OIDC libraries (from Okta or elsewhere) that would be able to do this - you would have to set the cookie via a server, and said cookie would only be usable with that one server.  If you are looking to store the token for use with a single server, I would recommend looking into backend libraries to do this - Okta has a variety to pick from in several languages: 

https://developer.okta.com/docs/
