### ISSUE TITLE
Okta Vue authorization code flow bug

### ISSUE THREAD

**Issue by plin-prog** [okta/okta-oidc-js#862]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [x] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
There's a bug during the authorization flow when a user logs onto the application after not having logged in for a while (say overnight).  The authorization flow errors out on the POST request to obtain tokens and the application is stuck on the /implicit/callback route.

If the user refreshes, this issue doesn't occur again (until the user tries logging on after a while - I've been able to reproduce this when logging on for the first time each morning).

## Expected behavior
The user logs on without the authorization flow failing.

## Minimal reproduction of the problem with instructions
1) After 6+ hours, log on to the application
2) Attempt to access a protected route
3) After being redirected to the Okta sign-in widget, enter credentials.
3) After entering valid credentials, the user is redirected to the /implicit/callback route with the authorization code in the url.
4) The POST request for token errors out with a 400 and the user is stuck on the /implicit/callback route. Error message:  { error: "invalid_grant", error_description: "PKCE verification failed." }

## Environment

- Package Version: "@okta/okta-vue": "^2.0.0"
- Browser: Chrome
- OS: macOS Mojave v10.14.6
- Node version (`node -v`): v10.16.3

**Comment by plin-prog** [comment]
Is this similar to https://github.com/okta/okta-oidc-js/issues/804?

I've seen recommendations to override **onSessionExpired**.  Is this reliable? I'm reading this method is being deprecated.

**Comment by shuowu** [comment]
@plin-prog The suggestion would be to override the `onSessionExpired` callback to a no-op (`() => {}`) function to avoid login concurrency issue (same as deprecate). Currently the default behavior is to try to auto-login, which causes issue.

We will also update the `okta-vue` SDK with the latest `auth-js` SDK to make sure it behaves correctly by default.

**Comment by plin-prog** [comment]
Thank you for confirming that this is still the recommended workaround.  I'll try this and report back.

**Comment by plin-prog** [comment]
@shuowu This solution appears to be working!  If this error happens again, I will reopen a ticket.  Thank you!

**Comment by JWilliamsGH** [comment]
@shuowu Was this resolved with the latest update or is this still the recommended workaround?

**Comment by shuowu** [comment]
@JWilliamsGH The default behavior has been removed in the latest release. As the workaround is just to override the default behavior, you can safely remove it now (keep it in code with no touch is also fine).

**Comment by JWilliamsGH** [comment]
@shuowu Thanks for that. We're experiencing a similar issue on the latest release. I was hunting around for possible solutions and just wanted to check if this was still a possible solution.
