### ISSUE TITLE
onAuthRequired has undefined router when using Ionic

### ISSUE THREAD

**Issue by mraible** [okta/okta-oidc-js#864]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [x] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

I'm trying to use [the Okta Sign-In Widget and Angular guide](https://developer.okta.com/code/angular/okta_angular_sign-in_widget/) to add authentication to an Ionic app. My `app-routing.module.ts` looks as follows:

```ts
import { NgModule } from '@angular/core';
import { PreloadAllModules, RouterModule, Routes } from '@angular/router';
import { ProtectedComponent } from './protected.component';
import { LoginComponent } from './login.component';

import {
  OKTA_CONFIG,
  OktaAuthModule,
  OktaCallbackComponent,
  OktaAuthGuard
} from '@okta/okta-angular';

const config = {
  issuer: 'https://dev-133320.okta.com/oauth2/default',
  redirectUri: 'http://localhost:4200/callback',
  clientId: '0oa55giv775Ul3LHL357',
  pkce: true
}

export function onAuthRequired({ oktaAuth, router }) {
  console.log('oktaAuth', oktaAuth)
  console.log('router', router)
  // Redirect the user to your custom login page
  router.navigate(['/login']);
}

const routes: Routes = [
  {
    path: '',
    loadChildren: () => import('./tabs/tabs.module').then(m => m.TabsPageModule)
  },
  {
    path: 'callback',
    component: OktaCallbackComponent
  },
  {
    path: 'login',
    component: LoginComponent
  },
  {
    path: 'protected',
    component: ProtectedComponent,
    canActivate: [ OktaAuthGuard ],
    data: {
      onAuthRequired
    }
  }
];

@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules }),
    OktaAuthModule
  ],
  providers: [
    { provide: OKTA_CONFIG, useValue: config },
  ],
  exports: [RouterModule]
})
export class AppRoutingModule {}
```

When I click on the `Protected` link, I expect that I'd be routed to `/login`. Instead, the `router` is undefined and the following error gets printed to my console.

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'navigate' of undefined
```

## Expected behavior

`router` is resolved.

## Minimal reproduction of the problem with instructions

```
git clone git@github.com:oktadeveloper/okta-ionic-social-login-example.git
cd okta-ionic-social-login-example
npm i
npm start
```

Go to `http://localhost:4200` and click the **Protected** link.

## Extra information about the use case/user story you are trying to implement

I'm trying to see if you can embed the Sign-In Widget in an Ionic app.

See [this commit](https://github.com/oktadeveloper/okta-ionic-social-login-example/commit/9d35867926d9e2ed94e708890871baa196015a64) to see the code I added to upgrade to Angular 10 and add the Sign-In Widget.

## Environment

- Package Version: 2.1.0
- Browser: Chrome
- OS: macOS
- Node version (`node -v`): v14.8.0

**Comment by aarongranick-okta** [comment]
The logic is implemented here: https://github.com/okta/okta-signin-widget/blob/master/src/util/OAuth2Util.js#L75

It may be possible to bypass this logic via authParams so that it performs the logic here: https://github.com/okta/okta-signin-widget/blob/master/src/util/OAuth2Util.js#L83

Or you can skip the entire OAuth2 token flow in the SIW and call `getWithoutPrompt` yourself in the success callback. The `getTokens` flow is enabled based on the `oauth2Enabled` setting: https://github.com/okta/okta-signin-widget/blob/master/src/util/RouterUtil.js#L155 which is defined here: https://github.com/okta/okta-signin-widget/blob/master/src/models/Settings.js#L227

It looks like if you don't pass a `clientId` param then it will perform login and pass a sessionToken to your sucessCallback. Then in the callback you can call `authClient.token.getWithoutPrompt` passing the clientId and sessionToken

**Comment by mraible** [comment]
It looks like the [README](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-angular#using-a-custom-login-page) has it correctly:

```
export function onAuthRequired(oktaAuth, injector) {
  // Use injector to access any service available within your application
  const router = injector.get(Router);

  // Redirect the user to your custom login page
  router.navigate(['/custom-login']);
}
```

[This documentation](https://developer.okta.com/code/angular/okta_angular_sign-in_widget/) needs updating.

**Comment by aarongranick-okta** [comment]
Internal ref: OKTA-323249

**Comment by sdunnin** [comment]
I'm not using Ionic but am having a similar issue. With an onAuthRequired function added into my Okta Config I am seeing  the second parameter passed to that callback function being undefined just as mraible did.

I upgraded the okta-angular package in my project from 1.4 to 2.2 just to make sure something hadn't been fixed in a newer version.

**Comment by shuowu** [comment]
@sdunnin Does this comment help? https://github.com/okta/okta-oidc-js/issues/864#issuecomment-675174729

**Comment by sdunnin** [comment]
@shuowu No it does not. Doesn't matter what you call the 2nd parameter (router vs injector) it is still undefined when the function is called.

**Comment by shuowu** [comment]
@sdunnin I tried the latest version locally, looks like the second parameter is there. Also, based on the search result https://github.com/okta/okta-oidc-js/search?q=onAuthRequired+path%3Apackages%2Fokta-angular%2Fsrc&type=Code, all usages have the 2nd parameter properly passed.  

I saw it appears in some sample code as `onAuthRequired: ({oktaAuth, router}) ...`, which should be `onAuthRequired(oktaAuth, injector) ...` (without the `{}`).

**Comment by sdunnin** [comment]
Here are some code snippets and a screen-shot of console.log statements

```
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { Router } from '@angular/router';
import {
  OktaAuthModule,
  OktaAuthService,
  OKTA_CONFIG
} from '@okta/okta-angular';

import { oktaConfig } from '../environments/okta-config';

import { AuthRoutingModule } from './auth-routing.module';
import { AuthMethod } from './auth.injection-token';

const oktaConfig2 = {
  ...oktaConfig,
  ...{
    onAuthRequired: (
      { oktaAuth }: { oktaAuth: OktaAuthService },
      { router }: { router: Router }
    ) => {
      console.log('router', router);
      console.log('oktaAuth', oktaAuth);
      return;
      // void router.navigate(['/login']);
    }
  }
};

@NgModule({
  imports: [CommonModule, AuthRoutingModule, OktaAuthModule],
  exports: [AuthRoutingModule],
  providers: [
    { provide: AuthMethod, useValue: 'okta' },
    { provide: OKTA_CONFIG, useValue: oktaConfig2 }
  ]
})
export class AuthOktaModule {}
```

**okta-config**
```
export const callbackUrl = 'implicit/callback';
export const oktaDomain = '*********.okta.com';

export const oktaConfig = {
  issuer: `https://${oktaDomain}/oauth2/default`,
  redirectUri: `http://localhost:4200/${callbackUrl}`,
  clientId: '**********************',
  pkce: true,
  scopes: ['openid', 'profile'],
};
```
After calling `OktaAuthService.login()` from elsewhere in the code I get the following log messages:

![image](https://user-images.githubusercontent.com/1950736/92531376-c274c180-f1f3-11ea-806d-e01b3b4997bd.png)

**Comment by aarongranick-okta** [comment]
@sdunnin See @shuowu comment: https://github.com/okta/okta-oidc-js/issues/864#issuecomment-687334054

`onAuthRequired` takes 2 arguments. The first agument is the instance of the Okta Auth service for Angular. The second argument is the injector which you can use to get any other object in the system.

**Comment by sdunnin** [comment]
Sorry, but still not seeing the point. I do not call onAuthRequired explicitly from my application code. It is called somewhere from within the okta-angular library and I have no control over that unless I am missing something. It doesn't matter if I look for an instance of router or an instance of injector when referenced the parameter is undefined.

**Comment by sdunnin** [comment]
Sorry for the noise in this issue, I had bad Typescript declarations on the onAuthRequired paramaters. After correcting it is working as expected with Injector passed in for 2nd arg.

**Comment by aarongranick-okta** [comment]
@sdunnin Glad you were able to get it working! We will update the documentation to make it more clear.

**Comment by mraible** [comment]
Fixed by https://github.com/okta/okta-developer-docs/pull/1439.
