### ISSUE TITLE
AuthSdkError: Unable to retrieve OAuth redirect params cookie

### ISSUE THREAD

**Issue by pbollaram** [okta/okta-oidc-js#870]
## I'm submitting this issue for the package(s):
- [ x] okta-react

## I'm submitting a:

- [x ] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Expected behavior
i am continuously getting "AuthSdkError: Unable to retrieve OAuth redirect params cookie" error when i am trying to login using OKTA SSO.
it was working earlier and started seeing this issue all of sudden. 
i have tried following
1. reinstalling/ deployed app. did not work.
2. upgraded to latest @okta/okta-react: 3.0.4. but of no use( surprisingly working on my local but i see this issue in production server).

## Extra information about the use case/user story you are trying to implement
configuration that i have used is: 
 
const config = {
    issuer: `${process.env.REACT_APP_OKTA_ORG_URL}`,
    redirect_uri: `${window.location.origin}/implicit/callback`,
    client_id: process.env.REACT_APP_OKTA_CLIENT_ID,
    scope: ['openid', 'profile', 'email', 'groups'],
    pkce: true,
  };

<Security {...config}> <somecomponent /> </Security>

## Environment

- Package Version:
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by aarongranick-okta** [comment]
@pbollaram Can you provide extra information about the Browser/OS? Do you see the behavior on all browsers? Does the issue happen every time or is it intermittent?

**Comment by pbollaram** [comment]
chrome Version 84.0.4147.125 .
Mac OS  Version 10.14.6

**Comment by pbollaram** [comment]
this is not intermittent i would say. from last few days this is happening continuously.

**Comment by aarongranick-okta** [comment]
@pbollaram Does it work in Firefox and/or Safari? Does the issue only happen on Chrome? And to confirm, you said it does not happen when running locally, but only when deployed in production?  If possible could you send more information, such as a network log (https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting) to devex@okta.com so we can analyze it.

**Comment by pbollaram** [comment]
I do not see this issue with Safari. The App working normal. 
sure sending you .har file

**Comment by aarongranick-okta** [comment]
This could be related: https://www.chromium.org/updates/same-site Is your site running on `https` or `http` protocol?

**Comment by pbollaram** [comment]
we are running this app with protocol **http** since we are still at dev stage ( changing it to https is in our TODO list).
i have enabled the IP address of the app as secured by running this **chrome://flags/#unsafely-treat-insecure-origin-as-secure** in chrome browser and testing the app.

**Comment by aarongranick-okta** [comment]
The issue may be that "secure" cookies are being set incorrectly. Our code detects http/https based on `window.location.protocol` and sets this value automatically. However, you can set this value explicitly. https://github.com/okta/okta-auth-js#additional-options

I'm not sure which value is correct in your case, but I think maybe setting `cookies.secure` to false may work:

```
{
 // other okta-auth-js config, issuer, etc ....
  cookies {
    secure: false
  }
}
```
Alternatively, since the browser will be treating this domain as secure, maybe explicitly setting the value to `true` will overcome this issue.

As you can see here: https://www.chromium.org/updates/same-site Chrome has some specific rules about "Same-Site" and secure cookies, which other browsers do not follow.

**Comment by aarongranick-okta** [comment]
Here is the relevant piece of code on our side: https://github.com/okta/okta-auth-js/blob/master/lib/browser/browser.ts#L71 It may help to debug through it in your browser (we do provide external sourcemaps which can be used by your app using the `source-map-loader` webpack plugin)

**Comment by aarongranick-okta** [comment]
Reading through the code I'm guessing you will see the warning about running on HTTPS and then cookieSettings.secure will be set to false. However the 'sameSite' value will still be 'none'. I think setting `cookies.secure` explicitly to false should fix this by automatically setting `sameSite` to `lax`

**Comment by pbollaram** [comment]
having below piece of code is working for me. hopefully i can remove this when we enable https. is it?

 {
 // other okta-auth-js config, issuer, etc ....
  cookies {
    secure: false
  }
}

**Comment by aarongranick-okta** [comment]
@pbollaram Yes we recommend removing it when enabling https. You could also make it conditional:
```
secure: window.location.protocol === 'https:' ? true : false
```
I have created an internal issue to adjust the logic on our end to set `sameSite` to `lax` when we autodetect http domains so this workaround should not be necessary in the future.

Internal Ref: OKTA-323826

**Comment by pbollaram** [comment]
Great. I will go ahead and keep this change for now.
