### ISSUE TITLE
Missing dist folder for okta-vue

### ISSUE THREAD

**Issue by gaastonsr** [okta/okta-oidc-js#88]
I'm trying to use the SDK for vue but it's missing the dist files. Can we please update the package :)

<img width="190" alt="screen shot 2018-01-10 at 5 32 31 pm" src="https://user-images.githubusercontent.com/2997285/34801084-4abed20e-f62c-11e7-855a-9c3892ed1d51.png">

Thanks!

**Comment by jmelberg-okta** [comment]
@gaastonsr Thanks for the heads up! Not sure how I missed that one. :)

Version `0.0.3` is now published to npm.

**Comment by gaastonsr** [comment]
Works beautifully! thanks!
