### ISSUE TITLE
withOktaAuth not injecting any props in TypeScript component

### ISSUE THREAD

**Issue by sethen** [okta/okta-oidc-js#913]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ x] okta-react
- [ ] okta-react-native

## I'm submitting a:

- [x ] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Using `withOktaAuth` with my TypeScript component does not actually add anything to the props.  I don't know if this is because I am using TypeScript or not.  I tried to use a vanilla component straight up and still the problem persisted.  I copy and pasted the code from the documentation and it still did not work.

## Expected behavior

`withOktaAuth` should work as described in the documentation.

## Minimal reproduction of the problem with instructions

```typescript
import * as React from 'react';
import { Button } from 'antd';
import { withOktaAuth } from '@okta/okta-react';
import { PROVIDERS } from 'sonar-ts-constants';

interface OktaReactProps {
	issuer: string;
	oidcClientID: string;
	authService: any;
}

class Okta extends React.Component<OktaReactProps> {
	constructor(props: OktaReactProps) {
		super(props);

		this.state = {};
	}

	render() {
		console.log(this.props.authService); // this is undefined at runtime

		return (
			<div id='okta'>
				<Button type='primary'>okta</Button>
			</div>
		);
	}
}
export default withOktaAuth(Okta);
```

## Environment

- Package Version: `@okta/okta-auth-js": "^4.0.0"` and `@okta/okta-react": "^3.0.7"`
- Browser: Chrome
- OS: Ubuntu 20.04
- Node version (`node -v`): v12.18.4
- Other:

**Comment by swiftone** [comment]
@sethen - Thanks for the report

I believe the issue is that you're using okta-auth-js 4.x - okta-react hasn't updated to that yet.

Side note: okta-auth-js 4.x actually pulls a lot of features from okta-react into itself

okta-react 3.0.7 makes use of okta-auth-js 3.x only - can you see if that resolves your issue?

**Comment by sethen** [comment]
@swiftone Thanks for getting back to me so quickly, appreciate that.

I changed my dependencies to the following:

```
    "@okta/okta-auth-js": "^3.2.3",
    "@okta/okta-react": "^3.0.7",
```

`this.props.authService` is still `undefined` when trying to access it using `withOktaAuth`

**Comment by swiftone** [comment]
@sethen - 

Huh.  Is this Okta component used "inside" (as a descendant of) `<Security>`?  That's the component that instantiates `authService`.

**Comment by sethen** [comment]
@swiftone 

Ah, I see.  No we are not and the reason being is because the way the app is currently set up using a overarching `Security` route isn't exactly feasible for us.  If I need that route to make the code work, then I will have to just use the JavaScript SDK instead and try and figure out that other issue I logged.

**Comment by swiftone** [comment]
@sethen - Take a peek at the `<Security>` code (https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/src/Security.js) 

It's is fairly simple (it is just a Provider for the authService context) so you may be able to use AuthService without Security, you'll just have to manage triggering the initial setting of state and have a provider to pass your AuthService along.

That should be more simple than going directly to okta-auth-js, though that would certainly work too.

**Comment by sethen** [comment]
> @sethen - Take a peek at the `<Security>` code (https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/src/Security.js)
> 
> It's is fairly simple (it is just a Provider for the authService context) so you may be able to use AuthService without Security, you'll just have to manage triggering the initial setting of state and have a provider to pass your AuthService along.
> 
> That should be more simple than going directly to okta-auth-js, though that would certainly work too.

It's fine, I should be able to use the JS SDK if we can get past that piece I logged.  It's actually better for me as well as I can have more control over the pieces.
