### ISSUE TITLE
<LoginCallback> returns "AuthSdkError: Unable to retrieve OAuth redirect params storage"

### ISSUE THREAD

**Issue by Joyeeta** [okta/okta-oidc-js#923]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [X] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native

## I'm submitting a:

- [X ] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

I am using "@okta/okta-signin-widget": "^3.8.2" and "@okta/okta-angular": "^2.0.0", which has a dependency "okta-auth-js": 3.2.4. The application was running fine until it started showing some "AuthSDKError" since 4 days ago.  I have specified storage as 'localStorage' while initializing "OktaAuth" ,
const athClient = new OktaAuth({
url: 'XXX',
redirectUri: redirectUri,
responseMode: 'query',
pkce: true,
tokenManager: {
storage: 'localStorage',
expireEarlySeconds: 300
}
});
While debugging,i noticed in token.js it is trying to read the okta-oauth-redirect-params from the sessionStorage rather than localStorage. I see a blank callback html, which displays the error in console: AuthSdkError: Unable to retrieve OAuth redirect params from storage.

## Expected behavior

It should redirect me to my application which I should see after login.

## Minimal reproduction of the problem with instructions

I have noticed it across all major browsers and operating systems. And this is happening in the latest version of "@okta/okta-angular" as well. Get the oktaAuth configured, login, and you should see this.

## Environment

- Package Version: "@okta/okta-angular": "^2.X.X",
- Browser: Chrome, Safari, FF
- OS: MAC, Windows 10
- Node version (`node -v`): 12.16.2
- Other:

**Comment by aarongranick-okta** [comment]
@Joyeeta Thanks for the submission. We have identified a flaw in okta-auth-js@3.2.4 which we are fixing now.

**Comment by aarongranick-okta** [comment]
@Joyeeta We have released version 3.2.5 which should correct this flaw

**Comment by Joyeeta** [comment]
Thanks @aarongranick-okta

**Comment by hellmean** [comment]
we are still experiencing this error with version 4.6.1:
```
Uncaught (in promise) AuthSdkError: Unable to retrieve OAuth redirect params from storage
```
