### ISSUE TITLE
using @okta/okta-react-native . In android app is not getting redirected back from okta login page. After Sign click on browser it stays there.  

### ISSUE THREAD

**Issue by shweta-itilite** [okta/okta-oidc-js#925]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Environment

- Package Version:
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by aarongranick-okta** [comment]
@shweta-itilite thanks for the submission. Are you able to see any messages in the browser console? https://developer.android.com/guide/webapps/debugging

**Comment by shweta-itilite** [comment]
Thanks for responding. No, I cannot see any message in browser console. signInSuceess event is not triggered after successful signIn in android but same function is working n iOS.

**Comment by shweta-itilite** [comment]
I have installed using yarn add @okta/okta-react-native. Did the configuration as per README.

**Comment by shweta-itilite** [comment]
![Uploading Screenshot 2020-10-01 at 12.08.53 AM.png…]()

**Comment by robertjd** [comment]
Hi @shweta-itilite , can you compare your application to our sample applications, these are working examples of how to achieve login with react native: https://github.com/okta/samples-js-react-native

**Comment by shweta-itilite** [comment]
Hi Robert, I have compared the application used it in the same way.Your sample application is working fine but cannot figure out why is is not working in my app.  I will listen the steps I have followed. It is redirecting me to okta page but not getting me back after login. Please help me if I am missing anything.
1) yarn add @okta/okta-react-native
2) added in android/build.gradle maven {
            url("https://dl.bintray.com/okta/com.okta.android")
        } 
3) manifestPlaceholders.appAuthRedirectScheme='callback url'

**Comment by shweta-itilite** [comment]
Hi, The issue has been resolved. It was very small issue. I was using part of callback URL in Capital letter which was creating problem. Please do mention the same in the official document. Although It is small things but, fresher like me or anyone without experience may fail to observe this. Thanks.

**Comment by oleggnidets-okta** [comment]
The comment above provides a solution.

Thanks for using Okta!
