### ISSUE TITLE
okta-oidc-js error in documentation on how to work with Proxies

### ISSUE THREAD

**Issue by jespersoderlund** [okta/okta-oidc-js#930]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [x] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
The documentation specifies a way to get the module to work with HTTP-proxies that is not supported (any longer) by the dependency being used.

The package dependency on "openid-client" is version 3.x. Version 3.x dropped support for the 'request' module as a breaking change which is the documented way to get proxy to work with okta-oidc-js middleware. Now the only supported http package is 'got' but I haven't found a way to configure this through the okta-oidc-js eventhough the 'got' module itself supports proxying.

## Expected behavior
Being able to use okta-oidc-js through a HTTP proxy.

## Minimal reproduction of the problem with instructions

const {Issuer} = require('openid-client')
Issuer.useRequest()

This will cause an error

## Environment

- Package Version: 4.0.1
- Browser: N.A.
- OS: MacOS
- Node version (`node -v`): 12
- Other:

**Comment by shuowu** [comment]
@jespersoderlund Thanks for reporting the issue! Looks like you have found the related issue (#685). 

Internal ref: OKTA-282367

**Comment by shuowu** [comment]
Doc has been updated in #931
