### ISSUE TITLE
SecureRoute is not passing Router props to my component

### ISSUE THREAD

**Issue by pbollaram** [okta/okta-oidc-js#933]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [x] okta-react
- [ ] okta-react-native

## I'm submitting a:

- [x ] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
i have downloaded latest @okta-react v3.0.8 and i still not able to access routing props in my component.
code that i am using is below:

## <SecureRoute path="/notifications" component={Notifications} />
![image](https://user-images.githubusercontent.com/65185492/96922113-49a88c80-1464-11eb-987c-13e7bc9758d9.png)

and in my component i am just printing console.log(props) which is giving me output of empty object {}.

tried with withRouter as suggested by someone on the page https://github.com/okta/okta-oidc-js/issues/724 and i am still facing same issue.

## <SecureRoute path="/notifications" component={withRouter(Notifications)} />
![image](https://user-images.githubusercontent.com/65185492/96922055-34cbf900-1464-11eb-9323-1db04f6818c9.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/65185492/96921597-a0fa2d00-1463-11eb-8e7a-d0f87326d24e.png)

## Environment

- Package Version: 3.0.8
- Browser: Chrome
- OS: Mac Os Mojave
- Node version (`node -v`):
- Other:

**Comment by aarongranick-okta** [comment]
@pbollaram I tried to reproduce this issue using the `okta-hosted-login` sample here: https://github.com/okta/samples-js-react/tree/master/okta-hosted-login

I modified the "Profile" component to log the props that it receives:

https://github.com/okta/samples-js-react/compare/ag-repro-gh-933?expand=1

I did see the router props logged out as expected:

<img width="667" alt="Screen Shot 2020-10-22 at 1 06 51 PM" src="https://user-images.githubusercontent.com/47947204/96924418-7a3df580-1467-11eb-8cd1-2949e537a4a5.png">

Is it possible your `Notifications` component is being wrapped in some way, maybe by a higher-order component which is not passing the props through?

**Comment by pbollaram** [comment]
Oh Yes. @aarongranick-okta . i almost forgot that and looking for router props in completely wrong place. Thanks for correcting me. Closing the issue.
