### ISSUE TITLE
security vulnerabilities from lodash

### ISSUE THREAD

**Issue by faizhasim** [okta/okta-oidc-js#934]
## I'm submitting this issue for the package(s):

- [x] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

we run security scan for all dependencies and we found out that jwt-verifier is using lodash which contains multiple high level vulnerabilities from our scan:

- https://snyk.io/vuln/SNYK-JS-LODASH-450202

![image](https://user-images.githubusercontent.com/898384/97064088-37e6f680-15d6-11eb-9211-b34b1423e540.png)

- https://snyk.io/vuln/SNYK-JS-LODASH-590103

![image](https://user-images.githubusercontent.com/898384/97064140-7e3c5580-15d6-11eb-9594-7b4e78413a24.png)

- https://snyk.io/vuln/SNYK-JS-LODASH-608086

![image](https://user-images.githubusercontent.com/898384/97064109-5e0c9680-15d6-11eb-85c5-406940651dfb.png)

- https://snyk.io/vuln/SNYK-JS-LODASH-73638

![image](https://user-images.githubusercontent.com/898384/97064160-8f856200-15d6-11eb-9a13-35659fb5e236.png)

from the look of it, you can try to upgrade your `jwks-rsa` to latest version which is released 8 hours ago. seems like the auth0 folks updated already address this issue at https://github.com/auth0/node-jwks-rsa/issues/86 last year.

i honestly feel that you should expedite this due to security concerns.

## Expected behavior

for all the reported vulnerabilities to be fixed

## Environment

- Package Version:
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by swiftone** [comment]
@faizhasim - Thanks for the detailed report, we'll dig into it.

**Comment by faizhasim** [comment]
Thanks for the fix.
