### ISSUE TITLE
done is not a function in oidcUtils.bootstrapPassportStrategy 

### ISSUE THREAD

**Issue by mayankgupta0510** [okta/okta-oidc-js#936]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [X] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native

## I'm submitting a:

- [X] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

Currently I am trying to use oidc-middleware library (version -> 4.0.1), and after configuring the ExpressOIDC i.e.

const oidc = new ExpressOIDC({
		issuer: ias_serv.credentials.url,
		client_id: ias_serv.credentials.clientId,
		client_secret: ias_serv.credentials.Secret,
		appBaseUrl: domainURL,
		scope: "openid",
		loginRedirectUri: domainURL + "/login/callback",
		response_type: "code",
	});

	app.use(
		session({
			secret: "dummy-cookie-secret",
			resave: true,
			saveUninitialized: false,
		})
	);

	app.use(oidc.router);
oidc.on("ready", () => {
		app.listen(port, () => {
			console.log("We are live on " + port);
		});
	});

after successfully login, I am getting error from bootstrapPassportStrategy i.e. done is not a function, when I debugged i found out bootstrapPassportStrategy function using userToken as parameter which does not exists in openid-connect lib.

oidcUtil.bootstrapPassportStrategy = context => {
  const oidcStrategy = new OpenIdClientStrategy({
    params: {
      scope: context.options.scope
    },
    sessionKey: context.options.sessionKey,
    client: context.client
  }, (tokenSet, userInfo, done) => {
    console.log(done);
    return tokenSet && userInfo
      ? done(null, {
        tokens: tokenSet
      })
      : done(null);
  });

After i removed the userInfo parameter and just using tokenSet and done it works fine.
i believe you have to update openid-connect library version in package.json and use the latest one.

Can you please help me to understand is it an existing issue ?

please help.

**Comment by swiftone** [comment]
Internal ref: OKTA-341568

**Comment by mayankgupta0510** [comment]
Sorry i think , i didnt explain the problem properly, so i using oidc-middleware -> version 4.0.1 and my code snippet is 

const oidc = new ExpressOIDC({
		issuer: ias_serv.credentials.url,
		client_id: ias_serv.credentials.clientId,
		client_secret: ias_serv.credentials.Secret,
		appBaseUrl: domainURL,
		scope: "openid",
		loginRedirectUri: domainURL + "/login/callback",
		response_type: "code",
		response_mode: "form_post",
	});

	app.use(
		session({
			secret: "dummy-cookie-secret",
			resave: true,
			saveUninitialized: false,
		})
	);

	app.use(oidc.router);

	app.use(function (req: any, res: any, next: Function) {
		if (!req.userContext && req.url == "/") {
			console.log("login");
			res.redirect("/login");
			return;
		} else {
			app.use("/", routes);
		}
		next();
	});

	app.get("/login", oidc.ensureAuthenticated());

	app.get("/login/callback", (req, res, next) => {
		res.redirect("/home");
		next();
	});

	const port = process.env.PORT || 3000;
	oidc.on("ready", () => {
		app.listen(port, () => {
			console.log("We are live on " + port);
		});
	});

after successfully authentication it redirects to /login/callback and it gives an error stating "done is not a function" from oidcUtils.bootstrapPassportStrategy line 91.

**Comment by mayankgupta0510** [comment]
i believe there is already PR raised for this issue https://github.com/okta/okta-oidc-js/pull/372,
to update oidcUtil to allow a callback without userinfo
can you please confirm whether this fix is valid or not ?

**Comment by robertjd** [comment]
HI @mayankgupta0510 , we have this on our board to look at next week, including reviewing the PR above.  Are you blocked while we investigate or have you been able to workaround by using the code in the PR?  Thanks!

**Comment by mayankgupta0510** [comment]
Hi Robert,
Actually I am totally block with this issue, I am able to use the above PR code but I cannot use that for my production code.
Please can you take up this on priority, we have our Dev close on 4th November.

Thanks,
Mayank

**Comment by mayankgupta0510** [comment]
Hello Team, Robert,

any updates on this please?

**Comment by aarongranick-okta** [comment]
@mayankgupta0510 I am reviewing the code changes. So far they look good and we should be able to get them integrated. If I understand the issue properly, it is that your IDP does not support the "profile" scope which would normally provide the userinfo? And without the userinfo object, the number of parameters is changed, leading to this error.

**Comment by mayankgupta0510** [comment]
"it is that your IDP does not support the "profile" scope which would normally provide the userinfo? And without the userinfo object, the number of parameters is changed, leading to this error."

Mayank >> Yes that's exactly the problem.
could you please let me know in which release version or beta version this fix will be available since we are waiting for this fix for our release.

**Comment by mayankgupta0510** [comment]
Hello,
can you please let me know when will you release this fix?

**Comment by oleksandrpravosudko-okta** [comment]
hello @mayankgupta0510 - I am getting https://github.com/okta/okta-oidc-js/pull/372 ready to merge - it should be good to go in the next few days
the release date have not been set yet but it is likely to happen soon

**Comment by oleksandrpravosudko-okta** [comment]
@mayankgupta0510 - FYI, fix has been released in v4.0.2
