### ISSUE TITLE
Angular SDK doesn't work with Ionic because of Router dependency

### ISSUE THREAD

**Issue by lboyette-okta** [okta/okta-oidc-js#94]
Copied from https://github.com/okta/okta-auth-js/issues/84

Ionic uses a NavController instead of Angular Router. Attached is the error that happens when you try to use Okta's Angular SDK in an Ionic project.

![Okta Angular SDK Error](https://user-images.githubusercontent.com/17892/34996021-838dce60-fa95-11e7-85d5-c78d327db1ae.png)

**Comment by mraible** [comment]
I believe you can close this. Ionic 4 works with [Ionic AppAuth](https://github.com/wi3land/ionic-appauth#readme) and we offer support for that via @oktadev/schematics. https://github.com/oktadeveloper/schematics#ionic
