### ISSUE TITLE
Security vulnerability in jwks-rsa's dependency

### ISSUE THREAD

**Issue by melanopsis** [okta/okta-oidc-js#970]
## I'm submitting this issue for the package(s):

- [x] jwt-verifier
- [ ] oidc-middleware

## I'm submitting a:

- [ ] Bug report  
- [ ] Feature request
- [x] Other (Describe below)

Security vulnerability in axios (https://www.npmjs.com/advisories/1594) which is a dependency of jwks-rsa. Upgrade jwks-rsa to v.1.12.1 or above. 

`npm audit` output

![image](https://user-images.githubusercontent.com/620072/105922961-800c1f80-5ff0-11eb-925e-cd148d0b5357.png)

**Comment by shuowu** [comment]
@melanopsis Thanks for the report.

Internal Ref: OKTA-365079

**Comment by sooryaprakash99** [comment]
@oleksandrpravosudko-okta  I am using latest version @okta/jwt-verifier  v2.3.0. In that it has jwks-rsa dependency which uses the axios version v0.21.1. 

Axios v0.21.1 has security issues.
May I know when will the dependency node module will be updated.

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for bringing this to our attention @sooryaprakash99. It looks like [`0.21.1`](https://snyk.io/vuln/npm:axios@0.21.1) vuln was not known at the time previous fix was applied.

I'll log another ticket to have this resolved:
Internal Ref: OKTA-432584

**Comment by ashokkumarsundar** [comment]
This is not fixed yet, when we can expect this fix?

**Comment by jaredperreault-okta** [comment]
@ashokkumarsundar `okta-jwt-verifier` has moved to it's own repo and requires `axios` `0.21.2` or higher

https://github.com/okta/okta-jwt-verifier-js/blob/master/package.json#L44

```
jared:jwt-verifier$ yarn why axios
yarn why v1.22.17
[1/4] 🤔  Why do we have the module "axios"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "axios@0.21.4"
info Reasons this module exists
   - "jwks-rsa" depends on it
   - Hoisted from "jwks-rsa#axios"
info Disk size without dependencies: "512KB"
info Disk size with unique dependencies: "560KB"
info Disk size with transitive dependencies: "560KB"
info Number of shared dependencies: 1
✨  Done in 0.36s.
```
