### ISSUE TITLE
Server-side request forgery

### ISSUE THREAD

**Issue by Nawazsherif** [okta/okta-oidc-js#972]
## I'm submitting this issue for the package(s):

- jwt-verifier

## I'm submitting a Bug Fix:

Please fix server-side request forgery from your side

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for reporting this @Nawazsherif.

In case you are referring to [reported transitive dependency](https://github.com/okta/okta-oidc-js/issues/970) vulnerability, its [fix](https://github.com/okta/okta-oidc-js/pull/971) and release are underway.  Please let us know if there is a different source of vulnerability you are aware of.

**Comment by Nawazsherif** [comment]
This is what I am exactly looking for. Thanks for the quick response. 
Expecting the patch soon.

**Comment by oleksandrpravosudko-okta** [comment]
Released in v2.0.1
