### ISSUE TITLE
Creating Multiple OIDC instances in Nodejs('@okta/oidc-middleware')

### ISSUE THREAD

**Issue by ramkarthik77** [okta/okta-oidc-js#974]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [x] oidc-middleware

## I'm submitting a:

- [ ] Bug report  
- [x] Feature request
- [x] Other (Describe below)

## Environment

- Package Version:
- Browser:
- OS:
- Node version (`node -v`):
- Other:

**Comment by ramkarthik77** [comment]
I've implemented authentication for an application using @okta/oidc-middleware in node.js. It is working as expected. Now I got a requirement to add one more application that shares the same client and secret. How to implement 2 apps like abc.com/user-login, bcd.com/user-login in node js using @okta/oidc-middleware

**Comment by denysoblohin-okta** [comment]
Thank you for the question.  Can you be more specific about your problem? 
In Okta Dashboard you can specify multiple redirect URIs in your application settings as well as multiple domains for CORS.

**Comment by ramkarthik77** [comment]
I have configured multiple redirect uri's in okta dashboard. The issue that i'm facing here is since i'm using @okta oidc middleware i was trying to create mutliple OIDC instances. Can you share me an example how i can create mutliple oidc instances in nodejs.
Regards 
Karthik Guduri.

**Comment by aarongranick-okta** [comment]
@ramkarthik77 There is some discussion and a PR attached to this issue: https://github.com/okta/okta-oidc-js/issues/686
Hopefully this may be helpful.

**Comment by ramkarthik77** [comment]
> @ramkarthik77 There is some discussion and a PR attached to this issue: #686
> Hopefully this may be helpful.

Thanks for your reply @aarongranick-okta. The PR really helped me a lot. I have one doubt here do I need to run my application on 2 different ports. one app1 and another app2 like below

oidcMiddleware1.on('ready', () => {
    app.listen(5456, () => console.log('app started1'));
});
oidcMiddleware2.on('ready', () => {
    app.listen(5056, () => console.log('app started2'));
});

**Comment by aarongranick-okta** [comment]
@ramkarthik77 `oidc-middleware` is built primarily around two packages: `openid-client` and `passport`. I am not sure in this case if a separate Express instance is necessary or not. It may be a feature the original author of the PR wanted, or it may be a workaround to overcome some static/instance variables used within these modules.

The good news is Okta is 100% compatible with OpenId/OAuth 2.0 so you have several choices on how to implement your solution. `oidc-middleware` is one option, and with some hacking may serve your needs very well. But another package may provide better options for you. Please let us know what you discover. Thanks!
