### ISSUE TITLE
Error while resolving signing key for kid . Unable to verify first certificate

### ISSUE THREAD

**Issue by GowthamRajagopal26** [okta/okta-oidc-js#987]
## I'm submitting this issue for the package(s):

- [x] jwt-verifier
- [ ] oidc-middleware

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
After my okta authentication I am verifying the token using jwt okta verifier by passing the clientid and the issuer.

I tried pasting the token received from okta in jwt.io and verified the information with that of the information passed in the okta verifier. The information matches. but the code goes to the catch block and throws the error mentioned below in the screenshot

I also noticed that the mentioned okta verifier is working with different okta tenant and issuer 

The new okta tenant is setup with same as the old one just with **different authentication method** and is **exposed outside the proxy environment.**

**Working Okta Authentication**: 

"amr": [
    "mfa",
    "kba",
    "pwd"
  ],

**Non-Working OKTA Authentication**

"amr": [
    "mfa",
    "otp",
    "pwd"
  ],

## Expected behavior

Expect a working solution without setting the strictssl as false in node js.  

## Environment

- Package Version: 0.0.16 (tried with latest version too still getting same error)
- Browser: Chrome
- OS: Windows 10
- Node version (`node -v`): 12.14.1
- Other:
![Error Occurred](https://user-images.githubusercontent.com/82559964/114977642-a336c480-9ea5-11eb-86e7-0a24a6518f22.png)
![Code](https://user-images.githubusercontent.com/82559964/114977871-088ab580-9ea6-11eb-936c-638bd2e5d006.png)

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue.
Internal ref: [OKTA-387834](https://oktainc.atlassian.net/browse/OKTA-387834)

**Comment by tcboles** [comment]
I am having this same issue. Is there any updates?

**Comment by jayendrajatav** [comment]
@denysoblohin-okta 

We are getting same issue, can you please provide us required solutions.
