### ISSUE TITLE
JWT-verifier -> Unable to find a signing key that matches 'xxxx'

### ISSUE THREAD

**Issue by Pixelatex** [okta/okta-oidc-js#998]
## I'm submitting this issue for the package(s):

- [*] jwt-verifier
- [ ] oidc-middleware

## I'm submitting a:
- [ ] Other (Describe below)

I keep getting this error and I can't for the life of me find out why this is happening. After logging into okta, I use the accesstoken and send it to my node backend so I can get protected data.

Here I use the jwt verifier package to check if the accesstoken is actually valid. I can verify the token in jwt.io so it works, it's the right kind.

I'm using our domain company.okta.com/oauth2/default so I don't understand why it doesn't work.

```
const oktaJwtVerifier = new OktaJwtVerifier({
  issuer: `https://${process.env.OKTA_DOMAIN}/default`, // required
})

await oktaJwtVerifier.verifyAccessToken(adminToken, '0oao1o272wX0yOF225d6') // my audience as defined in okta but tried this with default as well.

```

I keep getting the `Error while resolving signing key for kid "hBLe8Pk0HtpKnAeQ2LYKzA3XYhWTZJpxlkF-1OCr4bo"` error... what am I missing?

## Environment

- Package Version: ^2.1.0
- Browser: chrome
- OS: osx
- Node version (`node -v`): 15.14.0
- Other:

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for report @Pixelatex.

> After logging into okta

Are you using the same issuer (`https://${process.env.OKTA_DOMAIN}/default`) when signing in?

Is specified 'kid' `hBLe8Pk0HtpKnAeQ2LYKzA3XYhWTZJpxlkF-1OCr4bo` returned from either of authorization servers endpoints?

https://${process.env.OKTA_DOMAIN}/oauth2/default/v1/keys
https://${process.env.OKTA_DOMAIN}/oauth2/v1/keys

**Comment by Pixelatex** [comment]
I don't really have an issuer field when I login. We are using next-auth which only accepts client_id, client_secret and domain.

The domain is company.okta.com/oauth2

oauth2/v1/keys returns hBLe8Pk0HtpKnAeQ2LYKzA3XYhWTZJpxlkF-1OCr4bo as the key while the default/ path returns a different one

**Comment by oleksandrpravosudko-okta** [comment]
Tokens issued by org authorization server (company.okta.com/oauth2) can't be validated by custom authorization server (company.okta.com/oauth2/default) - you probably want to have token issued by custom authorization server during sign in. Please check out [Authorization Servers ](https://developer.okta.com/docs/concepts/auth-servers/#which-authorization-server-should-you-use) doc page in case you haven't already.

**Comment by Pixelatex** [comment]
Right, so this is my bad on misunderstanding okta's auth servers. I need to use my company.okta.com/oauth2/default as my signin.

Will try it!
